### ISSUE TITLE
support for color functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#1]
In Function Builder, some of the required functions involve color filtering. We currently don’t have support for that, but there is a related scenery issue: https://github.com/phetsims/scenery/issues/158.

The color functions are:

• **Grayscale** (non-invertible) - converts the input image to grayscale

• **Color inversion** (invertible) - maps colors in the input image to the opposite side of the RGB color wheel

• **Warhol** (non-invertible) - creates a 2x2 grid of the input image, using 4 colors (#FF51E7, #06FFAF, #FAFF69, #5871FF). All non-tranparent pixels in the input image are mapped to one of the 4 colors. Each background is one of the 4 colors.

*Non-invertible* means that an output image dragged backwards through the function cannot produce the original input image. 

Here's a visual example of each color function, courtesy of @amanda-phet:

![pastedgraphic-4](https://cloud.githubusercontent.com/assets/3046552/9777964/985d4438-5727-11e5-89b9-6f419a126580.png)

**Comment by pixelzoom** [comment]
Skype conversation:

[9/9/15, 1:09:05 PM] Sam Reid: WebGL is a natural solution for color mapping like that.  Not sure what to do for webgl-less platforms.
[9/9/15, 1:09:35 PM] Sam Reid: When I have tried pixel ops on canvas itself, it is often too slow to use.  Though if the images are small enough, pixel ops may be feasible there.
[9/9/15, 1:09:41 PM] Chris Malley: omit those functions from the sim?
[9/9/15, 1:10:00 PM] Chris Malley: (on WebGL-less platforms)
[9/9/15, 1:10:15 PM] Chris Malley: I can ask my team if that's an option.
[9/9/15, 1:10:39 PM] Sam Reid: Well, since the function evaluation doesn’t have to be “realtime” e.g. happening every frame at 60fps, perhaps it would be ok to experiment with canvas pixel ops.
[9/9/15, 1:13:39 PM] Chris Malley: it has to happen as the user drags the image through a "function machine". but i guess the image could be generated as soon as the input and functions are selected.
[9/9/15, 1:14:11 PM] Chris Malley: but the point of the function machine is that the user sees the change happening as they drag their input through the machine.
[9/9/15, 1:14:11 PM] Sam Reid: yes, and you could gradually “reveal” the change as it drags though despite pregenerating the image
[9/9/15, 1:14:16 PM] Chris Malley: yep

**Comment by pixelzoom** [comment]
I asked @amanda-phet via email:
> Something to discuss at design meeting related to these color functions…  WebGL is a natural solution for color mapping. But there is no easy/obvious fallback for platforms that don’t have WebGL.  Would it be acceptable to omit these functions from the sim if we detect that a platform doesn’t support WebGL?

She replied:
> I’ll add it to Thursday’s agenda. I am fine with that solution but it would be good to run by the team.

**Comment by jonathanolson** [comment]
@amanda-phet, how is the Warhol function invertible? Its output range of images is much smaller than "every possible image", and maps multiple images (those with the same alpha channel) to one result.

**Comment by pixelzoom** [comment]
My bad, the Warhol function is non-invertible in the design doc. First comment above edited to reflect the correction. And I'm going to delete this comment and @jonathanolson's for issue hygiene :)

**Comment by jonathanolson** [comment]
Also, the "changes as they drag it through" - is that like a slow fade for the entire image, or a sharp boundary where it changes from "before" to "after", or something else?

**Comment by pixelzoom** [comment]
See the design doc at https://docs.google.com/document/d/1S6pkoJODPNZFtkLaSmk2MKzh2aAH6lk30pqCTxTX8z8/edit

There is a "spy glass" at the boundary where 2 functions meet that lets you see what is coming out of the left function and going into the right function.  So no, there is no slow fade.

**Comment by pixelzoom** [comment]
See the design doc at https://docs.google.com/document/d/1S6pkoJODPNZFtkLaSmk2MKzh2aAH6lk30pqCTxTX8z8/edit

There is a "spy glass" at the boundary where 2 functions meet that lets you see what is coming out of the left function and going into the right function.  So no, there is no slow fade, and you don't see an animation of the transformation occurring.

**Comment by jonathanolson** [comment]
Since there is no fading, it seems like using Canvas pixel mapping and/or Canvas operations would be best. WebGL would do the same thing (but with a lot more code), and I wouldn't recommend starting with it.

For the RGB inversion, Canvas blending mode "difference" (globalCompositeOperation) could be used.

For the Warhol effect, you could draw in four smaller copies of the image, set globalCompositeOperation to "source-in", then draw the "foreground" colors on top (four filled quads in one image), then draw THAT result onto the background.

For the puzzle effect, Canvas supports drawing part of an image.

The rest of the functions could be done by transforming how the original image is drawn (or not drawn at all).

We'd also need to check browser compatibility for all of the blending modes before they are used. See visual effects at https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by jonathanolson** [comment]
Also if we use the Canvas method described above, no Scenery work in https://github.com/phetsims/scenery/issues/158 would be needed for this feature.

**Comment by pixelzoom** [comment]
I'll process with Canvas approach, will consult with @jonathanolson.

**Comment by pixelzoom** [comment]
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.1/function-builder_en.html

This dev version demonstrates all functions applied to all cards. Everything is implemented using the most basic Canvas API, no globalCompositeOperation (which is likely to have issues browser compatibility issues).  Even this is exhibiting browser compatibility issues. It works reliably with Chrome. It’s totally untested on IE. And if you run it on Safari or Firefox, it will look fine sometimes, and really messed up other times (images will be offset).

**Comment by pixelzoom** [comment]
About the Safari and Firefox weirdness, @jonathanolson said:

> One complication could be running on retina devices. the putImageData/etc. deal with the "big" pixels, which may have subpixels. Canvas in Safari would actually have 4x the number of pixels actually rendered, which may be throwing off browsers here. See https://github.com/phoboslab/Ejecta/issues/4. Let me know if you want to collaborate to nail down this issue.

**Comment by pixelzoom** [comment]
Also worth noting in the 1.0.0-dev.1 is that image quality generally stinks in Firefox. And using mipmaps in this case is practically not an option.

**Comment by pixelzoom** [comment]
These functions are all basically working. The sub-issue of their layout has been moved to https://github.com/phetsims/function-builder/issues/3.  Closing.
