### ISSUE TITLE
Publish a PhET-iO Version

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#100]
In https://github.com/phetsims/phet-io/issues/548 @kathy-phet said:

> Priority is definitely Function Builder. So let's focus on getting that one tested and published to see if input/playback works.

From https://github.com/phetsims/phet-io/issues/548#issuecomment-240588553
I elaborated a bit in an email to @pixelzoom:

Chris,

I wanted to notify you ASAP that Function Builder will be undergoing development/testing/release for PhET-iO for record and playback (which doesn't require tandemization). I already made changes in master for phetsims/function-builder#99, which is assigned to you for review.

Just wanted to get you in the loop as soon as I could.

Best Regards,
Sam

In https://github.com/phetsims/phet-io/issues/548#issuecomment-240835722 @pixelzoom replied:

> https://github.com/phetsims/function-builder/issues/99 looks good and is closed.  

I've finished local testing (including testing built versions) and would like to take the next step of testing a version published online, so I'll create a dev release.  If my tests work out well, the next step will be QA team testing.

**Comment by samreid** [comment]
The latest version is 1.0.0 (both for published and for dev), so the next version will be `1.1.0-dev.1` which is already specified in the package.json.

**Comment by samreid** [comment]
@pixelzoom would you like me to bump package.json to `1.1.0-dev.2` after publishing `1.1.0-dev.1`?  As far as I know, different developers have different conventions for when to update this version.

**Comment by pixelzoom** [comment]
I typically update just before publishing, with the exception of the *-dev.1 version.  I pre-set 1.1.0-dev.1 at the same time as I created the 1.0 release branch, so I wouldn't forget to move master to 1.1.0.   Perhaps I should have set it to 1.1.0-dev.0, so that the "increment dev number just before publishing" rule applies in all cases.

**Comment by samreid** [comment]
I am stuck on Step 5 from https://github.com/phetsims/phet-info/blob/master/deployment-info/sim_deployment.md from the "PhET-iO Deployment Guidelines" section.  I don't think we are deploying to figaro any longer, and I tried using phet-server and ox in that scp command, and bash tells me `node name or service name not known`.  @mattpen can you help me?

**Comment by samreid** [comment]
@mattpen and I revised the "how to deploy" instructions for the new server, and @mattpen contacted Morlino about granting access to other developers.  @mattpen completed the deploy for now.  Next step is testing, I'll leave it assigned to me for testing.

**Comment by samreid** [comment]
Publish is complete, and there is a new issue for testing, closing.
