### ISSUE TITLE
Update to use QueryStringMachine

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#101]
I'd like to convert Function Builder to use QueryStringMachine as a test case for fleshing out the API.

**Comment by samreid** [comment]
I converted to use QueryStringMachine in the preceding commit and tested against the phet.chipper.getQueryParameter for several cases.  @pixelzoom can you please take a look at the proposed API in FBQueryParameters.js and let me know if you have any recommendations?

Additional review questions:
1. When `allowedValues` is provided, should QueryStringMachine automatically make the first element the default, or should the default always be provided separately?
2. `{ type: 'flag' }` appears frequently.  Should we provide a separate way of dealing with them, such as factoring out `var FLAG = { type: 'flag' }` or putting an array list of flag items?  The former would look like:

```js
  var FLAG = { type: 'flag' };
  var FBQueryParameters = QueryStringMachine.parse( {

    // enables developer-only features
    dev: FLAG,

    // adds the 'Test' screen
    testScreen: FLAG,

//... etc.
```

The second option could read like:

```js
  var FBQueryParameters = QueryStringMachine.parse( {

    // when to initialize screen views: 'onDemand'|'onStart'
    initScreenViews: { type: 'string', allowedValues: [ 'onDemand', 'onStart' ], defaultValue: 'onStart' },

    // when to initialize scenes: 'onDemand'|'onStart'
    initScenes: { type: 'string', allowedValues: [ 'onDemand', 'onStart' ], defaultValue: 'onStart' },
  }, {
    flags: [

      // enables developer-only features
      'dev',

      // adds the 'Test' screen
      'testScreen',

      // populates the output carousel with 1 card of each type
      'populateOutput',

      // makes all animation run slowly, so that things are easier to grab while they're animating
      'slow',

      // puts a red stroke around containers in the carousels, so that empty containers are visible
      'showContainers',

      // shows the answer in the Mystery screen
      'showAnswer',

      // plays all Mystery challenges, in order
      'playAll',

      // shows all colors, in order that they appear in pool, for Mystery challenges
      'showAllColors'
    ]
  } );
```

**Comment by pixelzoom** [comment]
Answers to review questions:

> 1. When allowedValues is provided, should QueryStringMachine automatically make the first element the default, or should the default always be provided separately?

Provide default value separately.

> 2. 2. { type: 'flag' } appears frequently. Should we provide a separate way of dealing with them ...

I like the way things look in @9a23f31c717d1bba88235461286c0db5b6b0a1da.  It's clear what's going on, and I don't mind the duplication of 'flag' type.  

Additional suggestions:

Instead of type 'flag', how about type 'boolean' that defaults to 'true'?  E.g., `?ea` would be equivalent to `?ea=true`.

**Comment by samreid** [comment]
In https://github.com/phetsims/query-string-machine/issues/1 I renamed parse => getAll to match get.

**Comment by samreid** [comment]
> Instead of type 'flag', how about type 'boolean' that defaults to 'true'? 

Are you saying we would use `{type:'boolean', defaultValue:true}` for these cases?  I don't think that would work as expected, because we want this behavior:

(no query parameter supplied) => false
?ea => true
?ea=true => true
?ea=false => false
?ea =treu => Error

If we used `{type:'boolean', defaultValue:true}`, I think the table would become:
(no query parameters supplied) => true (INCORRECT)
?ea => true
?ea=true => true
?ea=false => false
?ea =treu => Error

**Comment by pixelzoom** [comment]
You're right, what I proposed doesn't work.  Looks like there's a legitimate need to distinguish 'flag' from 'boolean'.

**Comment by samreid** [comment]
> E.g., `?ea` would be equivalent to `?ea=true`, and `?ea=false` would work properly (which is currently not the case).

If I change initialize-globals.js from
```js
var enableBasicAssertions = enableAllAssertions || ( !isProduction && !!phet.chipper.getQueryParameter( 'ea' ) );  // enables basic assertions
```
to
```js
var enableBasicAssertions = enableAllAssertions || ( !isProduction && QueryStringMachine.get( 'ea', { type: 'flag' } ) );  // enables basic assertions
```
then ?ea=false works properly.

So I think everything in this issue is complete. (@pixelzoom please reopen if there is more to do here).  In https://github.com/phetsims/query-string-machine/issues/1 we can proceed with next steps, including code review and broader usage.
