### ISSUE TITLE
Estimate for a "patterns only" version

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#103]
2/23/17 design meeting: 

Provide an estimate for a version of Function Builder that has:
• Patterns screen with no changes
• Mystery screen with patterns instead of numbers, no table, no graph

For the revised Mystery screen, the challenges are:

• Colors for mystery functions are randomly chosen from color sets. The icons for pattern functions look good on specific background colors, and we don't want to use those colors in mystery mode because it would give away the function.  Perhaps make all functions gray in mystery mode, then reveal icon+backgroundColor when revealing identity. @ariel-phet suggested using colored question marks if we use gray mystery functions.  

• @ariel-phet suggested adding additional input patterns to the revised Mystery screen. This should be as simple as adding new PNG files for the additional inputs. (See `PatternsScene.cardContent`.)

**Comment by pixelzoom** [comment]
2/23/17 design meeting:
Ideally do this estimate by 3/3/17.
Do this after graphing-lines estimate in https://github.com/phetsims/graphing-lines/issues/66.

**Comment by pixelzoom** [comment]
Co-assigning to @amanda-phet to come up with a name for this sim, so that I can create the corresponding repository.

**Comment by pixelzoom** [comment]
@ariel-phet I'll need 2-4 hours of exploratory development to provide a reliable estimate. Or I can provide a WAG.  Let me know which you'd prefer.

**Comment by ariel-phet** [comment]
@pixelzoom lets do exploratory development. Perhaps once Unit Rates is into RC or during the time you are working no Graphing Lines.

**Comment by pixelzoom** [comment]
Before starting exploratory work, I'll need a repository for the code.  So we need to choose a sim name. We can change the sim name later, but not at zero cost (repository needs to be move, code needs to be changed, all developers need to change their working copy,...)

Some possible names:

Function Builder: Patterns
Pattern Builder
Pattern Functions

(Side note: I've always wondered why the term "pattern" was used instead of "image".)

@amanda-phet What sim name do you want me to use?

**Comment by ariel-phet** [comment]
@amanda-phet @pixelzoom I would suggest Function Basics for the moment. I know it is not zero cost to change later, but we have changed names on other repositories and the cost has been acceptably small.

As for the side note...it is true that you are acting on images, but you are trying to identify the pattern of how different function act on the image, but that does contrast with the names of the next two screens a bit.

**Comment by amanda-phet** [comment]
@ariel-phet Function Basics was one that I liked the best from our previous discussion. I also like Function Builder: Patterns for users who would recognize the Patterns Screen. 

Let's go with Function Basics!

**Comment by pixelzoom** [comment]
Repository function-basics has been set up, with sim title "Function Basics".   Further discussion will take place in that repository. Closing.
