### ISSUE TITLE
revised the screenshot

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#106]
See https://github.com/phetsims/function-basics/issues/12

We decided to use a screenshot of the Numbers screen, to differentiate from function-basics sim.

**Comment by amanda-phet** [comment]
Here is the screenshot! 

![screen shot 2017-04-13 at 1 55 07 pm](https://cloud.githubusercontent.com/assets/7852916/25021857/df3d6b46-2050-11e7-9a04-646b2db35894.png)

**Comment by ariel-phet** [comment]
@amanda-phet once we revise the screenshot we should review activities and contact any authors if they are using the previous screenshot as a reference to the sim (for telling their students which sim to use)

**Comment by pixelzoom** [comment]
@phet-steele Would you mind creating this screenshot, as shown above? Note the '3' card that is partially inserting into the builder.

**Comment by pixelzoom** [comment]
@phet-steele Would you mind creating this screenshot, as shown above? Note the '3' card that is partially inserting into the builder. You can check in to master only.

**Comment by phet-steele** [comment]
New screenshot added, back to you @pixelzoom.

**Comment by phet-steele** [comment]
Also back to @amanda-phet because of @ariel-phet's comment to review activities that may use the old screenshot.

**Comment by pixelzoom** [comment]
Verified, thank you @phet-steele.

**Comment by pixelzoom** [comment]
There are no immediate plans to republish this sim, but we do want the screenshot to be changed on the PhET website.  My understanding is that this is a manual process, and the old screenshot is liable to appear for some time thereafter.  

@mattpen can you please take care of updating the screenshot on the PhET website?

**Comment by pixelzoom** [comment]
The screenshot is at:
https://github.com/phetsims/function-builder/blob/master/assets/function-builder-screenshot.png

**Comment by mattpen** [comment]
I can upload the new screenshot into the directory for the latest version of the sim.  The old screenshot will be cached by Varnish for up to 30 days.  If there is an urgent need, I can clear the cache in the off hours, but   this would not be preferable.

**Comment by pixelzoom** [comment]
@amanda-phet Are you OK with the old screenshot being visible for up to 30 days?

**Comment by mattpen** [comment]
@pixelzoom @amanda-phet - I forgot, but the static files aren't cached by varnish any longer but accessed directly.  The new screenshots are now up on the main website.

**Comment by mattpen** [comment]
OK to close?

**Comment by pixelzoom** [comment]
Excellent, thanks @mattpen!  Closing.

**Comment by amanda-phet** [comment]
Oops, I had this written but never submitted it :) 

If we can get the screenshot changed now, being visible for 30 days shouldn't be too bad. @mattpen please go ahead and upload the new screenshot for Function Builder

**Comment by pixelzoom** [comment]
@amanda-phet The new screenshot is live on the PhET website.

**Comment by amanda-phet** [comment]
I also double-checked the activities and none of them had a screenshot of the sim page in the lesson or activity sheet, so we're all good there!

**Comment by mattpen** [comment]
@pixelzoom - The screenshot reverted to the original when version 1.0.4 was deployed for function builder.  I've fixed the screenshot on the website again, but it will need to be added to the release branch for FB to remain persistent.

**Comment by pixelzoom** [comment]
Ah.... The screenshot never got cherry-picked to the 1.0 branch.  I've taken care of that in the above commit.  It will be published in the impending 1.0.7 maintenance release (https://github.com/phetsims/function-builder/issues/110), probably sometime in early June.

**Comment by pixelzoom** [comment]
@samreid In case it's important to have the correct screenshot in 1.1-phetio, I've updated it in that branch too.
