### ISSUE TITLE
make '?' larger and bold on Mystery functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#108]
In https://github.com/phetsims/function-builder-basics/issues/1, we made the questions marks on the Mystery functions larger and bolder.   Since I need to do a 1.0 maintenance release to pick up https://github.com/phetsims/function-builder/issues/107, I think this enhancement is worth adding too.

The related changes are https://github.com/phetsims/function-builder/commit/440ccd20f72e9044c4383fcde3ae187baf399bf3 and https://github.com/phetsims/function-builder/commit/f6412332a16ad776826690ef37c8d645d200fcb2.

**Comment by pixelzoom** [comment]
This change was already present in master at the result of  phetsims/function-builder-basics#1, and I patched it into the 1.0 branch. I will appear in the 1.06 maintenance release.

**Comment by pixelzoom** [comment]
Reopening. I just noticed issue https://github.com/phetsims/tasks/issues/690.  Apparently there is a 1.1-phetio branch.  @samreid Does this need to be patched there too?

**Comment by samreid** [comment]
Function Builder had a PhET-iO "lite" instrumentation for playbacks.  I don't think anyone is using it any longer, so no need to update it at the moment.
