### ISSUE TITLE
suggestions for how to implement 'spy glass' feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#11]
In Function Builder, there's a "Spy Glass" feature.  Here's a mockup from the design document:

![screenshot_18](https://cloud.githubusercontent.com/assets/3046552/13583025/9d9dfe7e-e46c-11e5-934b-8e33fd1435fa.png)

The "Spy Glass" check box (lower left) toggles the visibility of the spy glasses.  When the spy glasses are visible, the card that is being dragged through the function builder is visible when it's dragged past one of the spy glasses. In the mockup above, you can see the card (which has an equation on it) through the rightmost spyglass.

A more general version of this problem is: I have a Rectangle, and a checkbox that controls the visibility of N circular holes that appear in the interior of the Rectangle, through which I can view Nodes that are dragged behind the Rectangle. Think of it as cheese that can be toggled between Swiss and cheddar :) How do I create these "holes"?

Suggestions from @samreid @jonathanolson @jbphet (or anyone else) will be appreciated.

**Comment by samreid** [comment]
Use Path/Shape instead of Rectangle, and create the shape with lineTo/arc commands.  Similar to how we cut the hole out of the ProbeNode line 147.  Also keep in mind that when creating path with holes that the clockwise/counterclockwise matters. (I think inner shapes have to go opposite direction of outer shapes, but not 100% sure).

**Comment by pixelzoom** [comment]
So I'll need 2 shapes, one with holes and one without.  And I'll need to line up the spy glasses (lens+handle) with these holes.  Do I understand that correctly?

**Comment by samreid** [comment]
> So I'll need 2 shapes, one with holes and one without. And I'll need to line up the spy glasses (lens+handle) with the holes. Do I understand that correctly?

Yes, you understood my suggestion.

Brainstorming... another way to do this could be to make the bottom half with semicircle cutouts and the top half with semicircle cutouts.  Then to show the cutouts filled in, put a larger rectangle/circle behind the holes.

I suspect @jonathanolson will have good suggestions as well.

**Comment by pixelzoom** [comment]
Another complication in function-builder is that spy glasses are supposed to appear only to the right of "slots" in the builder that are populated with functions. For example, if the builder has 3 slots, and only the left slot is populated, then a spy glass appears only for that slot.  So it sounds like I'll need to either (a) eagerly create a different Shape for each possible configuration, or (b) (better) dynamically create the Shape based on which slots are populated with functions.

**Comment by samreid** [comment]
> So I'll need 2 shapes, one with holes and one without. 

Or just create one shape with holes and then (when closed) cover the holes with circles or rectangles that are slightly bigger than the holes.

**Comment by jonathanolson** [comment]
The Shape "make the outline counter-clockwise (or clockwise) and then the holes clockwise (or counter-clockwise" that @samreid mentioned is the approach to making shapes with holes. Note that for circles, you'll want to moveTo so that it doesn't stroke from the end of your outline to the start of your hole.

I'm fine with either:

> dynamically create the Shape based on which slots are populated with functions.

OR 

> Or just create one shape with holes and then (when closed) cover the holes with circles or rectangles that are slightly bigger than the holes.

Performance isn't a huge concern, since the shape isn't going to be changing every frame.

Happy to collaborate to clarify any issues that arise.

**Comment by pixelzoom** [comment]
> Performance isn't a huge concern, since the shape isn't going to be changing every frame.

But if the shape is changing dynamically, if will need to change while the user is dragging functions in/out of the builder.  So performance may be an issue.

**Comment by jonathanolson** [comment]
> But if the shape is changing dynamically, if will need to change while the user is dragging functions in/out of the builder. So performance may be an issue.

I was imagining this as a "user releases mouse (or dragged something over), and it immediately toggles from "no hole" to "complete hole" or vice versa.

Is this instead something where there are more shapes in-between "no hole" and "complete hole", where every mouse/touch-move would be changing the same?

**Comment by pixelzoom** [comment]
User toggles spy glasses on/off via a check box.  If a function is removed from the builder, the spyglass on it's right edge disappears. If a function is added to the builder, a spyglass appears on it's right edge.

**Comment by jonathanolson** [comment]
The safest way to start if concerned about performance is to make a shape with all of the holes, and use circles in the foreground (with the same fill), which will be transparent when there are spyglasses. There may be a chance of a seam between the filled-in hole and the outer shape (browser-specific chance).

The safest way to start for appearance and code complexity is to change the shape dynamically (on one path) by changing whether holes are included or not.

I would first opt for the "safe for appearance and code complexity" option personally.

**Comment by pixelzoom** [comment]
Thanks for the pointers.

**Comment by samreid** [comment]
> The safest way to start for appearance and code complexity is to change the shape dynamically (on one path) by changing whether holes are included or not.

If my combinatorics are correct this would result in 2^3=8 distinct shapes.

**Comment by jonathanolson** [comment]
> If my combinatorics are correct this would result in 2^3=8 distinct shapes.

With 3 spyglasses, yes. May be preferable to create the 8 shapes on startup.

**Comment by samreid** [comment]
Or 4 shapes, if using the "covering" approach.

**Comment by pixelzoom** [comment]
Hmmm... I'll also need to cut holes in the function placeholders (dashed lines where you drop functions into the builder).  This "hole cutting" approach is getting too complicated.   I think I'll investigate a different approach, where the "spy glass" feature is its own layer (Node) with cards as children and clipAreas for the spy glass holes.

**Comment by pixelzoom** [comment]
Closing.  Thanks to all who contributed ideas.
