### ISSUE TITLE
maintenance release: Function Builder 1.0.7

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#110]
To pick up these 3 fixes:

phetsims/function-builder#109 (symmetry problems with card images)
phetsims/function-builder-basics#18 (artifacts from ?C function)
screenshot from master

Cherry pick files from function-builder master:

```
% git checkout 1.0
% git checkout master -- assets/card-icons.ai
% git checkout master -- images/cards
% git checkout master -- js/patterns/common/Scene.js
% git checkout master -- js/patterns/model/PatternsScene.js
% git checkout master -- js/patterns/model/functions/Shrink.js
```

Increment version id to 1.0.7. 

Then build, test, deploy:

```
% grunt checkout-shas
% grunt 
// test
% grunt deploy-production
```

**Comment by pixelzoom** [comment]
This is on hold until the above issues are verified in https://github.com/phetsims/tasks/issues/844, and Function Builder: Basics 1.0.0 is published.

**Comment by phet-steele** [comment]
@pixelzoom, please also grab the screenshot from master. The 1.0 branch still has the old screenshot and overwrote the new one on the website after a maintenance release.

**Comment by pixelzoom** [comment]
Will do, I've added the cherry-pick command above for `function-builder-screenshot.png`.

**Comment by pixelzoom** [comment]
I handled the screenshot in issue #106, since there were multiple branches (1.0, 1.1-phetio) that didn't have the current screenshot.

**Comment by pixelzoom** [comment]
@samreid with these fixes (replacing all of the card images, among other things), 1.1-phetio is going to be horribly out of sync.  And I've lost track of other changes that have not been propagated to 1.1-phetio.  Your opinion on how to proceed with the 1.1-phetio branch?

**Comment by samreid** [comment]
For the long run, we will have to figure out how to deal with issues like this, but in this case, the PhET-iO "lite" sim does not have any upcoming usage and does not need to be maintained.

**Comment by pixelzoom** [comment]
Something went wrong with build-server, so 1.0.7 was messed up.  I had to then publish 1.0.8, which mysteriously worked.  

Closing/.
