### ISSUE TITLE
rectangle -> ?C = swastika

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#111]
Noted during RC testing of function-builder-basics, https://github.com/phetsims/tasks/issues/844.

When you run the blue rectangle through `?C` function, you get a swastika:

![screenshot_33](https://cloud.githubusercontent.com/assets/3046552/26261143/4e38fd28-3c8d-11e7-92fb-81af6f5207e5.png)

This is not a new issue, not related to the revised artwork (#109) and is present in the version published on the PhET website.

![screenshot_35](https://cloud.githubusercontent.com/assets/3046552/26263371/c7e3cf6a-3c95-11e7-949d-b438887b20b3.png)

**Comment by pixelzoom** [comment]
I spoken with @amanda-phet about this. Our initial thought was to replace the rectangle with a different shape, perhaps a polygon. But I think we should discuss this a bit more -- perhaps we should just remove the black stroke?  The rectangle would then look unchanged when run through `?C`, which might be a nice learning experience.

**Comment by pixelzoom** [comment]
Skype discussion with @amanda-phet:

[5/19/17, 12:41:19 PM] Amanda McGarry: I think it looks funny to not have a stroke on just one shape
[5/19/17, 12:41:42 PM] Amanda McGarry: I’ve always thought the star needed the stroke because it’s yellow, and we want contrast
[5/19/17, 12:41:51 PM] Amanda McGarry: but maybe we should remove it from all of the shapes
<img width="127" alt="1495219331" src="https://cloud.githubusercontent.com/assets/3046552/26262784/2efbf7a2-3c93-11e7-8dda-fcb3d1ffb3cb.png">
[5/19/17, 12:43:33 PM] Amanda McGarry: never mind, the yellow only has a 1.28:1 contrast ratio with white, that’s not enough
[5/19/17, 12:50:40 PM] Chris Malley: change color of star?
[5/19/17, 12:50:56 PM] Amanda McGarry: yeah I’m playing around with it
<img width="126" alt="1495219911" src="https://cloud.githubusercontent.com/assets/3046552/26262850/73939a82-3c93-11e7-87f4-4ae09a9db1a1.png">
[5/19/17, 12:52:19 PM] Chris Malley: look good to me.
[5/19/17, 12:52:57 PM] Amanda McGarry: the orange is still fairly low contrast.
<img width="131" alt="1495219977" src="https://cloud.githubusercontent.com/assets/3046552/26262807/4d4be32a-3c93-11e7-962b-166e07271904.png">
<img width="126" alt="1495219911" src="https://cloud.githubusercontent.com/assets/3046552/26262834/6852fe60-3c93-11e7-9ec1-da98b78ae2a5.png">
[5/19/17, 12:53:09 PM] Amanda McGarry: Should I try to export these or ask Cheryl to do them?
[5/19/17, 12:53:51 PM] Chris Malley: It sounded like there were some tricks, so perhaps ask Cheryl.
[5/19/17, 12:55:46 PM] Chris Malley: Ariel likes this solution too, I sent him your mockup.
[5/19/17, 12:56:49 PM] Chris Malley: Are we sure that removing the stroke doesn't have consequences for other functions?
[5/19/17, 12:58:06 PM] Amanda McGarry: I played around a bit and it looks good to me
[5/19/17, 12:58:19 PM] Amanda McGarry: I was worried about the rainbow function but the black stroke turns into a white one anyway
[5/19/17, 12:58:22 PM] Chris Malley: I think it could actually make Warhol look a little better.
[5/19/17, 12:58:26 PM] Amanda McGarry: yeah

**Comment by pixelzoom** [comment]
@clmccutchan when you have time... I'll need:

rectangle.png 108x64
circle.png 108x108
triangle.png 126x126
star.png 126x122 (new color)
card-icons.ai

Thanks!

**Comment by pixelzoom** [comment]
Here's what we settled on, from @amanda-phet email:

![screenshot_34](https://cloud.githubusercontent.com/assets/3046552/26263270/57531b7a-3c95-11e7-8bfb-0ea05bc96776.png)

**Comment by pixelzoom** [comment]
@clmccutchan when you have time... I'll need:

rectangle.png 108x64
circle.png 108x108
triangle.png 126x126
star.png 126x122
card-icons.ai

Thanks!

**Comment by clmccutchan** [comment]
@pixelzoom @amanda-phet I've emailed the new pngs and ai file to both of you.

**Comment by pixelzoom** [comment]
Files received, thanks @clmccutchan.

**Comment by pixelzoom** [comment]
@clmccutchan I did not receive a new card-icons.ai file.   It looks like you put the revised icons in new-shapes.ai.   Please put them in card-icons.ai (replacing the relevant old icons) and send me the revised card-icons.ai.

**Comment by pixelzoom** [comment]
Please make sure that you're modifying the the latest card-icons.ai, which can be found in https://github.com/phetsims/function-builder/tree/master/assets.

**Comment by pixelzoom** [comment]
@amanda-phet @phet-steele Please verify in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.1.0-dev.4/function-builder_en.html

Verify that:
(1) The swastika problem is gone.
(2) No additional issues have been introduced by removing the stroke from the 4 basic shape.

**Comment by pixelzoom** [comment]
Revised card-icons.ai received from @clmccutchan, thanks!

**Comment by pixelzoom** [comment]
@amanda-phet @phet-steele This issue is blocking both a Function Builder maintenance release (#110) and continued testing of Function Builder: Basics (https://github.com/phetsims/tasks/issues/844).  So high priority on verification please.

**Comment by phet-steele** [comment]
> So high priority on verification please.
You caught me typing this up!

?c still has little lines through the rectangle on high resolution screens:
<img width="178" alt="screen shot 2017-06-05 at 1 56 28 pm" src="https://cloud.githubusercontent.com/assets/5863899/26801682/da2faa50-49fa-11e7-883e-bbb7bcf01150.png">

The lines are more pronounced with double ?c:
<img width="199" alt="screen shot 2017-06-05 at 1 56 46 pm" src="https://cloud.githubusercontent.com/assets/5863899/26801681/da2e097a-49fa-11e7-8391-c562ca27e52c.png">

180 degrees -> rainbow -> warhol shows that some colors on the triangle (the yellow) are not clearly segregated. Not sure if this is a result of getting rid of the stroke or by changing the image size:
<img width="123" alt="screen shot 2017-06-05 at 2 22 44 pm" src="https://cloud.githubusercontent.com/assets/5863899/26801680/da2b1c7e-49fa-11e7-9efe-97fe8235aed4.png">

In any case, @amanda-phet is okay with these small use cases, so no need to take action. @pixelzoom, no other issues were noticed as a result of these changes. The swastika is gone.

**Comment by pixelzoom** [comment]
@phet-steele said:
> In any case, @amanda-phet is okay with these small use cases, so no need to take action.

Via Skype, @phet-steele clarified that @amanda-phet has reviewed this, no further changes are needed, and we're OK to proceed.

Closing.
