### ISSUE TITLE
Why is "twixt" listed in phetLibs in package.json?

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#112]
I was looking into https://github.com/phetsims/circuit-construction-kit-common/issues/330 and I noticed that twixt is listed in function builder's package.json.  I removed it and it built and ran OK.  Perhaps I'm unclear what "phetLibs" is for, or perhaps it can be removed.

**Comment by pixelzoom** [comment]
"phetLibs" is supposed to include optional phet repositories; that is, repositories that are not specified in chipper/build.json.  function-builder uses twixt, and twixt is an optional repository. So I would expect that it needs to be included in package.json, and I'm surprised that it works without it.   FYI, 10 other projects include twixt via their package.json.

**Comment by pixelzoom** [comment]
vegas and vibe are other optional repositories that need to be specified in a project's package.json.

**Comment by pixelzoom** [comment]
I verified that function-builder builds and runs without "phetLibs" in its package.json.

make-a-ten has this "phetLibs" in package.json:

```js
    "phetLibs": [
      "twixt",
      "vegas",
      "vibe"
    ]
```

If I totally remove "phetLibs", make-a-ten also builds and runs. 

Very curious. I suspect that something has changed within the build process.

**Comment by pixelzoom** [comment]
I verified that nothing in the build process is automatically adding optional repositories to buildConfig.phetLibs, by placing the following at the end of getBuildConfig.js, and inspecting the output with and without "phetLibs" in package.json.

```js
grunt.log.writeln(  'buildConfig=' + JSON.stringify( buildConfig, null, 2 )  );
```

**Comment by pixelzoom** [comment]
Via Skype @samreid said:
> I suspect the requirejs build phase has always used *config.js.  But maybe the phetLibs was just used to look up SHAs for dependencies.json?

**Comment by pixelzoom** [comment]
phetLibs is essential to lint and published-README tasks.  If repositories are omitted, the sim will build.  But optional repos won't be linted. And they won't appear in the `git clone` instructions that appear in README.md.

**Comment by pixelzoom** [comment]
As @samreid hypothesized, phetLibs is also essential to generating dependencies.json.  If optional repos are omitted, the sim will build and run, but the optional repos will be missing from dependences.json.  Nothing will warn you about this, and you checkout-shas will also give you an incorrect set of shas in the future (optional repos will silently remain on master).

**Comment by samreid** [comment]
Should we eliminate `phetLibs` from package.jsons and try to use config.js files as ground truth?

**Comment by pixelzoom** [comment]
So... It is essential to specify optional repositories in package.json.  But there is nothing that verifies that buildConfig.phetLibs matches what is actually needed by the sim (as specified in config.js).

**Comment by pixelzoom** [comment]
This is a general issue, moved to https://github.com/phetsims/chipper/issues/580, closing.

**Comment by pixelzoom** [comment]
@samreid Note that you need to add ```"phetLibs": [ "twixt" ]``` to all CCK repos that use twixt.

**Comment by samreid** [comment]
Will do, thanks!

**Comment by pixelzoom** [comment]
@samreid Also... Since you don't have "twixt" in package.json for your CCK projects.... beware that anything you have published so far has an incorrect dependencies.json.  If you use 'grunt check-out' shas, twixt will remain on master.

**Comment by samreid** [comment]
Added twixt above, leaving closed.
