### ISSUE TITLE
revise colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#12]
From 2/4/16 meeting notes in the design document:

![screenshot_20](https://cloud.githubusercontent.com/assets/3046552/13782544/3802e54e-ea8d-11e5-81cd-73480b4d9476.png)

**Comment by pixelzoom** [comment]
Recommended to address this sometime after all 3 screens are somewhat fleshed out, so we can see the colors in context.

**Comment by pixelzoom** [comment]
Generalizing this to "revise colors", since we'll undoubtedly need to tweak not only builder colors, but colors for functions, backgrounds, etc.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to assign this to someone.

**Comment by ariel-phet** [comment]
@pixelzoom at this point, now with things fleshed out, I am fairly agnostic about this color choice.

If we go lighter, I would say we want to make sure that the dashed white outline for the function pieces cue should still stand out well, so we could not go too light.

Do you want to try lightening the current colors a bit and see if you like it better? Or feel free to close.

**Comment by pixelzoom** [comment]
@ariel-phet:

(1) I originally created this issue because @amanda-phet wanted to play with the colors, so I don't feel like this is my decision to make.  I will note that it seems odd that the only builder that's not blue is the "single scene" builder on the Patterns screen.  

(2) As noted in https://github.com/phetsims/function-builder/issues/12#issuecomment-218534219, this issue was expanded to include colors in general, not just builder colors.  In particular, I think the colors of the function in the Numbers screen could use some work. I added a bunch of functions that are not in the design document, and I spent zero time picking pleasing colors, or colors that might work together.  If you'd like me to spend time on that, I will. But since time is tight, I'd prefer to be working on implementation rather than color harmony.

Back to you for comment.

**Comment by ariel-phet** [comment]
@pixelzoom for me, the colors are pretty acceptable as is, perhaps not super harmonious, but generally bright, fun, and not causing any obvious issues. What I am saying is that if there is anything you feel like you want to change (like making the single builder blue), go ahead, otherwise I don't think there is any critical action here. 

I looked at the sim in B/W just to make sure none of the colors were causing contrast issues or such. No problems that I can see on any screen. Therefore this strikes me as very low priority.

**Comment by ariel-phet** [comment]
As a side note, @amanda-phet will likely be back online in June, so if she has strong opinions on color tweaks we can just leave it until she is available. Currently I do not feel there is anyone else on the team with strong opinions.

**Comment by pixelzoom** [comment]
5/26/16 design meeting:

• Make all builders blue. 
• For "Numbers" functions, use the same background colors as the the "Patterns" functions.

**Comment by pixelzoom** [comment]
Done, closing.
