### ISSUE TITLE
evaluate stepper option to Carousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#120]
Carousel was converted to use TWIXT/Animation in https://github.com/phetsims/sun/issues/381.  The default is `stepper: 'manual'`, which means that the client must call `step` to control the Carousel's animation.   To avoid having to make changes in this sim, `stepper: 'timer'` was added to Carousel call sites, which means that the animation will run automatically using the sim Timer.  

The responsible developer (that would be me) should evaluate what `stepper` value should be used.

**Comment by pixelzoom** [comment]
@jonathanolson randomly selected to review.

**Comment by pixelzoom** [comment]
Blocked until @samreid changes the default as planned in https://github.com/phetsims/twixt/issues/19#issuecomment-418943560.

**Comment by samreid** [comment]
https://github.com/phetsims/twixt/issues/19#issuecomment-418943560 seems to imply that the Carousel default should also be the PHET_CORE/Timer instead of manual.

**Comment by jonathanolson** [comment]
> I've changed the default for Animation to timer

That sounds like a large API change, but I see cases (like in AnimationTests) that are manually stepped but use the default still. Are there cases that still need to be updated?

**Comment by samreid** [comment]
I tried to catch as many cases as I could in the commits listed after https://github.com/phetsims/twixt/issues/19#issuecomment-433674965, but maybe I missed some.  I can re-review them.  Thanks for pointing out the missed case in AnimationTests.  I'll reassign https://github.com/phetsims/twixt/issues/19 to double check.

**Comment by pixelzoom** [comment]
`stepper: timer` (the new default for Carousel) is appropriate for function-builder. Closing.
