### ISSUE TITLE
title case

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/function-builder#122]
For phetsims/tasks/issues/953
The checkboxes that read "simplify" should read "Simplify"
![title case2](https://user-images.githubusercontent.com/41024075/45238401-eddc1300-b29e-11e8-92bd-c0c9b98ff8db.PNG)

**Comment by pixelzoom** [comment]
This checkbox was very specifically labeled "simplify", as requested by @amanda-phet in https://github.com/phetsims/function-builder/issues/90.   And I know of no convention that requires every control label to start with an uppercase letter.  (I would in fact disagree with such a convention.)

Assigning to @amanda-phet to decide whether to do anything.

**Comment by pixelzoom** [comment]
Here's the context, in the Numbers screen:

![screenshot_752](https://user-images.githubusercontent.com/3046552/45238835-6394ae80-b2a0-11e8-9034-2030afd43520.png)

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/tasks/issues/953#issuecomment-419548715, @arouinfar's opinion was that "simplify" (lowercase) was just fine in this context.  @amanda-phet can you please make a decision on this?

**Comment by amanda-phet** [comment]
I think this one is ok to leave lowercase. I think it minimizes the weight of that function, which is desirable.
