### ISSUE TITLE
Consider using PropertyFractionNode (common) 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/function-builder#128]
Any sim that uses a fraction in a display might want to consider using (and modifying, if needed) the new fraction common code that was added due to https://github.com/phetsims/fractions-intro/issues/7 .

**Comment by pixelzoom** [comment]
I have investigated.  The advantage to doing this is almost negligible, and the amount of work is large.   Even if there were some a11y or PhET-iO advantage, those features should be addressed for equations _in general_, not just fractions. 

So I'm going to close this as "won't fix".  @amanda-phet feel free to reopen if you disagree.
