### ISSUE TITLE
Function machine shows multiple pieces when switching during fade

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/function-builder#130]
**Test device**
iPad
**Operating System**
iPadOS 13
**Browser**
Safari
**Problem description**
For ES6 Testing
When switching the function machine between number of pieces, there is a brief fading transition. During this, if you switch again it can show two or more settings at once.
**Steps to reproduce**
1. Go to the Mystery screen
2. Set the machine to have three steps
3. Quickly switch to and from the other settings, doing so before the transition finishes
4. Resetting does not solve, but moving slowly and going back to the first setting might.

**Visuals**
![funkycolors](https://user-images.githubusercontent.com/41024075/75579380-e83e3400-5a22-11ea-9dd8-ce941c62e04e.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: Function Builder
URL: http://phettest.colorado.edu/function-builder/function-builder_en.html?ea&brand=phet
Version: 1.2.0-dev.4 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Can't reproduce on published

**Comment by pixelzoom** [comment]
Unlikely that this is due to ES6 module migration.  More likely due to conversion from Tween to twixt in https://github.com/phetsims/twixt/issues/18.

**Comment by pixelzoom** [comment]
I had difficultly reproducing this, but I think I've resolved it in the above commit. 

@KatieWoe please verify in master. If it looks OK, you can close this issue.

**Comment by KatieWoe** [comment]
Looks good in master
