### ISSUE TITLE
Mac 10.10 erases images when black/white and negative filters are used

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/function-builder#132]
**Test device**
Dirac
**Operating System**
10.10.5
**Browser**
Safari 10.1.2
**Problem description**
Found during https://github.com/phetsims/chipper/issues/840, but reproduced and recorded on published version.
When an image goes through the function machine when it has the black/white or the negative rainbow filter it comes out blank instead. If you remove the filter and put it back on, sometimes the image comes back correctly. Checked on 10.11 and 10.12 on the same device and did not see this.
Assigning @ariel-phet since this is an existing issue on an older platform.
**Steps to reproduce**
1. Go to the first screen
2. Put the black/white or negative rainbow option in the function machine
3. Grab an object and put it through the machine

**Visuals**
https://drive.google.com/file/d/1Chv_8rqpZ1he6govCylnCpYHG0315VTQ/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Function Builder‬
URL: https://phet.colorado.edu/sims/html/function-builder/latest/function-builder_en.html
Version: 1.0.23 2020-04-07 10:33:32 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
Language: en-US
Window: 1276x663
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-10.0.35)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"9a0e2f3a","branch":"HEAD"},"babel":{"sha":"5befa799","branch":"master"},"brand":{"sha":"827202bf","branch":"HEAD"},"chipper":{"sha":"d2cc8b53","branch":"HEAD"},"dot":{"sha":"3628c3ae","branch":"HEAD"},"function-builder":{"sha":"422e7f6e","branch":"HEAD"},"joist":{"sha":"469cf96d","branch":"HEAD"},"kite":{"sha":"88f0c3a0","branch":"HEAD"},"phet-core":{"sha":"718ca784","branch":"HEAD"},"phetcommon":{"sha":"84d5c397","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"scenery":{"sha":"11ed5dad","branch":"HEAD"},"scenery-phet":{"sha":"512f6f77","branch":"HEAD"},"sherpa":{"sha":"03590a07","branch":"HEAD"},"sun":{"sha":"cccaf534","branch":"HEAD"},"tandem":{"sha":"a8ac284b","branch":"HEAD"},"twixt":{"sha":"53b31872","branch":"HEAD"}}

</details>

**Comment by pixelzoom** [comment]
I recommend checking on 10.13 and 10.14.  I confirmed that it does not occur on macOS 10.15.4.

The images on cards are rendered using the Canvas API.   The 2 functions that have been identified as problematic are Grayscale.js and InvertRGB.js.  They are the only 2 functions that edit the canvas data directly, while other functions perform transformations (scale, rotate,...) of the canvas image.  I can't think of another way to implement these functions.  And the bigger issue is that I don't have a macOS 10.10 development system.  So if we want to fix this, it will require relatively slow iteration.

**Comment by pixelzoom** [comment]
@KatieWoe can you please confirm that this is not an issue on 10.13.6 and 10.14.6 ?

**Comment by ariel-phet** [comment]
@KatieWoe  if you confirm that this is not an issue on 10.13.6 and 10.14.6 feel free to close. If it is an issue on those please reassign to me.

**Comment by KatieWoe** [comment]
Confirmed that they don't occur on 10.13 or 10.14

**Comment by pixelzoom** [comment]
@ariel-phet How wold you like to proceed now that @KatieWoe determined that it's not a problem on 10.13 or 10.14 ?

**Comment by ariel-phet** [comment]
Let's go ahead an close. not worth fixing such a platform specific bug currently when it can fixed with an OS upgrade.
