### ISSUE TITLE
Functions and cards can be dragged outside the bounds of the browser window

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#136]
@brooklynlash reported in Slack:
> Good afternoon, for Virtual Workshop I noticed that the objects in the Function Builder iframe can go out of the border, but then come back if you let go of the object. Katie said this is not an issue for the Virtual Workshop itself, but would this warrant an issue for the Function Builder sim?

**Comment by pixelzoom** [comment]
In general, there is no constraint on dragging unless something can become “lost” by dragging it outside the bounds.  Since the functions and cards in Function Builder animate back, there is no possibility of them becoming lost, so no need for drag constraints.  @KatieWoe FYI,  because it sounds like you may not be aware of this convention.

Let's also confirm with the designer @amanda-phet to be sure.  @amanda-phet are you OK with the behavior as is?

**Comment by amanda-phet** [comment]
Many sims have defined bounds of the play area, but when there are toolboxes or panels to bring things to a play area, we can see this kind of behavior. Least Squares Regression is a sim with the same type of behavior (try the data points). So this is certainly not unique to Function Builder, but is probably less common in our sims.
