### ISSUE TITLE
User request: composite functions

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/function-builder#138]
> Would there be any way to build 2 separate functions in which one function would feed into the other function?  I could use this to teach composite functions in Math 3.

**Comment by amanda-phet** [comment]
The sim currently supports this, since you can compose up to three functions. I might need clarification on what they are looking for, but I would respond with something along the lines of using the "see inside" checkbox to see between each function.

**Comment by pixelzoom** [comment]
@oliver-phet checking on the status of this issue. Have you responded to the user?

**Comment by oliver-phet** [comment]
Yes, I responded to the user on Jan 10. Haven't heard from the user since then so I'll close for now!
