### ISSUE TITLE
revise Warhol function

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#14]
There is confusion about what the Warhol function does, and what the result should be when applying it multiple times. This has come up multiple times, most recently reported by @oliver-phet. 

This implementation currently matches what was requested in the 9/9/15 design meeting. E.g.:

Applied once:

![screenshot_25](https://cloud.githubusercontent.com/assets/3046552/13856373/7d6f7666-ec3a-11e5-8beb-2bd80a0b9d11.png)

Applied twice:

![screenshot_26](https://cloud.githubusercontent.com/assets/3046552/13856381/837eebf4-ec3a-11e5-876a-4a4be2b715db.png)

Since @amanda-phet is on leave, assigning to @ariel-phet to decide how to resolve this.

**Comment by pixelzoom** [comment]
@oliver-phet supplied this URL that demonstrates a Warhol effect:
http://convertimage.net/online-photo-effects/make-an-online-andy-warhol-pop-art-effect.asp?i=20150328-021235-bxdlm

Also note that the "soup can" icon here is a little bit inappropriate. Warhol's famous artwork involving soup cans looked nothing like this effect.  His series on Marilyn Monroe used the effect that is similar to what is described in the design doc.

**Comment by oliver-phet** [comment]
Here is another editor that demonstrates the effect: http://www124.lunapic.com/editor/?action=warhol

Inputting this already "Warholed" image 
![unnamed](https://cloud.githubusercontent.com/assets/5090275/13856865/e8c14866-ec3c-11e5-8ab0-a8eb68ef968f.png)

results in something like this: 
<img width="621" alt="screen shot 2016-03-17 at 12 35 17 pm" src="https://cloud.githubusercontent.com/assets/5090275/13856854/d7ac4bde-ec3c-11e5-816f-a9a2cd37fc93.png">

**Comment by ariel-phet** [comment]
@pixelzoom you and I should talk next week (perhaps just on skype) and flesh out, I think I know how I want this to work, so lets come up with a solution that makes sense to both you and the potential user.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/function-builder/issues/20 (Meeting with Amanda 3/18/2016 notes), @ariel-phet said:

> • revisiting warhol function seems like a good idea (so double warhol gives something more expected)

**Comment by pixelzoom** [comment]
Discussed with @ariel-phet today via Skype, I'll try the different approach based on remapping colors.

**Comment by pixelzoom** [comment]
Revised the Warhol function using the approach described at http://chennanni.com/archives/1111.  The basics steps are:

1. Scale the image by 50%.
2. Convert the image to grayscale.
3. Use intensity of pixels in the grayscale image to map pixels to colors.
4. Draw the mapped image into 1 of the 4 quadrants.
5. Repeat steps 3 & 4 for each quadrant, using a different color mapping.

**Comment by pixelzoom** [comment]
Did a lot of work on this, which can be seen in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.18/function-builder_en.html

Here's what the first few cards look like for single and double Warhol:

![warhol](https://cloud.githubusercontent.com/assets/3046552/14437065/cd9c1882-ffdc-11e5-8af0-6bc64298fcbf.png)

Some notes:

(1) Warhol tends to look better/interesting in images that have variable contrast (e.g., photographs). The images in this sim suffer because they are (mostly) very simple, with little contrast.  Nothing I can do about that. And there's a good chance that the images will be revised to be even simpler (see #13).

(2) The result of applying Warhol twice suffers because our images are small.  I've made the images fill more of the cards. But we can't make the cards much larger without sacrificing space for the table and graph.  And we'd have to make the cards dramatically larger for it to really make a difference. 

(3) By default, the implementation converts all transparent pixels to opaque white, effectively putting the image on a background with bounds equal to the image (not the card).  Two issues: 
   (a) Processing the background is different than other image functions (eg 'invert RGB') which do not process the image's background. Will this be confusing?
   (b) If we do process the background, should the background be the same size as the card, versus the image bounds?  (Rathole alert: This gets problematic because the card has round corners and the pixel data is a rectangular block.)

(4) There are 4 different color maps, one for each of the 4 quadrants. Each map contains 4 colors. The grayscale intensity range is divided into 4 equal "bands", and a grayscale value is mapped to one of the 4 colors.  The colors can easily be changed, to tweak how the Warhol output looks.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet, let me know if/when you want further work on this.

**Comment by ariel-phet** [comment]
@pixelzoom no further work. I think this work fulfills the "vision" of the Warhol function. I am guessing if we do further work it will mainly involve:

a) revising the images a bit so that they all have consistent bounds
b) tweaking the color maps a bit (but from the code you showed me, that was a minor change as mentioned above)

Unassigning the issue for now, but leaving open

**Comment by pixelzoom** [comment]
Unlike other image processing functions in this sim, Warhol changes the transparent pixels in an image to opaque white (as requested by @ariel-phet).  Here's one scenario where that could be confusing, see screenshot below.  If there image was erased, then what is Warhol operating on? And why does each Warhol output have the same dimensions as original image?

In the current implementation, when an image is erased, it's canvas is erased, but its dimensions aren't changed.  And apparently erasing a canvas sets its contents to fully-transparent pixels, which will then be operated on by Warhol.  

Is this behavior acceptable? Should the Erase function do something else?

Assigning to @ariel-phet for comment. 

![screenshot_13](https://cloud.githubusercontent.com/assets/3046552/14687277/e756677c-06f9-11e6-8d12-a7eb50d60d99.png)

**Comment by pixelzoom** [comment]
I changed the Warhol function to first examine the input canvas. If the input is blank (all transparent pixels) then the Identity function is applied instead of the Warhol function.  Here's what it looks like in the scenario that was shown in the previous comment.  Better?

![screenshot_14](https://cloud.githubusercontent.com/assets/3046552/14688320/4593fb6a-06ff-11e6-844f-b4ad1b89776f.png)

**Comment by pixelzoom** [comment]
Changes for the above scenario:
https://github.com/phetsims/function-builder/commit/02f7447fe0a5f051e98f227793663db1597269cc
https://github.com/phetsims/function-builder/commit/45e49d66341370ae48acbb69fbce9eec62efc819

**Comment by ariel-phet** [comment]
@pixelzoom yes, I think that is better.

**Comment by pixelzoom** [comment]
Everyone seems to be satisfied with the current behavior. Closing.
