### ISSUE TITLE
Access of private attribute Carousel.items

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#152]
Discovered in https://github.com/phetsims/circuit-construction-kit-common/issues/630, several places in FunctionBuilder have code that accesses private instance variable `Carousel.items`.  For instance: SceneNode.js has this code around line 343:

```ts
this.functionCarousel.items.forEach( functionContainer => {
```

`Carousel.items` was marked as private in  https://github.com/phetsims/sun/commit/62874d6e04189060dd0bd99fd8f499887113dab1.  Should it be marked as public?  Or should function builder (and potentially other sims in the future) keep track of their own items?

**Comment by pixelzoom** [comment]
I see 8 occurrences:

<img width="482" alt="screenshot_2133" src="https://user-images.githubusercontent.com/3046552/211424692-c9afa94e-41d9-4f33-a735-cb65f27dd450.png">

**Comment by pixelzoom** [comment]
> `Carousel.items` was marked as private in https://github.com/phetsims/sun/commit/62874d6e04189060dd0bd99fd8f499887113dab1. Should it be marked as public?

`protected` seems reasonable.  I did not make that change because Carousel is undergoing changes in another issue.

> Or should function builder (and potentially other sims in the future) keep track of their own items?

Function Builder was already keeping track of its "containers" (the items in the Carousels) so it was trivial to adjust.

Back to @samreid.

**Comment by samreid** [comment]
Looks good, thanks!  Closing.
