### ISSUE TITLE
Meeting with Amanda 3/18/2016 notes 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/function-builder#20]
- Amanda approves of "mole under carpet" look (this transparency effect works nicely)
- Also likes the dragging solution for cards following an invisible line
- "See Inside" the cut-out works well, no "window" needed, but might be good to have the interior look the interior of the tube instead of just black. Worth trying, but black might look best, look like inside the most. Perhaps try the look given for the interior in mockups.
- Amanda also fine with fleshing out the functionality before changing artwork (but fine with changing artwork)
- revisiting warhol function seems like a good idea (so double warhol gives something more expected)

**Comment by pixelzoom** [comment]
Re: 
> revisiting warhol function seems like a good idea (so double warhol gives something more expected)

I've moved this comment to the relevant issue (#14).

Re:
> "See Inside" the cut-out works well, no "window" needed, but might be good to have the interior look the interior of the tube instead of just black. Worth trying, but black might look best, look like inside the most. Perhaps try the look given for the interior in mockups.

I tried the interior color shown in the mockup, it didn't look good.  After experimenting with several other options, black looked best.  If you want to see any of these options, please create an issue and specify what colors you'd like, and I'll create a dev version for each color.

All other notes in https://github.com/phetsims/function-builder/issues/20#issue-141995480 indicate approval, so require no action.

Back to @ariel-phet, feel free to create specific issues if there's anything else here to address, then close this issue.

**Comment by ariel-phet** [comment]
@pixelzoom I think black works fine for now and the near future, we can always revisit later (seems like an easy change comparatively). Closing
