### ISSUE TITLE
Numbers screen has no non-invertible functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#21]
While implementing the Numbers screen, I noticed that there are no non-invertible functions specified in the design document for this screen.  It seems odd to introduce the concept of non-invertibility in the Patterns screen with images, then not reinforce it in the Number screen with numbers, then bring it back in the Equations screen (where it will be mixed in with more difficult material).  

Consider adding '× 0' to the Numbers screen to serve that purpose.

**Comment by ariel-phet** [comment]
@pixelzoom which of the proposed functions would you propose replacing... and would you propose having it be a "mystery" function or an explicit function (like +3)

**Comment by pixelzoom** [comment]
I think an explicit function might be best, so we're not combining "guess the function" with non-invertible functions.  

I don't know which of the functions would be best to replace.  But it seems like there are a disproportionate number of "mystery" functions (6 of 9).   And as I'm playing with the sim, they seem difficult to guess - might be good to vet these mystery functions to make sure they aren't too difficult for the target audience. 

If you want to play with the functions, you can pull master.  Most of the basic functionality in the Numbers screen is working.

**Comment by pixelzoom** [comment]
Also consider the possibility of adding an addition 3 functions (including 'x 0').  The Patterns screen has 12 functions, the Numbers screen currently has 9.

**Comment by pixelzoom** [comment]
Rather than replacing a function, consider the possibility of adding an additional 3 functions (including 'x 0').  The Patterns screen has 12 functions, the Numbers screen currently has 9.  Adding additional functions might also help to address the disproportionate number of "mystery" functions.

**Comment by ariel-phet** [comment]
@amanda-phet mentioning you in case you have time to weigh in.

**Comment by pixelzoom** [comment]
Here's a dev version that included basic work on the Numbers screen. This should give you a feel for the current set of functions and inputs.

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.14/function-builder_en.html

**Comment by ariel-phet** [comment]
Discussed over skype 4/5/2016, @pixelzoom will add another page to the carousel.

**Comment by pixelzoom** [comment]
In addition to 'x 0', I'll add 2 other concrete (non-mystery) functions.  Note that functions can be easily changed later, as long as we stick to plus/minus/times/divide operators.

**Comment by pixelzoom** [comment]
I added 2 pages, for a total of 5 pages.

The first 3 pages contain 2 concrete example and 1 mystery for each operator, and includes the non-invertible 'x 0':

![screenshot_34](https://cloud.githubusercontent.com/assets/3046552/14302017/aea6c9ae-fb59-11e5-89ca-49fbe87c2960.png)
![screenshot_35](https://cloud.githubusercontent.com/assets/3046552/14302019/b200ae62-fb59-11e5-9dfd-f3360e6d7d55.png)
![screenshot_36](https://cloud.githubusercontent.com/assets/3046552/14302021/b735e7e4-fb59-11e5-89e5-d42d3e64cfd0.png)

The 4th page is similar, but with double functions:

![screenshot_37](https://cloud.githubusercontent.com/assets/3046552/14302028/d8eb5fe0-fb59-11e5-8bcd-233d79c84ee2.png)

The 5th page is functions where both the operator and number are a mystery:

![screenshot_38](https://cloud.githubusercontent.com/assets/3046552/14302030/dd59a686-fb59-11e5-9a30-6654e3b7748f.png)

As I mentioned above... All of this is easy to change. This gives me something more substantial to test with.

**Comment by pixelzoom** [comment]
Demonstrated in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.17/function-builder_en.html

Back to @ariel-phet.  Feel free to close after reviewing, and we can refine the functions later.

**Comment by ariel-phet** [comment]
Looks good, closing
