### ISSUE TITLE
Equations screen: range of input cards results in empty position in carousel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#22]
For the Equations screen, the design document indicates that the input carousel contains cards in the range [-4,6] and shows 4 items per page:

![screenshot_31](https://cloud.githubusercontent.com/assets/3046552/13974953/3de7a578-f076-11e5-817a-5ffe0375197f.png)

With those requirements, both the input and output carousels will have an empty position at the upper end of the range:

![screenshot_32](https://cloud.githubusercontent.com/assets/3046552/13974956/4e221a86-f076-11e5-8d52-f37fe8a3d84e.png)

Is this empty position acceptable? I think it could be confusing.

Note that increasing this range is likely to cause problems with exceeding the range of the graph.

Also note that the range in the Numbers screen is [-4,7].

**Comment by ariel-phet** [comment]
@pixelzoom I don't disagree it has potential to be a tad confusing, but at the same time, especially with the drag interaction you have programmed, there is no possibility to fill that empty slot through dragging cards or such correct?

There does not seem to be a good alternative. Shrinking the carousel to only three slots in that case seems like it would be confusing as well (and from my understanding would be programmatically highly undesirable to implement)  

I would say the empty position is acceptable, we can see if it cause issue in interviews. We might be able to come up with a visual that suggests "intentionally left blank" Perhaps that slot could be greyed out or such?

**Comment by pixelzoom** [comment]
> Shrinking the carousel to only three slots in that case seems like it would be confusing as well (and from my understanding would be programmatically highly undesirable to implement)

Changing the number of items per pages for a carousel is actually trivial, just set `options.itemsPerPage:3`. But I don't recommend it in this case -- I think it's important to have the same `itemsPerPage` on all screens.

**Comment by pixelzoom** [comment]
... so let's roll with it as is for now, and revisit when the sim is more fleshed out.

**Comment by pixelzoom** [comment]
It turns out that this is not an issue.  The range is [-4,6], followed by 'x'.  So there are in fact no empty positions in the carousel.  

Closing.
