### ISSUE TITLE
Simplify equations

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#26]
One of the requested features for one of the math screens is the ability to simplify equations.  I saw this 3rd party library today which has the capability to do symbolic equation simplification in JS.  It is likely to be too heavy-handed a solution for this problem, like using a sledgehammer to squash an ant, but thought I'd point it out in case it is useful:
https://github.com/davidedc/Algebrite

**Comment by pixelzoom** [comment]
Thanks, I'll have a look when I get around to implementing that feature.

**Comment by pixelzoom** [comment]
Algerije is not going to be useful for this sim.  "Unsimplified" form is going to be very PhET specific, and "simplified" form is going to be slope-intercept form.  See specification and examples in https://github.com/phetsims/function-builder/blob/master/doc/equation-formats.md.
