### ISSUE TITLE
function icons contain English text

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#27]
Some of the icons provided for the "mystery" functions currently contain English text ('A', 'B', 'C').

Patterns screen:

![screenshot_10](https://cloud.githubusercontent.com/assets/3046552/14620721/90cc572e-057b-11e6-8096-d522d1cf5569.png)

Equations screen:

![screenshot_09](https://cloud.githubusercontent.com/assets/3046552/14620701/729be1ca-057b-11e6-96c7-04b419ce5e88.png)

Options:

(1) Make the text translatable. Requires 2-3 hours of reworking code that currently expects an image file.
(2) Design an icon for these functions that doesn't require text.  No code changes required, design work needed.

**Comment by ariel-phet** [comment]
@pixelzoom my instinct would be to make the text translatable. Normally I would be in favor of an icon, but this is supposed to be scaffolding up to thinking about functions in an algebraic sense where variables are used to represent them ( like "f(x)" for instance )

Assigning to @amanda-phet to see if she has any thoughts.

**Comment by pixelzoom** [comment]
This was completed awhile ago. Closing.
