### ISSUE TITLE
[iOS] x & y don't render on mobile Safari

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#28]
Noted in 1.0.0-dev.26 and master.
See https://github.com/phetsims/scenery/issues/545, where this general issue is being tracked.

**Comment by ariel-phet** [comment]
Fortunately, we do have a fall back solution of using the times new roman text instead of unicode, so certainly not a "show stopper"

**Comment by pixelzoom** [comment]
Yes, that workaround is mentioned in phetsims/scenery#545:
> We could workaround by using a web-safe italic serif font,

**Comment by pixelzoom** [comment]
Resolved in https://github.com/phetsims/scenery/issues/545#issuecomment-220116510, closing.
