### ISSUE TITLE
image layout problem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#3]
(This issue was being discussed with @jonathanolson via email, but that didn't seem to be an effective medium for quick turnaround. So converting it to a GitHub issue.)

On 10/5/15 I wrote in email:

I’m testing function-builder.Grayscale (grayscale function) and I’m seeing a browser difference that I didn’t anticipate. 

With this input card:

![screenshot_17](https://cloud.githubusercontent.com/assets/3046552/10402966/acb3abb4-6e85-11e5-9b8d-0ada8c30b171.png)

Chrome looks great:

![screenshot_18](https://cloud.githubusercontent.com/assets/3046552/10402955/9f7ce73a-6e85-11e5-8159-a0856bbf3c32.png)

But in Firefox and Safari, the image isn’t centered.

![screenshot_19](https://cloud.githubusercontent.com/assets/3046552/10402960/a58ec01c-6e85-11e5-95f4-a8a1d7114091.png)

This test lives in function-builder.SingleSceneNode, line 145. 
You can see it on the “Patterns” screen. 
Results below were all on Mac OS X 10.10.5.

Any ideas?

**Comment by pixelzoom** [comment]
Making this change in Grayscale.js fixes the problem:

```
- context.putImageData( imageData, 0, 0 );
+ context.putImageData( imageData, 0, 0, 0, 0, canvas.width, canvas.height );
```

I guess those “optional” args aren’t really optional for some browsers.

**Comment by pixelzoom** [comment]
On 10/5/15, @jonathanolson wrote in email:

> One complication could be running on retina devices. the putImageData/etc. deal with the "big" pixels, which may have subpixels. Canvas in Safari would actually have 4x the number of pixels actually rendered, which may be throwing off browsers here. See https://github.com/phoboslab/Ejecta/issues/4. Let me know if you want to collaborate to nail down this issue.

**Comment by pixelzoom** [comment]
Hmmm…. The “fix” I noted is sporadic.  Or maybe isn’t doing anything at all.

Yes, I guess I’ll need some assistance debugging at some point. Thanks for the offer.

**Comment by pixelzoom** [comment]
Is there something in my implementation that is async? That would explain why the position of the images is off.

This perhaps?

`outputImage.src = canvas.toDataURL();`

**Comment by pixelzoom** [comment]
From scenery.Image doc:

```js
/*
* Canvas renderer supports the following as 'image':
*     URL (string)             // works, but does NOT support bounds-based parameter object keys like 'left', 'centerX', etc.
*                                    // also necessary to force updateScene() after it has loaded
*     HTMLImageElement         // works
```

I’m passing in an HTMLImageElement, but it’s src is a URL.  Does that have the same problems as if I pass the URL directly to Image?

**Comment by pixelzoom** [comment]
On 10/7/15 @jonathanolson wrote via email:

Since the plan was to only use Canvases from the initial require()'d image up until the final displayed output, not using images in-between, e.g. context.drawImage( canvas ), I imagine the async part would only cause layout issues for the final displayed Scenery Images, since browsers can't guarantee a synchronous width and height.

Instead of creating an HTMLImageElement (and then presumably the Scenery image to display it), you can just pass the URL to the Scenery Image itself.

Drawing a Canvas into another Canvas and then inspecting pixels/setting pixels should be 100% synchronous. Can you verify that is the used approach for computing card graphics?

**Comment by pixelzoom** [comment]
> Instead of creating an HTMLImageElement (and then presumably the Scenery image to display it), you can just pass the URL to the Scenery Image itself.

I’m confused. The doc for scenery.Image says that passing a URL to Image "works, but does NOT support bounds-based parameter object keys like 'left', 'centerX', etc. also necessary to force updateScene() after it has loaded”.  Since I need to center the Image on a card, how will this not be a problem?  And please clarify about updateScene, does the client need to make an explicit call?  I don’t see anything in Image that handles it.

> Drawing a Canvas into another Canvas and then inspecting pixels/setting pixels should be 100% synchronous. Can you verify that is the used approach for computing card graphics?

Yes, see for example function-builder.Grayscale, where you and I fleshed out the approach together via Skype.

**Comment by pixelzoom** [comment]
You can also see the problem occurring in the "Test" screen of function-builder (master) or in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.1/function-builder_en.html

**Comment by jonathanolson** [comment]
>> Since the plan was to only use Canvases from the initial require()'d image up until the final displayed output, not using images in-between

>> Drawing a Canvas into another Canvas and then inspecting pixels/setting pixels should be 100% synchronous. Can you verify that is the used approach for computing card graphics?

> Yes, see for example function-builder.Grayscale, where you and I fleshed out the approach together via Skype.

On line 52 of Grayscale, an HTMLImageElement (the input Card's image) is being drawn into the Canvas. I mean a Canvas being drawn into a Canvas. So for example, if we have currently:
```js
var snowflakeImage = require( 'image!FUNCTION_BUILDER/inputs/snowflake.png' ); // HTMLImageElement
var card0 = new Card( 'snowflake', snowflakeImage );

// make it grayscale
var canvas1 = ..., context1 = ...
context1.drawImage( canvas1, ... );
// ... and whatnot to get the transformed image
var image1 = ... // HTMLImageElement
image1.src = canvas1.toDataURL();
var card1 = new Card( 'name', image1 );

// ... repeat with FBFunctions ...

// CardNode:
new Image( card.image, ... );
```

I would recommend passing the Canvas through the Cards directly:
```js
var snowflakeImage = require( 'image!FUNCTION_BUILDER/inputs/snowflake.png' ); // HTMLImageElement
var snowflakeCanvas = ..., snowflakeContext = ...
snowflakeContext.drawImage( snowflakeImage, ... );
var card0 = new Card( 'snowflake', snowflakeCanvas );

// make it grayscale
var canvas1 = ..., context1 = ...
context1.drawImage( card0.canvas );
// ... and whatnot to get the transformed image
var card1 = new Card( 'name', canvas1 );

// ... repeat with FBFunctions ...

// CardNode:
new Image( card.canvas, ... );
// OR
new Image( card.canvas.toDataURL(), ... );
```

Also you can use initialWidth/initialHeight when creating a Scenery Image node.

Updated Image constructor docs:
```js
  /*
   * Constructs an Image node from a particular source.
   * @public
   *
   * We support a few different 'image' parameter types:
   *
   * HTMLImageElement - A normal HTML <img>. If it hasn't been fully loaded yet, Scenery will take care of adding a
   *   listener that will update Scenery with its width/height (and load its data) when the image is fully loaded. NOTE
   *   that if you just created the <img>, it probably isn't loaded yet, particularly in Safari. If the Image node is
   *   constructed with an <img> that hasn't fully loaded, it will have a width and height of 0, which may cause issues
   *   if you are using bounds for layout. Please see initialWidth/initialHeight notes below.
   *
   * URL - Provide a {string}, and Scenery will assume it is a URL. This can be a normal URL, or a data URI, both will
   *   work. Please note that this has the same loading-order issues as using HTMLImageElement, but that it's almost
   *   always guaranteed to not have a width/height when you create the Image node. Note that data URI support for
   *   formats depends on the browser - only JPEG and PNG are supported broadly. Please see initialWidth/initialHeight
   *   notes below.
   *
   * HTMLCanvasElement - It's possible to pass an HTML5 Canvas directly into the Image node. It will immediately be
   *   aware of the width/height (bounds) of the Canvas, but NOTE that the Image node will not listen to Canvas size
   *   changes. It is assumed that after you pass in a Canvas to an Image node that it will not be modified further.
   *   Additionally, the Image node will only be rendered using Canvas or WebGL if a Canvas is used as input.
   *
   * Mipmap data structure - Image supports a mipmap data structure that provides rasterized mipmap levels. The 'top'
   *   level (level 0) is the entire full-size image, and every other level is twice as small in every direction
   *   (~1/4 the pixels), rounding dimensions up. This is useful for browsers that display the image badly if the
   *   image is too large. Instead, Scenery will dynamically pick the most appropriate size of the image to use,
   *   which improves the image appearance.
   *   The passed in 'image' should be an Array of mipmap objects of the format:
   *   {
   *     img: {HTMLImageElement}, // preferably preloaded, but it isn't required
   *     url: {string}, // URL (usually a data URL) for the image level
   *     width: {number}, // width of the mipmap level, in pixels
   *     height: {number} // height of the mipmap level, in pixels
   *   }
   *   At least one level is required (level 0), and each mipmap level corresponds to the index in the array, e.g.:
   *   [
   *     level 0 (full size, e.g. 100x64)
   *     level 1 (half size, e.g. 50x32)
   *     level 2 (quarter size, e.g. 25x16)
   *     level 3 (eighth size, e.g. 13x8 - note the rounding up)
   *     ...
   *     level N (single pixel, e.g. 1x1 - this is the smallest level permitted, and there should only be one)
   *   ]
   *
   * -----------------
   *
   * Image also supports the following options beyond what Node itself provides:
   *
   * image - {see above} Allows changing the underlying input image to a Scenery Image node. Note that if for some
   *    reason the provided image was mutated somehow, it's recommended to call invalidateImage() instead of changing
   *    the image reference.
   *
   * initialWidth - {number} If the input image hasn't loaded yet, but the (expected) size is known, providing an
   *    initialWidth will cause the Image node to have the correct bounds (width) before the pixel data has been fully
   *    loaded. A value of 0 will be ignored.
   *
   * initialHeight - {number} If the input image hasn't loaded yet, but the (expected) size is known, providing an
   *    initialHeight will cause the Image node to have the correct bounds (height) before the pixel data has been fully
   *    loaded. A value of 0 will be ignored.
   *
   * mipmap - {boolean} Whether mipmaps are supported. Defaults to false, but is automatically set to true when a mipmap
   *    image is provided to it. Setting it to true on non-mipmap images will trigger creation of a medium-quality
   *    mipmap that will be used. NOTE that this mipmap generation is slow and CPU-intensive. Providing precomputed
   *    mipmap resources to an Image node will be much faster, and of higher quality.
   *
   * mipmapBias - {number} Allows adjustment of how much level-of-detail is displayed. Increasing it will typically
   *    decrease the displayed resolution, and decreases (going negative) will increase the displayed resolution, such
   *    that approximately:
   *        mipmapLevel = Math.round( computedMipmapLevel + mipmapBias )
   *
   * mipmapInitialLevel - {number} If relying on Scenery to generate the mipmaps (mipmap:true on a non-mipmap input),
   *    this will be the number of initial levels to compute.
   *
   * mipmapMaxLevel - {number} If relying on Scenery to generate the mipmaps (mipmap:true on a non-mipmap input),
   *    this will be the maximum (smallest) level that Scenery will compute.
   *
   * @param {see above} image
   * @param {Object} [options]
   */
```

**Comment by pixelzoom** [comment]
The issue with image layout is resolved after switching to a canvas-to-canvas rendering approach, and using the `new Image(canvas)` form of the scenery.Image constructor.  

The quality of the rendering is inferior on Mac+Chrome, but that issues is tracked in https://github.com/phetsims/function-builder/issues/4.

Closing.
