### ISSUE TITLE
[Edge] The "Artifact" Problem

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#30]
@pixelzoom Edge only problem seen during phetsims/tasks/issues/589.

So this sim doesn't like Edge very much. There are consistent, what I will call, "artifacts" left behind after an object translation. There is not an explicit way of reproducing this, it all just sort of happens (with maybe an 80% occurrence rate). **Ignore the poor performance in each video!** Strap in:

1. An artifact is left behind after grabbing a function from its carousel (in the below video only one should be allowed but a second is shown):
![funbu01](https://cloud.githubusercontent.com/assets/5863899/15188468/25e6a834-1763-11e6-83d6-c438e393057e.gif)

2. When returning functions to their carousel, the below happens. Scrolling the function carousel shows the artifact staying in place:
![funbu02](https://cloud.githubusercontent.com/assets/5863899/15188471/2ace3344-1763-11e6-92f9-10446ad84e03.gif)

3. Cards in the output carousel leave an artifact behind after a Reset All, Erase, or being dragged out by a user. Also in the video, similar to number 1, a function can leave an artifact behind after being grabbed from the function machine:
![funbu03](https://cloud.githubusercontent.com/assets/5863899/15188473/2f05b162-1763-11e6-917c-4a5f47c1b2aa.gif)

4. Visually similar to number 2, this can happen when placing a function into a slot:
![funbu04](https://cloud.githubusercontent.com/assets/5863899/15188478/330116a8-1763-11e6-8722-e5d755717552.gif)

5. An artifact is more than likely left behind after using the second card of an input, hence why the ghost state of the input has an obscured dashed outline:
![funbu05](https://cloud.githubusercontent.com/assets/5863899/15188481/388c138e-1763-11e6-829b-a5cc1d70cbf6.gif)

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.25/function-builder_en.html
Version: 1.0.0-dev.25 2016-05-05 18:36:48 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1600x746
Pixel Ratio: 1/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"b461c809","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"184674ba","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"function-builder":{"sha":"3d4fe673","branch":"master"},"joist":{"sha":"48836bcf","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"7590be09","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"9f2d40d5","branch":"master"},"tandem":{"sha":"5af5b8f8","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
To clarify what @phet-steele is calling an "artifact"... It's a lot more than an artifact - the entire function or card continues to be drawn where it previously was.

When a function moves between the carousel, to dragging, to the builder, it is reparented.  Similarly, a card is reparented when it moves between carousels and being dragged.  What appears to be happing is that, when reparented, a function or card is not erased from the location that it previously occupied. 

Video 5 appears to be a different problem. Rather than a complete card appearing where it should not, it shows a solid line (rather than a dashed line) around a "ghost" card. I suspect that this may be an issue with dashed lines.

Since all of this works fine on other platforms, I have to conclude that these are scenery issues with Edge support. I have no idea how to proceed with addressing these issues, and they are showstoppers for this sim.  Assigning to @jonathanolson with high priority. @ariel-phet please prioritize.

**Comment by pixelzoom** [comment]
No idea how to address this, likely a problem with Edge support in scenery. This would be a showstopper for publication.

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/function-builder/issues/30#issuecomment-218518690, I said:
> Video 5 appears to be a different problem. Rather than a complete card appearing where it should not, it shows a solid line (rather than a dashed line) around a "ghost" card. I suspect that this may be an issue with dashed lines.

But based on https://github.com/phetsims/function-builder/issues/31, it's possible that an entire card is still in the carousel, and that it's opacity is messed up.

**Comment by pixelzoom** [comment]
Mentioning @jonathanolson, since he will undoubtedly be involved in addressing this.

**Comment by pixelzoom** [comment]
At 5/12/16 dev meeting, @ariel-phet said that iOS issues are higher priority than Edge issues, so lowering the priority of this from "top" to "high".

**Comment by jonathanolson** [comment]
@phet-steele, can you confirm that this is fixed in master?

**Comment by pixelzoom** [comment]
@jonathanolson I don't see any commits? Did you fix something in scenery?

**Comment by jonathanolson** [comment]
Fixed in Scenery with commit https://github.com/phetsims/scenery/commit/46873398597e6012781ed01c85ca395d86b34644 in linked issue https://github.com/phetsims/scenery/issues/546.

**Comment by phet-steele** [comment]
@jonathanolson @pixelzoom Numbers 1-4 are fixed, 5 is still present.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery/issues/546#issuecomment-223200907, @jonathanolson indicated that number 5 is different than 1-4:

> Will handle the number-5 case in that issue separately, as it appears to be a separate bug, and may be fixed by the Canvas work that is in progress.

So I've factored number 5 out into a separate issue, #56.

Closing this issue since numbers 1-4 have been fixed.
