### ISSUE TITLE
[Edge] Card ghosting

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#31]
@pixelzoom Edge only problem seen during phetsims/tasks/issues/589.

The cards in the input carousel are in their apparent ghost state (the state normally seen after two cards of a single kind have been used) immediately upon sim load. It does not matter if both cards have been used or not at this point, they will always look grayed.

Edge:
![edgein](https://cloud.githubusercontent.com/assets/5863899/15188717/6852c0da-1764-11e6-9c07-1b3b795644ab.PNG)

Chrome:
![chromein](https://cloud.githubusercontent.com/assets/5863899/15188723/70cde442-1764-11e6-8409-128f8ef86b57.PNG)

Similarly, the second card of a kind that makes its way to the output carousel will do something similar to graying. Maybe hard to see, but the first butterfly gets dimmer when the second moves over it:

![funbu06](https://cloud.githubusercontent.com/assets/5863899/15188917/666b82c4-1765-11e6-8abd-bba082929d69.gif)

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.25/function-builder_en.html
Version: 1.0.0-dev.25 2016-05-05 18:36:48 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1600x746
Pixel Ratio: 1/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"b461c809","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"184674ba","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"function-builder":{"sha":"3d4fe673","branch":"master"},"joist":{"sha":"48836bcf","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"7590be09","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"9f2d40d5","branch":"master"},"tandem":{"sha":"5af5b8f8","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
No idea how to address this, likely a problem with Edge support in scenery.  This would be a showstopper for publication.

Assigning to @ariel-phet to prioritize and assign.

**Comment by pixelzoom** [comment]
Mentioning @jonathanolson, since he will undoubtedly be involved in addressing this.

**Comment by pixelzoom** [comment]
At 5/12/16 dev meeting, @ariel-phet said that iOS issues are higher priority than Edge issues, so lowering the priority of this from "top" to "high".

**Comment by pixelzoom** [comment]
@jonathanolson status?

**Comment by jonathanolson** [comment]
Should be fixed by https://github.com/phetsims/scenery/issues/518, which is at the top of my list (and I'm working on it).

**Comment by pixelzoom** [comment]
In Skype, @jonathanolson said:

[6/6/16, 9:10:43 PM] Jonathan Olson: The backup would presumably be to try SVG out on Edge
[6/6/16, 9:10:57 PM] Jonathan Olson: That's one thing we could try now (see how ?rootRenderer=svg works on Edge)

**Comment by jonathanolson** [comment]
Latest Scenery commit (https://github.com/phetsims/scenery/commit/768bf4537826a6bbda1ad6fc548883bc8b905179) appears to fix this. @phet-steele, can you verify?

**Comment by phet-steele** [comment]
@jonathanolson verified fixed on the original device.

**Comment by pixelzoom** [comment]
I don't have an Edge test platform, and don't have time to set one up.  So I'll take @phet-steele's word for it and close this issue.
