### ISSUE TITLE
[iOS] edges of "drawers" are clipped

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#33]
Drawers open and close by using a clipArea.  On iOS, it looks like the edges of the drawers are being clipped.

Example on iOS 9.3.1 with mobile Safari, notice how the left edge of the "graph" drawer is missing:

![img_0079](https://cloud.githubusercontent.com/assets/3046552/15190860/53c613c8-176f-11e6-9162-873b43621dee.PNG)

Here's a desktop Chrome screenshot, showing what it's supposed to look like:

![screenshot_29](https://cloud.githubusercontent.com/assets/3046552/15190907/905d1ce6-176f-11e6-86cc-a1ea25e4592d.png)

**Comment by pixelzoom** [comment]
Here's the relevant code in function-builder.Drawer:

```js
    // put all of the moving pieces together
    var drawerNode = new Node( {
      children: [ handleNode, backgroundNode, contentsNode, borderNode ]
    } );

    // wrap the drawer with a clipping area, to show/hide the container
    assert && assert( !options.children, 'decoration not supported' );
    options.children = [ drawerNode ];
    options.clipArea = Shape.rect( 0, 0, drawerNode.width, drawerNode.height );
    Node.call( this, options );
```

So two possibilities:

(1) `drawNode.width` is inaccurate, not taking lineWidth into account.
(2) clipArea feature is inaccurate on iOS.

If `drawNode.width` is inaccurate, then it should be possible to workaround by increasing the width of the clipArea, like this:

```options.clipArea = Shape.rect( -10, 0, drawerNode.width + 20, drawerNode.height );```

But that resulted in no change, the left edge of the "graph" drawer is still clipped.

@jonathanolson Do you have any suggestions or insights?

**Comment by pixelzoom** [comment]
This is not a showstopper, it just looks lousy.

**Comment by pixelzoom** [comment]
@ariel-phet Could you please assign a priority to this issue?

**Comment by pixelzoom** [comment]
@jonathanolson Asking again: Do you have any suggestions or insights?

**Comment by jonathanolson** [comment]
Try:
```js
options.clipArea = Shape.bounds( drawerNode.bounds );
```
since the drawerNode's minX is -0.5.

Right now, the left-most 0.5 pixels of the drawerNode is getting clipped, and browsers might do clipping/antialiasing/etc. slightly differently, resulting in our iOS problem.

**Comment by pixelzoom** [comment]
@phet-steele I unfortunately don't have an iPad with me today. Could you verify whether this issue is fixed in this dev version? Thanks.
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.43/function-builder_en.html

**Comment by phet-steele** [comment]
This is what it looks like good sir:

![img_0043](https://cloud.githubusercontent.com/assets/5863899/15830291/b1792536-2bd4-11e6-8740-9ca44db8581a.PNG)

**Comment by pixelzoom** [comment]
Great, problem solved, closing.
