### ISSUE TITLE
reduce startup time

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#37]
With master @791533fe7965fb124939f03247911fdf027be1bf in requirejs mode ...

On Mac OS X 10.11.4 + Safari, startup is ~6 seconds.
On iPad2 + iOS 9.3.1, startup is ~15 seconds.  
And that will only get worse when the Mystery screen is fleshed out.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to specify what acceptable startup time (ballpark, desktop and mobile) is for this sim.

**Comment by ariel-phet** [comment]
@pixelzoom it seems most of our larger sims (ESPB, FAMB, Graphing Lines) are loading up in 7-8 seconds on iPad2 + iOS 9.3.1

I would say under 10 seconds would be ideal for the built sim. But a longer load up time will no necessarily be a show stopper.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/function-builder/commit/48a62e12d5f430dce59b7ea0e7aae66e3e3831c6, I added query parameter `initOnDemand`, which initializes a screen only when you click on its icon on the home screen or navigation bar.  This spreads out the cost of initialization. The disadvantage is that the first time you visit a screen, it takes a bit longer than subsequent times.

**Comment by pixelzoom** [comment]
Note to self: Look for redundant work that may be occurring at startup.

I verified that there are no Movable locations that are changing during startup.

**Comment by pixelzoom** [comment]
Here's a comparison of initialization options.

Initialize on startup:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.42/function-builder_en.html

Initialize on demand:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.42/function-builder_en.html?initOnDemand

Comparing on iPad2 (which is where the performance issue is most acute)... The "on startup" option takes ~12 seconds to display the home screen.  The "on demand" option is much faster, home screen is visible almost instantly.  But clicking on the Patterns screen icon (the worst case) results in ~6 seconds before that screen becomes visible.  That delay feels too long, may give the user the impression that something is broken.

I'll leave this option in the code for now.  But I'll start looking for anything "big and unnecessary" that's being done during initialization.

**Comment by pixelzoom** [comment]
On the Patterns screen, there are 24 input cards of type `ImageNode`.  But I see `ImageCardNode.updateContent` being called 48 times at start up.  So there's a redundant (and expensive) call here.

**Comment by pixelzoom** [comment]
I was mistaken -- there are 48 input cards in the Patterns screen, 24 for each of the 2 "scenes".

**Comment by pixelzoom** [comment]
So it looks like the Patterns screen takes longer to load that the other because there are many more cards and functions, not because there's anything significantly more expensive about the type of cards and functions.

**Comment by pixelzoom** [comment]
I added some coarse timing output to `Screen.initializeModelAndView` so that I could see where the startup time is going.  Here's the revised `initializeModelAndView`

```js
    // Initialize both the model and view
    initializeModelAndView: function() {
      var beforeModel = new Date().getTime();
      this.initializeModel();
      var beforeView = new Date().getTime();
      this.initializeView();
      var afterView = new Date().getTime();
      console.log( this.name + ': model=' + ( beforeView - beforeModel ) + ', view=' + ( afterView - beforeView ) + ', total=' + ( afterView - beforeModel ) );
    }
```

Here's the output, all times are in milliseconds, `null` is the home screen, Mystery screen hasn't been implemented yet.

```
null: model=0, view=183, total=183
‪Patterns‬: model=9, view=2077, total=2086
Numbers‬: model=19, view=1118, total=1137
Equations‬: model=2, view=1158, total=1160
Mystery‬: model=0, view=2, total=2
```

**Comment by pixelzoom** [comment]
I've been unable to find any "significant and unnecessary" work that's being done at startup time.  So it looks like we may need to choose between the 2 options described in https://github.com/phetsims/function-builder/issues/37#issuecomment-223441991.  @amanda-phet which option do you want to go with?

**Comment by amanda-phet** [comment]
On my macbook pro, using my home wifi, the differences are minor, but I think I prefer when the sim initializes on startup. 

However, after reading your assessment of the performance on the iPad2, I think we should go with initializing on demand. It's very easy to get impatient on a tablet, so while there is still a wait-time, it is much shorter. 12s is a very long time.

**Comment by pixelzoom** [comment]
When we add the Mystery screen, startup time is likely to increase by an additional 3-6 seconds.

**Comment by amanda-phet** [comment]
Is that on top of initializing on demand?

**Comment by pixelzoom** [comment]
No, that's the initialization time for the Mystery screen.  We'll pay that price either at startup, or on demand.  If we decide to go with "on demand", then the startup time for the Mystery screen be similar to what it is now (details in https://github.com/phetsims/function-builder/issues/37#issuecomment-223777555).

**Comment by pixelzoom** [comment]
Query parameters related to initialization have been revised.  In anticipation of the Mystery screen, you can now specify when to initialize ScreenViews and Scenes.

`initScreenViews`: when to initialize screen views: 'onDemand' or 'onStart' (default)
`initScenes`: when to initialize scenes: 'onDemand' or 'onStart' (default)

**Comment by pixelzoom** [comment]
This dev version has most of the Mystery screen fleshed out, and is indicative of the initialization time required for that screen:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.57/function-builder_en.html

**Comment by pixelzoom** [comment]
6/16/16 design meeting:

Leaning towards paying the full price of initialization on startup.  Measure times (similar to https://github.com/phetsims/function-builder/issues/37#issuecomment-223777555) for all 4 screens, so that we can evaluate.

**Comment by pixelzoom** [comment]
6/23/16 design meeting:  Decided to pay the full price of initialization on startup.  I'll profile the sim on desktop on iPad2, as I did in https://github.com/phetsims/function-builder/issues/37#issuecomment-223777555, so that we have a clear picture of what the Mystery screen has added.

**Comment by pixelzoom** [comment]
Profiling with:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.66/function-builder_en.html

All times are in milliseconds.

MacBookPro5,3 / Chrome 51.0.2704.103 / requirejs mode:

```
Home: model=0, view=236, total=236
‪Patterns‬: model=25, view=2704, total=2729
Numbers‬: model=3, view=1259, total=1262
‪Equations‬: model=1, view=674, total=675
Mystery‬: model=30, view=1637, total=1667
TOTAL: mode=59, view=6510, total=6569 (6.5 seconds)
```

MacBookPro5,3 / Chrome 51.0.2704.103 / built mode:

```
Home: model=0, view=115, total=115
Patterns‬: model=8, view=1131, total=1139
Numbers‬: model=3, view=592, total=595
‪Equations‬: model=1, view=509, total=510
Mystery‬: model=26, view=1304, total=1330
TOTAL: model=28, view=3651, total=3689 (3.7 seconds)
```

**Comment by pixelzoom** [comment]
iPad2 / iOS 9.3.2 / Safari / requirejs mode:
```
TBD
```

iPad2 / iOS 9.3.2 / Safari / built mode:
```
Home: model=1, view=383, total=384
Patterns‬: model=33, view=4728, total=4761
Numbers‬: model=5, view=2233, total=2238
Equations‬: model=3, view=1669, total=1672
Mystery‬: model=31, view=4302, total=4333
TOTAL: model=73, view=13315, total=13388 (13.5 seconds)
```

**Comment by pixelzoom** [comment]
@amanda-phet @ariel-phet The initialization times for iPad2 are shown in the comment above. We're looking at 13-14 seconds.  Patterns and Mystery screens account for most of this, 5 seconds each. Unlike desktop, built mode doesn't seem to initialize any fast than requirejs mode, no idea why that's the case, but I confirmed on multiple runs.

**Comment by pixelzoom** [comment]
@amanda-phet @ariel-phet I'd like to close this issue. Have you reviewed the profiling in https://github.com/phetsims/function-builder/issues/37#issuecomment-228180214? Have you tried the sim on iPad2? Are you still OK with the decision to incur the full initialization cost on startup?

**Comment by ariel-phet** [comment]
I am getting an average stratup time on iPad 2 (iOS 9.3.2) of around 12.5 seconds.

This is an acceptable cost to pay up front for being able to move seamlessly through the sim.

Great job getting it as light weight as possible! Closing

**Comment by ariel-phet** [comment]
BTW, just as an added note, it is blazing fast on desktop (~3s).
