### ISSUE TITLE
stranded functions and cards

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#40]
@pixelzoom this is for phetsims/tasks#589. Noticed on all Win 10 browsers and iPad 2 iOS 9.3.1 (Tycho).

Doesn't matter the state of the sim when you do this @pixelzoom...just do the steps:
1. Put a function into the machine.
2. Begin to drag another function on top of a function already in the machine. Hover over the function and prepare your finger.
3. Quickly after releasing the dragged function, start clicking/tapping rapidly above the slot (you will be grabbing/releasing the functions mid-animation back to the carousel). You may make this issue happen right away, or it will take a couple seconds. Stop clicking when once you see nothing animating. The two functions will now be occupying the same slot (but only the "bottom" function is applied to the inputs).
![greatmath](https://cloud.githubusercontent.com/assets/5863899/15198410/72bf4b8a-1794-11e6-9459-54ff501c8c82.PNG)

Seen in the above screenshot: The hide function option will only apply to the bottom function, and the "see inside" boxes will be buried underneath the top functions. Did I just type functions with an "s"? Yes I did, you can repeat these steps as many times as you like to make a huge stack of functions and completely exhaust the carousel. If you were curious, the two functions at the bottom of this screenshot are two "x2" functions.

If you need a video, let me know...might have to screen share.

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.25/function-builder_en.html
Version: 1.0.0-dev.25 2016-05-05 18:36:48 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Language: en-US
Window: 2560x1315
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"b461c809","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"184674ba","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"function-builder":{"sha":"3d4fe673","branch":"master"},"joist":{"sha":"48836bcf","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"7590be09","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"9f2d40d5","branch":"master"},"tandem":{"sha":"5af5b8f8","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
Since the functions are in front of the 'see inside' windows, they are not actually in the builder, they are more likely stranded in the drag layer.  I asked @phet-steele to run master in requirejs mode with assertions enabled, and he reported no console output.

**Comment by pixelzoom** [comment]
These "stranded" functions can be dragged back to the carousel, and they don't affect the output result.

**Comment by pixelzoom** [comment]
Reducing priority to low, because this is just an unlikely use case.

**Comment by phet-steele** [comment]
@pixelzoom I believe you can do the same thing with cards in the output carousel. They no longer are recognized as populating the carousel; the erase button is grayed and the table is incomplete. Is this the same issue? It follows the same procedure of quickly clicking the card once it's in the output carousel.
<img width="1630" alt="screen shot 2016-06-10 at 12 18 34 pm" src="https://cloud.githubusercontent.com/assets/5863899/16017647/11ffc3cc-315e-11e6-879a-3c22ee9d3dcd.png">

**Comment by pixelzoom** [comment]
@phet-steele In the case with the output carousel, does scrolling the carousel cause the card to move? I suspect not, in which case the card is not actually in the output carousel, but likely still in the drag layer.

**Comment by phet-steele** [comment]
Your suspicions are correct. If you notice in the screenshot, the carousel is on the third page, which shouldn't have the 2 in it.

**Comment by pixelzoom** [comment]
Well, it's good that this occurs with both the functions and cards, because they share the same dragHandler architecture.  May make it easier to figure out.  Or not.

**Comment by pixelzoom** [comment]
Increasing priority to medium, since it affects both functions and cards.

**Comment by pixelzoom** [comment]
Reproduced on my iPad2 with card in output carousel.

**Comment by pixelzoom** [comment]
@phet-steele Your original report said "Hover over the function and prepare your finger" in one of the steps. Wondering if you seen this issue on non-touch devices?

**Comment by pixelzoom** [comment]
Never mind, I just reproduce it on Chrome + Mac OS X.

**Comment by pixelzoom** [comment]
Also reproduced the issue with functions on Chrome + Mac OS X.

**Comment by pixelzoom** [comment]
This smells like an issue with Tween callbacks, which the sim relies on heavily for animation.

**Comment by pixelzoom** [comment]
Adding debug output to FunctionNode `animateToCarousel` and `animateToBuilder`, here's what should happen in the typical case when a function (eg Rotate90) is dragged to a slot that is occupied by another function (eg Mirror):

```
Mirror.animateToBuilder begin
Mirror.animateToBuilder slot occupied
Rotate90.animateToCarousel begin
Mirror.animateToBuilder end
Rotate90.animateToCarousel end
```

Here's what I see if I click quickly after releasing Mirror in the same scenario:

```
Mirror.animateToBuilder begin
Mirror.animateToBuilder slot occupied
Rotate90.animateToCarousel begin
Mirror.animateToBuilder end
(3) Rotate90.animateToBuilder begin
```
Note that "Rotate90.animateToBuilder begin" appears 3x at the end, there is no indication that the slot was occupied by Mirror, and there is no corresponding "Rotate90.animateToBuilder end".

**Comment by pixelzoom** [comment]
Tween isn't involved here at all, the animation is handled by Movable.step and its animationCompletedCallback field.  Tween animation is used only for fading between scenes in this sim.

**Comment by pixelzoom** [comment]
Problem identified and fix.  It is possible (and necessary in many situations) for a Movable's `animationCompletedCallback` to set an additional `animationCompletedCallback`.  But the implementation of Movable.isAnimating was preventing these additional callbacks from executing in some situations.  This situation (rapidly clicking on something close to its location in a carousel) was such a situation.  

I believe I've fixed it in the above 1-line commit, since I can easily make the problem come and go by changing this one line.  With the fix, I no longer see the the problem on Chrome + Mac OS X, and that this fix applies to all platforms. 

That said... @phet-steele please work you verification magic on this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.54/function-builder_en.html

**Comment by phet-steele** [comment]
@pixelzoom used an autoclicker going at ~50 clicks a second, and this issue looks resolved on a smattering of platforms.

**Comment by pixelzoom** [comment]
Thanks @phet-steele, I'm going to consider this closed.
