### ISSUE TITLE
The sim crashes without ?log

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#41]
Testing for https://github.com/phetsims/phet-io/issues/440 I noticed the simulation will crash in both requirejs mode and built mode unless ?log is specified as a query parameter.  This should be fixed before I publish a test version for @phet-steele in https://github.com/phetsims/phet-io/issues/440

**Comment by pixelzoom** [comment]
What are you testing? This was fixed in master on 5/13/16.

**Comment by samreid** [comment]
Looked like I hadn't pulled lately, thanks!
