### ISSUE TITLE
Test a built version of Function Builder

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#42]
As discussed in https://github.com/phetsims/phet-io/issues/440 we would like to test Function Builder with the changes in chipper, tandem and joist before merging changes into master.

The main things to test pertain to the startup sequence, since the launch strategy is one of the main changes:
- [x] any errors during startup
- [x] do the images appear, and look normal
- [x] does the overall behavior seem normal (minor detail bugs may not be related to the branch changes)

Ideally the tests above would be done on all of our supported platforms (though time could be saved by skipping near-identical platforms).

We would like to test a requirejs version (to make sure development is unimpeded) as well as a built version, but delivering a requirejs version to test on many platforms may be difficult.  Perhaps we should start with @phet-steele testing the built version.  If that goes acceptably well, the code could be merged to master, then @phet-steele could test the requirejs development mode code from master on phettest.colorado.edu.

@pixelzoom is the sim in a good situation to have a dev version published and tested as described above?  If so, assign this issue to me and I can publish from the phet-io-require-2 branches.

**Comment by pixelzoom** [comment]
Plan looks good and sim is in a good situation at this moment.

**Comment by samreid** [comment]
Thanks @pixelzoom, I'll proceed.

**Comment by samreid** [comment]
deployed: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.30/function-builder_en.html

@phet-steele can you take this built version for a test drive on a smattering of platforms as described above?

**Comment by ariel-phet** [comment]
@phet-steele this is tippy top priority :) (as in please do this before any other QA tasks including new webserver testing)

**Comment by phet-steele** [comment]
@samreid @pixelzoom things appeared to not be disrupted. Tried Win 10 Chrome, iPad Air2 iOS 9.3.2, and OSX 10.11.5 Safari.

**Comment by samreid** [comment]
Thanks @phet-steele, I'll mark this for developer meeting and we'll discuss whether we are go for a merge or waiting on the phet-io testing in https://github.com/phetsims/phet-io/issues/440

**Comment by samreid** [comment]
We agreed to wait a bit and see if the phet-io things are tested soon, closing.
