### ISSUE TITLE
constrain to 1 card "parked" in the builder at a time

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#44]
In https://github.com/phetsims/tasks/issues/594#issuecomment-219818916 (results of preliminary interviews), @amyh-phet said:

> 3) One student managed to place several cards in the builder when using the "see through" feature, including stacking cards on top of each other in the same "see through" slot. In speaking with @ariel-phet, it sounds like this has come up in design meetings previously. The student was confused when he did this as he lost track of what cards he had placed in the builder, especially when the cards stacked. This seemed especially confusing in the Numbers and Equations screen as reading the function and outputs from left to right no longer made sense. Based on what I noticed from student interactions, it would be best if only one card was allowed in the builder at a time.

@ariel-phet requested to change the current behavior so that only 1 card (input or output) is allowed in the builder at a time.  If another card is drag towards the builder, it is rejected -- dragging is blocked at the builder's input/output slots, and if a card is released it returns to the input/output carousel.

This will involve major changes to CardNode drag handler, *the* most complicated piece of code in the sim, which has already been vetted by @phet-steele.  So we should verify this change request in a design meeting before proceeding.

**Comment by pixelzoom** [comment]
Setting to high priority, since this will be a time-consuming change, better done sooner than later.

**Comment by pixelzoom** [comment]
The fix in #47 may mitigate "lost card syndrome" somewhat.  The card that you most recently grabbed is now always on top, so it won't disappear behind cards that are already in the builder.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to decide how/when to discuss this issue with the design team.

**Comment by pixelzoom** [comment]
In a Skype call today, @ariel-phet suggested something different than what is described in https://github.com/phetsims/function-builder/issues/44#issue-155554345.  He suggested that dragging a card into the builder should cause any cards that are in the builder and not being dragged to exit the builder (similar to what happens when you turn off 'See Inside').  The question then would be what to do when multiple cards are released while in the builder.

Another concern about only allowing 1 card in the builder at a time is that it make may certain explorations/activities impossible.  For example, the student may want to put a card in a 'See Inside' window, then drag another card (of the same or different type) through to compare.  That will be impossible.

**Comment by amanda-phet** [comment]
Could part of this issue be related to not knowing how to push the card forward when "see inside" is checked? I actually didn't know how to do this myself when I played with the sim recently (and I am the lead designer...). The card paused in the window and I wasn't sure if it got stuck, or what I needed to do to keep it moving.

**Comment by pixelzoom** [comment]
>  I actually didn't know how to do this myself when I played with the sim recently (and I am the lead designer...).

What did you try to do? Did you figure it out? 

To move a card that's in a 'See Inside' window, you grab it and move it - the same interaction that you do with cards visible anywhere else. If you turn off 'See Inside', the cards are flushed out of the builder.

**Comment by pixelzoom** [comment]
Something that may be relatively easy to do is to allow only 1 card to be sitting in the builder at a time. That means that, regardless of the number of "See Inside" windows in the builder, only 1 window can ever be occupied, and by only 1 card.  As soon as another card is released and enters a window, any card that is currently in a window is flushed from the builder.

**Comment by pixelzoom** [comment]
5/26/16 design meeting:

Let's try the proposal in https://github.com/phetsims/function-builder/issues/44#issuecomment-221971960.

**Comment by pixelzoom** [comment]
@amanda-phet mentioning you so that you're aware that this change is going to be made. I don't recall if you attended the design meeting where this decision was made (no one has been making notes in the design doc for some time.) I will wait to proceed with this work until I have your OK.

**Comment by amanda-phet** [comment]
Thanks Chris. Please proceed- I believe I was at the meeting and am very much OK with the solution to have 1 card in the builder at a time.

**Comment by pixelzoom** [comment]
FYI... This is proving to be really difficult.

**Comment by pixelzoom** [comment]
FYI... This is proving to be really difficult, not "relatively easy" as I guessed in https://github.com/phetsims/function-builder/issues/44#issuecomment-221971960.

**Comment by pixelzoom** [comment]
It involves significant changes to (1) the drag handler in CardNode, the most complicated piece of code in the sim, (2) animation in CardNode, the second most complicated piece of code in the sim.

**Comment by pixelzoom** [comment]
As the only remaining issue, this is now my top priority.

**Comment by pixelzoom** [comment]
@amanda-phet @ariel-phet Here's a dev version that implements this constraint. Please verify that this meets your expectations.

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.68/function-builder_en.html

When a card reaches a 'see inside' window, cards in any other windows are animated to the output carousel, without stopping at any other windows. If multiple cards are in play, the last card to reach a window will occupy that window, and all other cards that were in windows are animated to the output carousel.

Also worth noting again... Restricting the 'see inside' windows to a single card makes certain types of exploration impossible.  For example, see the screenshot below, where 2 instances of the "butterfly" card are compared at various stages in the builder. This is now impossible.  And that may be OK, I just wanted to point it out.

![screenshot_44](https://cloud.githubusercontent.com/assets/3046552/16535361/e306ce2c-3fa3-11e6-8d6e-f63ed030b97d.png)

**Comment by ariel-phet** [comment]
@pixelzoom this meets my expectations of what we described. Although you cannot statically compare to identical pattern inputs in the builder, it is still quite easy to put one input in the builder and drag and hold the other at the see inside windows, so I am not concerned that we no longer have the static comparison functionality.

When we saw this commit, the whole QA crew pulled the latest version earlier this afternoon to check it out :). I don't think there were any obvious bugs ( @phet-steele of course tried to break it!).

Removing my assignment, and leaving to @amanda-phet for final decision to close or further discussion.

**Comment by pixelzoom** [comment]
@amanda-phet Your feedback? Top priority.  I'd like to move forward with final dev test, and this is the blocking issue.

**Comment by amanda-phet** [comment]
It's not quite ideal, for the reasons you point out. We'll probably need to let teachers knows that you can drag a card without letting go. 

Can I use this version in my interviews this afternoon? I'd want to see if students ever move a card forward or if they always "push" it out with another input.

**Comment by pixelzoom** [comment]
Yes, feel free to use this version in interviews.

**Comment by ariel-phet** [comment]
@pixelzoom since you said you touched a significant portion of code - it seems there would be no penalty for moving ahead with dev testing regardless. Please make a task if you see fit.

**Comment by pixelzoom** [comment]
@ariel-phet dev testing doesn't happen until after final change requests are received from the team. The deadline for final change requests is next Monday, 7/11/16.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> We'll probably need to let teachers knows that you can drag a card without letting go.

This is being tracked in https://github.com/phetsims/function-builder/issues/52#issuecomment-230061663.

**Comment by pixelzoom** [comment]
@amanda-phet's feedback didn't indicate any discrepancy between the implementation and the expected behavior, so I'm going to close this issue.  If any problems are noted during interviews that require revising how this works, please open a new issue.
