### ISSUE TITLE
Consider changing icons for mystery functions in Patterns screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#45]
From preliminary interview results, https://github.com/phetsims/tasks/issues/594#issuecomment-219818916:

> 4) On the Patterns screen, both students realized that the icons on the functions gave hints as to what the functions did to each image. This was helpful to an extent, but led the students to analyze each icon. [...] One student attempted to ascribe meaning to the shapes behind the letters on the mystery functions. One thing that we might need to think about is how much we want the function icons to give cues to students.

Consider changing the mystery function icons in the Patterns screen. Presents ala Balancing Act? Get rid of translatable text if possible?

**Comment by pixelzoom** [comment]
How about something as simple as getting rid of the confusing shades behind the letters, and replacing the letters with '?', like this:

![screenshot_37](https://cloud.githubusercontent.com/assets/3046552/15517859/4243a1a4-21b7-11e6-971e-67a25089b52d.png)

The teacher could refer to one of these function as (for example) "the purple mystery function" or "the purple function with the question mark".  And since this is what we intended to do in the Mystery screen, it's probably good to do the same thing in the Patterns screen.

**Comment by pixelzoom** [comment]
Btw... The above solution would take ~15 minutes to implement.  Something like Balancing Act (labeled packages) is going to take a lot longer, and we'll need lots of packages in the Mystery screen.

**Comment by pixelzoom** [comment]
I also think package icons (ala Balancing Act) might be a bit distracting/noisy on the Patterns screen. We already have a lot of visual noise with the icons on the cards.

**Comment by pixelzoom** [comment]
I also think package icons (ala Balancing Act) might be a bit distracting/noisy on the Patterns screen. We already have a lot of visual noise with the icons on the cards.  Compare package icons to simple '?' label in the screenshots below.

![screenshot_38](https://cloud.githubusercontent.com/assets/3046552/15518247/27812556-21b9-11e6-85bc-0de21293b587.png)

![screenshot_39](https://cloud.githubusercontent.com/assets/3046552/15518243/2510b9ee-21b9-11e6-8956-cc7151553e6b.png)

**Comment by amanda-phet** [comment]
The letters are intended to be a quick and simple way to reference the functions, just like the presents in balancing act are labeled with letters.

**Comment by pixelzoom** [comment]
> One student attempted to ascribe meaning to the shapes behind the letters on the mystery functions.

The primary issue is with the shapes behind the letters. 

In the Mystery screen, we're planning to label the cards with '?'.  So why would we use a different representation in the Patterns screen?

**Comment by amanda-phet** [comment]
Ah, good point. On the Numbers screen the ? originally replaced a missing number (+ ?), operation (? 3), or both (??), whereas on the Patterns screen a letter was replacing an image.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, May 26, 2016 at 8:15 AM -0700, "Chris Malley" <notifications@github.com<mailto:notifications@github.com>> wrote:


One student attempted to ascribe meaning to the shapes behind the letters on the mystery functions.

The primary issue is with the shapes behind the letters.

In the Mystery screen, we're planning to label the cards with '?'. So why would we use a different representation in the Patterns screen?

-

**Comment by pixelzoom** [comment]
5/26/16 design meeting:

Consensus is to use '?' with a letter subscript, and get rid of halo shape. I.e.:

![screenshot_48](https://cloud.githubusercontent.com/assets/3046552/15588147/b9bc112e-2349-11e6-8797-df158277bd6b.png)

**Comment by pixelzoom** [comment]
Done, closing.
