### ISSUE TITLE
Consider changing icons for identity and Warhol functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#46]
From preliminary interview results in https://github.com/phetsims/tasks/issues/594#issuecomment-219818916:

> 4) On the Patterns screen, both students realized that the icons on the functions gave hints as to what the functions did to each image. This was helpful to an extent, but led the students to analyze each icon. Neither student understood the identity function, and they mentioned they thought the function might make the image on the input card brighter. Neither student connected the soup can with Warhol, but one student mentioned Picasso and both students were able to describe what the function did despite not being able to use the term Warhol. Both students liked the Warhol effect. [...] One thing that we might need to think about is how much we want the function icons to give cues to students.

Consider a new icon for identity function.

**Comment by ariel-phet** [comment]
We should also ask ourselves if want to keep the soup can. This could be fine, but we could also go for just an "art" metaphor like a painting brush

**Comment by amanda-phet** [comment]
The soup can is meant to be somewhat of an "easter egg". It is art history, and teachers can explain it to their students for an interdisciplinary discussion if they want. That's also why it is the last function. 

I'm open to a different icon for identity- suggestions?

**Comment by pixelzoom** [comment]
For someone who is familiar with the "Warhol effect" the most iconic representation would be:

![unnamed](https://cloud.githubusercontent.com/assets/3046552/15580016/4464fa14-2324-11e6-95ac-bb8a9aa0e38a.png)

But there are lots of problems with that icon: it shows a specific image; it may have right-to-use issues; etc.  I'm not suggesting that we should use it, but pointing out that we are unlikely to find an icon that clearly conveys "Warhol effect".  So I'm find with the soup can.

For the identity function, the observation was:
> Neither student understood the identity function, and they mentioned they thought the function might make the image on the input card brighter. 

So might the solution be to simply removed the lines surrounding the stick figure?

**Comment by pixelzoom** [comment]
For the identity function, the observation was:

> Neither student understood the identity function, and they mentioned they thought the function might make the image on the input card brighter.

So might the solution be to simply removed the lines and "glow" surrounding the stick figure?  Here's what it looks like currently:

![screenshot_40](https://cloud.githubusercontent.com/assets/3046552/15581310/f6eeecb8-2328-11e6-8a21-64071d98009e.png)

**Comment by pixelzoom** [comment]
Here's the current identify icon without the elements that provide the "brighter" cues:

![screenshot_41](https://cloud.githubusercontent.com/assets/3046552/15581870/78b92d1a-232b-11e6-847a-ad3385b1374e.png)

Here it is in context:

![screenshot_43](https://cloud.githubusercontent.com/assets/3046552/15581857/64d5e4d2-232b-11e6-9b68-ea9f28f6299b.png)

**Comment by pixelzoom** [comment]
Also worth noting is that we have stick figures on both a card and a function.

**Comment by pixelzoom** [comment]
@ariel-phet suggested a stick figure that is pointing to him/herself.

**Comment by pixelzoom** [comment]
5/26/16 design meeting:

• Everyone is OK with the soup can.

• For now, just remove "brightness" cues from identity icon.  A "selfie" icon was also discussed.

**Comment by pixelzoom** [comment]
Identity function icon has been changed.

Assigning to @ariel-phet to decide when (or if) he wants someone to take a stab at a new icon.

**Comment by pixelzoom** [comment]
Comments relevant to identity function icon in https://github.com/phetsims/tasks/issues/604#issuecomment-222723912 (iOS interviews):

> Students still were confused by the output of the identity function (no change), but the icon was not misleading (e.g., students did not expect a different outcome based on the icon).

I asked about whether the students figured it out, and @amyh-phet said in https://github.com/phetsims/tasks/issues/604#issuecomment-222747143:

> Students realize the identity function doesn't change the image on the card. One student though it might rotate the image "all the way around". Others expressed that they realized no change happened, but weren't sure why. I think this is function will be a great teaching point as students are expecting the image to change but it doesn't.

@ariel-phet up to you whether to take another stab at revising the identity icon, or to just close this issue.

**Comment by amanda-phet** [comment]
@ariel-phet based on the interview I think it might be worth trying a different icon. It seems like the icon doesn't currently hurt, but it also doesn't help or seem to have any connection for students, and it should. I like the selfie idea- can we roll with that?

**Comment by pixelzoom** [comment]
@ariel-phet Are we going to do revise this icon? If so, can you please assign this to someone?

**Comment by ariel-phet** [comment]
@pixelzoom I took a few quick stabs at this myself, but did not really come up with anything I loved.

@amanda-phet since you are back this week, want to take a try at the icon? It seems we will want something like this: https://thenounproject.com/term/selfie/397877/

I tried a full stick figure, but then the detail gets too small to see, so I think just the upper torso is probably the way to go, or a very "squat" stick figure

**Comment by amanda-phet** [comment]
I took a stab at this too but I think the selfie you linked to actually works really well...
<img width="890" alt="screen shot 2016-06-13 at 11 58 39 am" src="https://cloud.githubusercontent.com/assets/7852916/16017706/47c47c82-315e-11e6-9341-9ba3f5aada98.png">

**Comment by ariel-phet** [comment]
@amanda-phet I think I would modify it slightly...make the phone a bit bigger and the "flash" a bit more prominent.

**Comment by pixelzoom** [comment]
+1 for bigger phone and more "flash".

**Comment by amanda-phet** [comment]
<img width="678" alt="screen shot 2016-06-14 at 1 08 28 pm" src="https://cloud.githubusercontent.com/assets/7852916/16056078/210218ba-3231-11e6-8b5c-7b176b103478.png">

**Comment by pixelzoom** [comment]
It looks like the person got significantly larger.  I think the suggestion was to make the phone and flash relatively larger.

**Comment by pixelzoom** [comment]
@amanda-phet If you make changes to card-icons.ai, make sure you grab the latest from GitHub. I just made a change to it (grouped the circle with the star for #34).

**Comment by amanda-phet** [comment]
I also made the torso shorter... which is perhaps the more noticeable difference. 

How about this?
<img width="682" alt="screen shot 2016-06-14 at 4 44 31 pm" src="https://cloud.githubusercontent.com/assets/7852916/16062279/590ff902-324f-11e6-9b5a-ce47ab515414.png">

I wouldn't make the phone and flash too much larger or else they might start looking like a hairbrush, or just something else entirely.

We could also try making the image less iconic... using some more color and detail.

**Comment by pixelzoom** [comment]
Looks good to me. @ariel-phet?

It would be nice to get this into the sim and do a couple of quick interviews.

**Comment by ariel-phet** [comment]
Looks good to me!

**Comment by ariel-phet** [comment]
And @pixelzoom - @amanda-phet is planning to do some interviews, but at this point I think it is fine for them to wait until mystery screen. Since students did not have a problem with the last iteration of the identity function (no brightness), we could always change back to that if the selfie analogy does not fly.

**Comment by pixelzoom** [comment]
Got it.

@amanda-phet When you're ready, add the new icon to the latest card-icons.ai (in GitHub).  Then either send the modified file to me, or check it back into GitHub.   Then I'll create the PNG file and integrate it into the sim.

**Comment by pixelzoom** [comment]
Revised function-icons.ai received from @amanda-phet via email, integrated in this version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.58/function-builder_en.html

@amanda-phet If this looks OK, go ahead and close this issue.

**Comment by pixelzoom** [comment]
@amanda-phet please review.

**Comment by amanda-phet** [comment]
Looks good. If there are issues from interviews I can re-open this issue.

**Comment by pixelzoom** [comment]
@amanda-phet noted that there were still issues with the identity function during interviews. Rather than reopen this issue, we're tracking in https://github.com/phetsims/function-builder/issues/91.
