### ISSUE TITLE
how to represent 'input' and 'output' in Numbers screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#51]
In the design document, the equation drawer in the "Numbers" screen looks like this:

![screenshot_34](https://cloud.githubusercontent.com/assets/3046552/15517333/6de7bf00-21b4-11e6-96d7-78d4d055d4a9.png)

The idea here is to not introduce 'x' and 'y', but instead talk about 'input' and 'output'.  And the 'In' and 'Out' shown in the equation are supposed to be input and output cards respectively.

There are a couple of problems with this design:

(1) 'In' and 'Out' are not nouns, they are awkward shorthand for 'Input' and 'Output', which we're using so that they fit on a square card.

(2) When translated, the plan is to distort the cards, so that they are no longer square. See example below. This distortion breaks the association with cards.

![screenshot_35](https://cloud.githubusercontent.com/assets/3046552/15517434/ea88331e-21b4-11e6-99fa-ae926dc59ab6.png)

I'd like to brainstorm other possible designs with @amanda-phet @ariel-phet @kathy-phet @samreid @bethstade.

**Comment by pixelzoom** [comment]
My ideas:

(1) Replace 'In' and 'Out' with icons that represent 'input' and 'output', and use those icons in both the equation and table.

(2) Use 'Input' and 'Output' strings, and forget about making them look like cards. You can see this in [1.0.0-dev.35](http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.35/function-builder_en.html), where it's currently a placeholder.  Here's a screenshot:

![screenshot_36](https://cloud.githubusercontent.com/assets/3046552/15517628/fac2fad8-21b5-11e6-9f74-e4f10afd141f.png)

**Comment by bethstade** [comment]
The obvious icons would be X and Y.
Which of course makes it more like the equation screen.
Or one could suggest the "Numbers" screen could be more like "Patterns," just with numbers, and remove the table and equations.
----- Original Message -----From: Chris Malley <notifications@github.com>To: phetsims/function-builder <function-builder@noreply.github.com>Cc: bethstade <stadee@colorado.edu>, Mention <mention@noreply.github.com>Sent: Tue, 24 May 2016 20:26:42 -0000 (UTC)Subject: Re: [phetsims/function-builder] how to represent 'input' and 'output' in Numbers screen (#51)

My ideas:
(1) Replace 'In' and 'Out' with icons that represent 'input' and 'output', and use those icons in both the equation and table.
(2) Use 'Input' and 'Output' strings, and forget about making them look like cards. You can see this in 1.0.0-dev.35, where this was intended to be a temporary solution. Here's a screenshot:

&mdash;You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by amanda-phet** [comment]
>(1) 'In' and 'Out' are not nouns, they are awkward shorthand for 'Input' and 'Output', which we're using so that they fit on a square card.

I understand that this is awkward and am open to new suggestions

>(2) When translated, the plan is to distort the cards, so that they are no longer square. See example below. This distortion breaks the association with cards.

I disagree that this distortion breaks the association. I think it is still very clear, and much clearer than just using the words. Seeing letters in math is very confusing and off-putting to some students, and the rounded rectangle/square is meant to be more iconic. I think it would be worthwhile to brainstorm an iconic representation that could work here if we can't use words.

**Comment by pixelzoom** [comment]
A downside of using an icon is that (presumably) we'll want to use the same icon to label the columns in the table.  And in the table, we are very tight on vertical space.   The height of the column labels will need to increase, and that will result in a smaller (and less readable) equation for the 'x' row in the table.

**Comment by pixelzoom** [comment]
@ariel-phet suggested something like this "input" icon, and a corresponding "output" icon. We'd make the slot narrower, ala the builder input/output slots.

![screenshot_44](https://cloud.githubusercontent.com/assets/3046552/15585832/9121f8ce-233e-11e6-964d-5c9045380a31.png)

**Comment by pixelzoom** [comment]
5/26/16 design meeting:

Start by putting rounded rectangles (like cards) around the words "Input" and "Output" in equation.  Max width for rectangles, make the translated words scale.  Min width so that cards remain square.

**Comment by pixelzoom** [comment]
Notes to self.... There are 2 ways to approach this.

(1) Pass in xNode and yNode to SlopeInterceptEquationNode and PhetEquationNode.

(2) Make SlopeInterceptEquationNode responsible for creating the rectangle around the symbols. Add options related to the rectangle. Probably something like:

```js
xyRectangleVisible: false, // {boolean} whether to put a rectangle around x & y symbols
xyRectangleXMargin: ...,
xyRectangleYMaring: ...,
xyRectangleMaxWidth: .... // {number} maxWidth of the rectangle, for i18n
xyRctangleMinWidth: ... // {number} min width of the rectangle, to keep the rectangle square
```

Potential problems:

• For the PhET-specific (aka "helpful") form of the equation, the xSymbol "card" needs to scale, since it may be in a numerator.

**Comment by pixelzoom** [comment]
I ran into a problem already...  For the PhET-specific (aka "helpful") form of the equation, the "Input" card needs to scale, since it may be in a numerator. Eg (as noted in https://github.com/phetsims/function-builder/blob/master/doc/equation-formats.md), if the builder contains "/3 * 2", then the equation will be "y = [2 Input]/3", where "2 Input" is the numerator above denominator 3.  In the slope-intercept equation, fractions are in a smaller font. If we remain consistent, then the "Input" card will be scaled.

@amanda-phet @ariel-phet Are you OK with the "Input" and "Output" cards being different sizes in the equation? Or would you prefer to have the cards the same size and scale the entire equation to fit?  If we do the latter, this is inconsistent with the slope-intercept equation, where fractions use a smaller font.

**Comment by ariel-phet** [comment]
@pixelzoom and I discussed and I was fine with the "Input" word scaling down as long as still readable

**Comment by amanda-phet** [comment]
We will probably need to assess once we see how small they get. 

This screen originally did not include division, so we could go back to leaving out that operation here and then we wouldn't have any fractions.

**Comment by pixelzoom** [comment]
Re the design meeting consensus in https://github.com/phetsims/function-builder/issues/51#issuecomment-221982425... I'm going to wait to implement this until I've implemented the PhET-specific (aka "helpful") form of the equation.

**Comment by pixelzoom** [comment]
Implemented "card" look for "Input" and "Output" in equations, see above commit.  Here are a few example screenshots, showing both equation forms in the Numbers screen:

![screenshot_54](https://cloud.githubusercontent.com/assets/3046552/15698069/f3e27ef0-277d-11e6-80a6-a15809181d2c.png)
![screenshot_56](https://cloud.githubusercontent.com/assets/3046552/15698072/f94b2db0-277d-11e6-9eee-58010746d6e3.png)
![screenshot_57](https://cloud.githubusercontent.com/assets/3046552/15698105/40b2f1a6-277e-11e6-90cd-ec03a7e09476.png)
![screenshot_58](https://cloud.githubusercontent.com/assets/3046552/15698106/4329110e-277e-11e6-95c7-7b0e46334137.png)

**Comment by pixelzoom** [comment]
Implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.39/function-builder_en.html

@amanda-phet and @ariel-phet please provide feedback.

**Comment by ariel-phet** [comment]
I know there was concern over the cards changing size, but that all seems fine.

I will say that in the design doc, @amanda-phet used a non-italic font. I know we are using an italic script font for the variables and that feels right to me for those, but I think I would prefer the font in the design doc, it feels more approachable.

**Comment by amanda-phet** [comment]
I think the card really works here. 

I would also like to try the non-italic font.

**Comment by pixelzoom** [comment]
Changed to non-italic font, pushed to master.  Examples:

![screenshot_59](https://cloud.githubusercontent.com/assets/3046552/15717438/45325ecc-27e4-11e6-8f54-766287dd777a.png)

![screenshot_60](https://cloud.githubusercontent.com/assets/3046552/15717430/40b5f2dc-27e4-11e6-95f7-29a82659d889.png)

**Comment by pixelzoom** [comment]
@amanda-phet and @ariel-phet Are you satisfied with the non-italic font, as shown in https://github.com/phetsims/function-builder/issues/51#issuecomment-223050211?

**Comment by pixelzoom** [comment]
Skype call with @ariel-phet, looks good, closing.

**Comment by amanda-phet** [comment]
I like it! Thanks @pixelzoom and @ariel-phet
