### ISSUE TITLE
things that should be in teacher tips

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#52]
This issue will be used to note things that should be in the teacher tips.

**Comment by pixelzoom** [comment]
The "invert RGB" function (below) is not obvious, unlikely that teachers or students will understand that it inverts the RGB colorspace, and is therefore invertible.  This should be noted in the teacher tips.

![screenshot_47](https://cloud.githubusercontent.com/assets/3046552/15586553/32f256dc-2342-11e6-85e1-7129878562d5.png)

**Comment by pixelzoom** [comment]
Describe what the mystery functions do in the Patterns screen.

**Comment by amanda-phet** [comment]
describe how to use equations screen to help figure out mystery functions

**Comment by pixelzoom** [comment]
Mention that the first instance of each function on the Mystery screen is always the same, identify what those functions are, describe how to get back to them using the "Reset All" button.

**Comment by pixelzoom** [comment]
Mystery screen: Indicate how many functions must be moved to output carousel before the "See Inside" check box is enabled.  Ditto for when the "reveal function identity" buttons are enabled.

**Comment by pixelzoom** [comment]
Mystery screen info.

Enabling controls:
• 1 function must put in the output carousel before the "See Inside" check box is enabled.  
• 3 functions must be in the output carousel at the same time before the "reveal function" (eyeball) toggle buttons are enabled

On startup and "Reset All", the default challenge for each scene is: 
• 1 function: `+ 3`
• 2 functions: `+ 1 * 2`
• 3 functions: `+ 2 * 1 + 2`

**Comment by pixelzoom** [comment]
Perhaps mention the Warhol function, in case someone doesn't get it.

**Comment by pixelzoom** [comment]
Describe the "see inside" feature.

The total number of cards that can be "parked" in the "see inside" windows is at most 1. "Parked" means that the card is sitting in the window, and is not being dragged. When a 2nd card reaches a window, any card that may currently be parked in a window is animated to the output carousel.

**Comment by pixelzoom** [comment]
Describe the "hide functions" feature in the first 3 screens.

**Comment by pixelzoom** [comment]
For the screens that involve numbers, mention that the carousel contains a page of negative numbers [-4,-1] that might be overlooked.

**Comment by pixelzoom** [comment]
Mention how the input and output carousels are synchronized so that corresponding inputs and outputs remain vertically aligned.

**Comment by pixelzoom** [comment]
Describe how the table works.  A row is added when a card is removed from the input carousel, and it's output cell is initially empty. The row's output cell is filled in when its card is put in the output carousel.  A row is removed when its card is returned to the input carousel.  Rows are sorted by ascending x (input) value.

**Comment by pixelzoom** [comment]
Describe the "helpful" equation form, since it is non-standard (something that PhET invented).   The specification is in [equation-formats.md](https://github.com/phetsims/function-builder/blob/master/doc/equation-formats.md), which may or may not be useful to teachers.

**Comment by pixelzoom** [comment]
Describe how the graph works:
• A point is added when its number card is added to the output carousel. 
• A point is removed when its number card is removed from the output carousel. 
• The line representing the functions in the builder is added when the 'x' card is added to the output carousel. 
• The line is removed when the 'x' card is removed from the output carousel.

**Comment by pixelzoom** [comment]
Indicate that slope-intercept format is shown on the 'x' card.

**Comment by pixelzoom** [comment]
Describe how the sim handles non-invertible functions.  Give some examples.

**Comment by amanda-phet** [comment]
Teacher tips are complete. Closing.

**Comment by pixelzoom** [comment]
Teacher Tips look awesome by the way. Nice job!
