### ISSUE TITLE
PhET-specific equation format

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#53]
https://github.com/phetsims/function-builder/blob/master/doc/equation-formats.md specifies the PhET-specific (aka "helpful") equation format.  The specification contains numerous examples, followed by the rules for converting what is in the builder to the equation format. This format was agreed upon by consensus in 4/28/16 design meeting, and refined in followup email discussions.

The equation format is implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.38/function-builder_en.html

I have compared the implementation to the examples in the specification, and confirmed that they match.

To access the equations, go to the "Equations" screen. Open the drawer that is at the bottom center of the builder. When the “slope-intercept” check box is checked, slope-intercept form is displayed. When *not* checked, the “helpful” form is displayed.  

Team: Please review ASAP, and check off the box next to your name (below) after reviewing.  If you'd like to change the format, please create a comment in this issue; specify which rule you'd like to change, and provide examples.

- [x] @amanda-phet 
- [x] @amyh-phet 
- [x] @ariel-phet 
- [x] @bethstade
- [ ] @kathy-phet 
- [x] @samreid (I don't have time to look at this at the moment.)

**Comment by bethstade** [comment]
Looks consistent to me.
I noticed the negatives weren't implemented - I imagine you know this.
<img width="1088" alt="screen shot 2016-05-31 at 6 11 36 pm" src="https://cloud.githubusercontent.com/assets/5370001/15694469/55bb76fe-275b-11e6-9c71-111e0966a1ff.png">

**Comment by ariel-phet** [comment]
@pixelzoom the format works well with the interactivity as designed. I might have a pixel polish or two, but that seems for a separate issue since this issue is to determine the rules for the format.

**Comment by ariel-phet** [comment]
@pixelzoom - note negatives ARE working in slope-intercept form, just not in "helpful" form

**Comment by pixelzoom** [comment]
I'm not sure what you mean by "negatives aren't working".  They are indeed working, here's a screenshot below.  The operator is adjusted so that the operand doesn't have a negative sign.  Or were you expecting (for example in this case) "y = x - -2"?

![screenshot_50](https://cloud.githubusercontent.com/assets/3046552/15697076/e69d86fe-2773-11e6-94ef-e89a3c422465.png)

**Comment by pixelzoom** [comment]
If you were indeed expecting "y = x − -2" in the example above, then what are you expecting in the case below?  It seems to me that the most general solution is what I've implemented.

![screenshot_51](https://cloud.githubusercontent.com/assets/3046552/15697122/7eadd30e-2774-11e6-94cf-c95e6913baca.png)

**Comment by bethstade** [comment]
<img width="1088" alt="screen shot 2016-05-31 at 6 11 36 pm" src="https://cloud.githubusercontent.com/assets/5370001/15697250/c57874c8-2775-11e6-8766-3cdc72836f33.png">
In this example I expected -3 x + 2.

**Comment by pixelzoom** [comment]
@bethstade That example is indeed a bug, thanks for pointing it out.  Any others?

**Comment by pixelzoom** [comment]
Btw... If there is anything at all that does not look right, do *not* assume that it's something that I know about or have not implemented.  This equation is *fully* implemented, and anything that's not working as specified is a bug that should be reported.  And specific examples are always appreciated.

**Comment by pixelzoom** [comment]
Sign has been corrected when collapsing adjacent multiplication operations, see above commit.  Here's a screenshot for the example reported by @bethstade in https://github.com/phetsims/function-builder/issues/53#issuecomment-222882803. 

![screenshot_52](https://cloud.githubusercontent.com/assets/3046552/15697433/501312d6-2777-11e6-98f4-61e3acd95b72.png)

**Comment by pixelzoom** [comment]
Here's a new dev version with the bug fix for multiplier sign:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.39/function-builder_en.html

**Comment by amanda-phet** [comment]
This seems to be working well to me. 

In the following situation, two questions come to mind: 
1. Do we want the 3 and -3 to "cancel" and become -1? (I am thinking yes, but it might break the rules we have established) 
2. Do we want parentheses around larger fractions to be taller? (I think it is fine the way it is, but normally they would be larger) 
<img width="887" alt="screen shot 2016-06-01 at 7 32 53 am" src="https://cloud.githubusercontent.com/assets/7852916/15711513/8bfb0b60-27cb-11e6-93fc-76c18ead1c1b.png">

**Comment by ariel-phet** [comment]
@amanda-phet I don't think we want those to cancel actually...the premise behind the "helpful" for is to make the most sense with interaction, so in the current form, as you play with the card controlling the denominator, the relationship between the interaction and the equation is very clear. if you change that to a "-1" you would also need to put a "-3/2" when you change the division card to -2, and so on. I see the "helpful" form as really being the "cleanest mapping to the interactivity" form.

**Comment by ariel-phet** [comment]
:+1: on parentheses tweak but as mentioned above probably first to best establish rules of this form, and then pixel polish

**Comment by pixelzoom** [comment]
@amanda-phet Where did you get the screenshot in https://github.com/phetsims/function-builder/issues/53#issuecomment-222994053? That's not what I see with the functions shown.  What I see is shown below, very different.  And it follows this rule:

> (10) Adjacent multiplication and division operations are NOT collapsed, e.g.: * 2 / 3 → [2x]/3. There is one exception: adjacent multiplication and division operations that evaluates to 1 are collapsed and hidden, e.g.: / 3 * 3 → x

Re @ariel-phet comment in https://github.com/phetsims/function-builder/issues/53#issuecomment-223014339... Are you suggesting that we change the rule above?

![screenshot_61](https://cloud.githubusercontent.com/assets/3046552/15717770/b7794eb8-27e5-11e6-92fb-04ac2ea0687b.png)

**Comment by pixelzoom** [comment]
Re parenthesis... I agree that it would look better if the parenthesis were the same height as the term that they enclose.  But there's a problem with that.  Parenthesis are currently rendered using a scenery Text node, using the default PhET font (Arial). If I increase the size to match the height of the term, then the parenthesis look very heavy. Here's an example:

![screenshot_62](https://cloud.githubusercontent.com/assets/3046552/15717931/55c9e7e4-27e6-11e6-96b5-549919dfc84e.png)

Options:

(1) Experiment with different web-safe fonts. (Suggestions?)

(2) Draw the parenthesis as a curve. This will take a significant amount of time, and I suspect that you will be ultimately unhappy with the look.

**Comment by pixelzoom** [comment]
I experimented with `weight: 'lighter', stretch: 'ultra-condensed'` options for the parentheses font, but it didn't look significantly better.

**Comment by pixelzoom** [comment]
Scaling x & y dimensions of the parenthesis separately looks like a reasonable solution. Here's the same example that we've been discussing above. Cool?

![screenshot_63](https://cloud.githubusercontent.com/assets/3046552/15719161/ebfe484a-27eb-11e6-9570-e5992a9e9227.png)

**Comment by pixelzoom** [comment]
Commits related to parenthesis:
https://github.com/phetsims/function-builder/commit/f1a1023c1d9c2dade93f24aea82cc8636c3b2de9
https://github.com/phetsims/function-builder/commit/e73ee066371a8dc3ff23326e9079b4a03eaf5713
https://github.com/phetsims/function-builder/commit/f1a1023c1d9c2dade93f24aea82cc8636c3b2de9

**Comment by pixelzoom** [comment]
There is an inconsistency related to rule 10, which says:

> (10) Adjacent multiplication and division operations are NOT collapsed, e.g.: * 2 / 3 → [2x]/3. There is one exception: adjacent multiplication and division operations that evaluates to 1 are collapsed and hidden, e.g.: / 3 * 3 → x

Here's an example where rule 10 is applied:

![screenshot_66](https://cloud.githubusercontent.com/assets/3046552/15719353/c81803d4-27ec-11e6-9fd3-0d38127cf23f.png)

Here's a similar example, where adjacent multiplication and division value to -1, which is not covered by rule 10.

![screenshot_65](https://cloud.githubusercontent.com/assets/3046552/15719382/e60bc484-27ec-11e6-86ee-960c5cb4db80.png)

If we're going apply rule 10 consistently, shouldn't it apply if adjacent multiplication and division value to 1 *or -1`?  In which case, the above should be displayed as `y = -x`.

**Comment by pixelzoom** [comment]
Skype call with @ariel-phet, decisions:

• parentheses look good
• drop rule 10 (do not collapse adjacent multiplication and division that evaluates to 1 or -1)

**Comment by pixelzoom** [comment]
Changes incorporated in this dev version, please review:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.41/function-builder_en.html

If I don't receive any change requests in the next 24 hours, I'll close this issue.

**Comment by amyh-phet** [comment]
@pixelzoom    I did not see any use cases that break any of the rules from the design meeting notes.  I also did not see any unexpected behavior regarding the equation display.   I have only a minor pixel polish to report.  When applying two multiplications in a row with one of the functions being a negative (e.g. *-3 * 3), the negative sign on the equation output is bold when in the PhET version of the equation but is not bold in the slope-intercept form.  This causes the equation to jump a bit when checking and unchecking the slope-intercept box.    
![fb_inconsistent_negatives]
(https://cloud.githubusercontent.com/assets/13650180/15751052/ee0a0218-28a5-11e6-975f-c27d1113d8df.png)
![fb_inconsistent_negatives_helpful](https://cloud.githubusercontent.com/assets/13650180/15751064/f40917c6-28a5-11e6-92e7-bb30731daea3.png)

**Comment by pixelzoom** [comment]
Thanks @amyh-phet, good catch, should be easy to fix.

**Comment by pixelzoom** [comment]
Sign fixed in above commit. Screenshot:

![screenshot_02](https://cloud.githubusercontent.com/assets/3046552/15751844/dc7fc480-28a8-11e6-8442-3757c379b1dd.png)

**Comment by pixelzoom** [comment]
No additional feedback received, closing.

**Comment by amanda-phet** [comment]
Sorry for the delay in my response here... I will be much more responsive starting tomorrow!

>Scaling x & y dimensions of the parenthesis separately looks like a reasonable solution. Here's the same example that we've been discussing above. Cool?

I think this looks really good.

>@amanda-phet Where did you get the screenshot in #53 (comment)? That's not what I see with the functions shown. What I see is shown below, very different. 

I created the equation by first creating this one, 
<img width="894" alt="screen shot 2016-06-06 at 4 30 33 pm" src="https://cloud.githubusercontent.com/assets/7852916/15840749/3b1d8e6a-2c09-11e6-8336-3faeed63d7cd.png">

then replacing •-1 with ÷3 by dragging up and substituting the function pieces. 
<img width="908" alt="screen shot 2016-06-06 at 4 30 41 pm" src="https://cloud.githubusercontent.com/assets/7852916/15840755/40c0ddcc-2c09-11e6-8927-d3303eecdc11.png">

**Comment by pixelzoom** [comment]
Got it, thanks @amanda-phet .  Your example had a division by -3, mine was division by +3, that's why they were different.
