### ISSUE TITLE
[Edge] dashed outline of ghost cards is obscured

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#56]
Reported by @phet-steele in #30, factored out into a separate issue since this is apparently a different bug.  Original report below.

---

(5) An artifact is more than likely left behind after using the second card of an input, hence why the ghost state of the input has an obscured dashed outline:
![funbu05](https://cloud.githubusercontent.com/assets/5863899/15188481/388c138e-1763-11e6-829b-a5cc1d70cbf6.gif)

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.25/function-builder_en.html
Version: 1.0.0-dev.25 2016-05-05 18:36:48 UTC
Features missing: touch
Flags: pointerEnabled
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Language: en-US
Window: 1600x746
Pixel Ratio: 1/1
WebGL: WebGL 0.95
GLSL: WebGL GLSL ES 0.95
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"5e33541f","branch":"master"},"babel":{"sha":"b461c809","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"184674ba","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"function-builder":{"sha":"3d4fe673","branch":"master"},"joist":{"sha":"48836bcf","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"7590be09","branch":"master"},"scenery-phet":{"sha":"436bf61d","branch":"master"},"sherpa":{"sha":"ab4d5c14","branch":"master"},"sun":{"sha":"9f2d40d5","branch":"master"},"tandem":{"sha":"5af5b8f8","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery/issues/546#issuecomment-223200907, @jonathanolson said:
> Will handle the number-5 case in that issue separately, as it appears to be a separate bug, and may be fixed by the Canvas work that is in progress.

What is the scenery issue number?

**Comment by jonathanolson** [comment]
Will check to see if this is a problem after the implementation for https://github.com/phetsims/scenery/issues/518.

**Comment by pixelzoom** [comment]
In Skype, @jonathanolson said:

[6/6/16, 9:10:43 PM] Jonathan Olson: The backup would presumably be to try SVG out on Edge
[6/6/16, 9:10:57 PM] Jonathan Olson: That's one thing we could try now (see how ?rootRenderer=svg works on Edge)

**Comment by jonathanolson** [comment]
Latest Scenery commit (https://github.com/phetsims/scenery/commit/768bf4537826a6bbda1ad6fc548883bc8b905179) appears to fix this. @phet-steele, can you verify?

**Comment by phet-steele** [comment]
@jonathanolson verified fixed on the original device.

**Comment by pixelzoom** [comment]
I don't have an Edge test platform, and don't have time to set one up.  So I'll take @phet-steele's word for it and close this issue.
