### ISSUE TITLE
should table drawer be closed by default?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#58]
In https://github.com/phetsims/tasks/issues/604#issuecomment-222723912 (preliminary interviews), @amyh-phet observed:
> It seems to take students a while to realize the output carousel updates when they change a function.

So the relationship between items in the input and output carousels may take a little effort to figure out.

The table orders things differently than the carousel.  And according to the design doc, the table drawer is supposed to be open by default.  Might that make it more difficult to determine the relationship between items in the input and output carousels?  Should we consider making the table drawer closed by default?

**Comment by ariel-phet** [comment]
I would certainly be fine with the drawer close by default

**Comment by pixelzoom** [comment]
It's now closed by default.  @amanda-phet let me know if you have a strong feeling to the contrary.  Otherwise please close this issue.

**Comment by amanda-phet** [comment]
That's fine, but I'd want to make sure in the next interviews that students find the drawers since they will all be closed on startup.
