### ISSUE TITLE
requirements for Mystery screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#60]
The design document contains no notes on our discussion of the new "Mystery" screen.  My memory of what the "function selection grid" contains has already proven to be different than @ariel-phet's.  And some important things were not decided (what's in the carousels, which drawers are present, ...)  So this issue will serve to nail down the requirements.

**Comment by pixelzoom** [comment]
This comment enumerates the requirements that are needed.

Function selection grid:
• what does it look like?
• where is it located?
• what does it contain?
• what static (non-random) functions does it contain?
• what "random generators" does it contain?
• how do the "random generator" items behave? (animation, etc.)

Functions:
• What do functions look like in the builder? Colored background with "?"
• For randomly generated scenarios, do we simply randomly generate colors (with no duplicates)? Or do we pick from a pre-determined set of accessible colors?

Functionality from other screens:
• What cards are in the input carousel?  [-4,6]? Is "x" included?
• What cards are displayed by default in the input carousel? [0,3]?
• Is the "see inside" check box present?
• Is the "hide functions" check box present? (probably not, since these are all mystery functions)
• Is the eraser button present below the output carousel?
• Is the table drawer present?
• Is the graph drawer present?
• Is the equation drawer present? Does it overlap the "function selection grid"?

**Comment by pixelzoom** [comment]
Labeled as "top priority".  If this screen has any hope of being included in 1.0 release, requirements specification by 6/10/16.

**Comment by ariel-phet** [comment]
My thoughts:

3 "static" mystery functions. A single, a double, and then a triple. These would basically be buttons...you press them and the mystery function appear in the builder (so that we don't have to deal with putting a double function in a carousel). 

Next there would be 3 "random" mystery functions. Again a single, a double, and then a triple, with some sort of generate button. 

So basically a grid of 6

"see inside" check box definitley not present (that sort of defeats the purpose of double or triple mystery functions)

Others are all good questions and should be discussed with @amanda-phet

**Comment by pixelzoom** [comment]
I don't see much point in having the "hide functions" check box for mystery functions.

**Comment by amanda-phet** [comment]
>I don't see much point in having the "hide functions" check box for mystery functions. 

I agree. This screen will be a much simpler version of the Equations screen. I'm working on a mockup today and hope to discuss tomorrow at design meeting.

**Comment by amanda-phet** [comment]
I have copied and pasted your questions into the design doc as a place to add answers and mockups. Once we have all questions answered I can add them back here to this issue.

**Comment by pixelzoom** [comment]
You don't need to paste answers back into this issue, you can just paste a link to the section in the design doc.

**Comment by pixelzoom** [comment]
FYI, I'm planning to do a "sprint" on the Mystery screen this afternoon, based on my best guess of what the requirements will be.

**Comment by amanda-phet** [comment]
https://docs.google.com/document/d/1S6pkoJODPNZFtkLaSmk2MKzh2aAH6lk30pqCTxTX8z8/edit#heading=h.ie707iinqicg 

New design question: How will the user know that they have a new set of randomly generated functions? Randomly selected colors, as @pixelzoom suggested? What if a color looks similar to one of the pre-set mystery functions? Maybe those should be shades of gray?

**Comment by pixelzoom** [comment]
Most of the requirements were hashed out in 6/9/16 design meeting, see the design doc.  Assigning to me.

**Comment by pixelzoom** [comment]
Email from @amanda-phet on 6/14/16:

Hi Chris, 

Beth narrowed the functions down to 148 possible combinations. Her spreadsheet is here: https://docs.google.com/spreadsheets/d/1leVeZl6LgXkXR4Khjk_j6LRp3OECaivzqIq82PaY0wE/edit?pli=1#gid=0 

What form would be useful for you to have these mystery combinations?

Also, let me know if you think a design meeting would be useful for this week. 

Thanks, 
Amanda

**Comment by pixelzoom** [comment]
Work on this issue is proceeding in the design doc, and the Mystery screen is mostly implemented. So I'm closing this issue.
