### ISSUE TITLE
Patterns screen icon is out of sync with star icon

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#63]
In issue #34, we change the icon on the 'star' card so that it would rotate more predictably.  

Here's what it looks like now:

![screenshot_10](https://cloud.githubusercontent.com/assets/3046552/15914186/fd364332-2d9b-11e6-9731-cf77007fdc09.png)

Here's what it looks like after going through Warhol:

![screenshot_09](https://cloud.githubusercontent.com/assets/3046552/15914197/14c38a3c-2d9c-11e6-893b-129ea2b4cce5.png)

And here's the Patterns screen icon. It still looks like the old star because it's drawn using different code (not run through the actual Warhol function) so it looks good at the larger size needed by the home screen.

![screenshot_08](https://cloud.githubusercontent.com/assets/3046552/15914205/2484954c-2d9c-11e6-8941-264c575ee606.png)

So, options...

(1) Revise the code that draws the stars on the Patterns screen, so that it matches the new start. Advantage to this option is that it will look better than option 2.  Disadvantage is that if the star changes again in the future, this problem will occur again. 

(2) Draw the Patterns screen icon by actually passing using the Warhol function. If it's the star icon, it will look a little crappy.  One of the other icons might looks less crappy, hard to say which one would be best.  Advantage of this approach is that it won't get out of sync again in the future.  Disadvantage is that it won't look as good as option 1.

@amanda-phet @ariel-phet Which option would you prefer?

**Comment by amanda-phet** [comment]
I was not aware of this change to the star input... can someone please explain why there is a circle around the star? Adding a circle does nothing to change the symmetry of the shape, so I'm not sure how a rotation looks any different. 

I looked in past issues but do not see one about this input.

**Comment by pixelzoom** [comment]
See issue https://github.com/phetsims/function-builder/issues/63.

**Comment by pixelzoom** [comment]
I updated the code that draws the Patterns screen icon in https://github.com/phetsims/function-builder/commit/c98bc89300556e2230a6580c42e0646642fcdd45.  Here's what it looks like now:

![screenshot_11](https://cloud.githubusercontent.com/assets/3046552/15914655/ef0d8fc8-2d9f-11e6-9e69-3271953fe2dd.png)

Still open to doing something else.

**Comment by pixelzoom** [comment]
Actually... Looks kind of lousy with those circles around the stars.  That's fine for the general star icon, but maybe we want to use a different icon on the home screen.  Butterfly?

**Comment by phet-steele** [comment]
My vote is for the famous C > C > Warhol! :wink:

**Comment by pixelzoom** [comment]
@phet-steele The question is which card icon to use, not which function to apply.

**Comment by phet-steele** [comment]
@pixelzoom it was a joke, to say to make the image using the butterfly after applying those functions. Clearly, that would not be a good choice!

**Comment by pixelzoom** [comment]
Yep, I got the joke. I just wanted to make sure that the others watching this issue don't get distracted :)

**Comment by ariel-phet** [comment]
I say definitely stick with Warhol as the function, but @amanda-phet you should choose the input you want.

**Comment by pixelzoom** [comment]
The best looking image will be one that doesn't have many obviously line (especially straight lines). That's why I suggested the butterfly - it's pretty "noisy" to begin with, so addition artifacts won't be as obvious.

**Comment by pixelzoom** [comment]
Here's the Patterns icon using the butterfly, and actually running it through the Warhol function:

![screenshot_14](https://cloud.githubusercontent.com/assets/3046552/15936517/91a28a94-2e28-11e6-8d3d-810d58c51165.png)

**Comment by pixelzoom** [comment]
I should also note that the above uses a higher-res version of the butterfly image, which adds ~16K to the uncompressed payload (which is relatively insignificant before and after compression).  I currently have the butterfly checked into master, but we can use any of the card images - some will obviously look better than others, as noted in https://github.com/phetsims/function-builder/issues/63#issuecomment-224938054.

**Comment by pixelzoom** [comment]
@amanda-phet To make your life easier, here are all 12 cards run through Warhol. Pick the one that you think would look best for the Patterns screen icon.

![warhol-cards](https://cloud.githubusercontent.com/assets/3046552/15937205/2645aada-2e2b-11e6-93d9-ea2c478b99c6.png)

**Comment by pixelzoom** [comment]
Something else I just noticed...  If you pick one of the icons that has a "portrait" orientation (taller than it is wide), then you'll end up with a lot of blank space on the left and right of the home screen icon.  This would be an issue with (for example) the stick figure or beaker.

**Comment by pixelzoom** [comment]
Eg, with the stick figure:

![screenshot_20](https://cloud.githubusercontent.com/assets/3046552/15937334/afc9f694-2e2b-11e6-94f8-6f1f4c145e94.png)

**Comment by pixelzoom** [comment]
Eg, with the stick figure:

![screenshot_20](https://cloud.githubusercontent.com/assets/3046552/15937334/afc9f694-2e2b-11e6-94f8-6f1f4c145e94.png)

So another plus for the butterfly is that is has almost the same aspect ratio as the home screen icons, so it fill more of the icon.

**Comment by amanda-phet** [comment]
The butterfly looks great! Let's use that one.

**Comment by pixelzoom** [comment]
Great, glad you like it, closing.
