### ISSUE TITLE
Outputs in table when there exist no outputs

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#64]
Outputs can be displayed in the table even when no cards occupy the output carousel. This is both the Numbers and Equations screen. Requirements to do so:

1. Start with the table closed
2. Check see inside
3. Put some cards into the function machine. Do not let them enter the output carousel
4. Open the drawer, and outputs will be shown!

![fb01](https://cloud.githubusercontent.com/assets/5863899/15947948/6de9f83e-2e5b-11e6-97bf-54f1957cbff4.gif)

Some caveats & additional notes:

- Step 3 is important in regards to not letting a card reach the output carousel. If a card does, then it's output will correctly not be shown in the carousel
- If a card enters the output carousel, it must be returned completely to the input carousel, then back to the function machine, in order to see this bug
- Functions being in the machine does not matter at all.
- Outputs will be shown for any amount of cards currently inside the function machine when the table drawer is open
- Outputs are not displayed in the graph
- Outputs are at least calculated correctly (and as if all functions were applied to the input), and update while changing the function

Seen on OSX 10.11.5 Chrome. For phetsims/tasks#613.
Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.48/function-builder_en.html
Version: 1.0.0-dev.48 2016-06-09 21:13:13 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Language: en-US
Window: 1920x962
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"728956f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"4c679115","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"function-builder":{"sha":"ebab2b1f","branch":"master"},"joist":{"sha":"ddf0d912","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"533a56b5","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
@phet-steele Good catch, fixed in above commit, feel free to confirm by pulling master.

**Comment by phet-steele** [comment]
@pixelzoom, confirmed.

**Comment by pixelzoom** [comment]
First published in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.49/function-builder_en.html
