### ISSUE TITLE
Odd layout of "Output = 0" equation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#65]
On the Numbers screen, if ever the equation drawer would read "Output = 0", enabling the slope-intercept checkbox makes the equation display as so:

![screen shot 2016-06-09 at 3 42 50 pm](https://cloud.githubusercontent.com/assets/5863899/15947510/0f6be8f0-2e59-11e6-8dec-787ad3f3e6bd.png)

Nothing special to this issue, sim state doesn't matter.

Seen on OSX 10.11.5 Chrome. For phetsims/tasks/issues/613.
Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.48/function-builder_en.html
Version: 1.0.0-dev.48 2016-06-09 21:13:13 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Language: en-US
Window: 1920x962
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"728956f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"4c679115","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"function-builder":{"sha":"ebab2b1f","branch":"master"},"joist":{"sha":"ddf0d912","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"533a56b5","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
Fixed in above commit, feel free to verify by pulling master. Here's what it looks like:

![screenshot_155](https://cloud.githubusercontent.com/assets/3046552/15948912/d3399e38-2e60-11e6-9f8e-548756d2cf84.png)

**Comment by phet-steele** [comment]
@pixelzoom, verified.

**Comment by pixelzoom** [comment]
First published in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.49/function-builder_en.html
