### ISSUE TITLE
[Safari] fails to start the first time

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#66]
On Safari desktop, version 1.0.0.-dev.47 and 1.0.0.-dev.48 fails to start the first time. You'll see the "Loading..." screen, followed by a completely black window.  Reloading the page starts the sim successfully.

Here's the console error:

```
TypeError: Type error    createLinearGradient - LinearGradient.js:36
```

... which points to LinearGradient, line 36:

```js
Gradient.call( this, scenery.scratchContext.createLinearGradient( x0, y0, x1, y1 ) );
```

No call stack, so I added this debug code immediately before the above statement:

```js
console.log( x0 + ' ' + y0 + ' ' + x1 + ' ' + y1 );
if ( isNaN( x0 ) || isNaN( y0 ) || isNaN( x1 ) || isNaN( y1 ) ) {
  debugger;
}
```
...which prints `0 0 NaN 0`.

Call stack:

![screenshot_154](https://cloud.githubusercontent.com/assets/3046552/15948041/de2ea522-2e5b-11e6-8c49-69afabc93347.png)

Looks like a problem with one of the screen icons having a height of `NaN`. I did just "tweak" the icons, and I'll bet that the culprit is issue https://github.com/phetsims/function-builder/issues/63.

**Comment by pixelzoom** [comment]
@phet-steele FYI, since this bug is present in the version that I gave you for dev testing in https://github.com/phetsims/tasks/issues/613

**Comment by pixelzoom** [comment]
The problem is indeed due to the change to the Patterns screen (#63).  Here's the code that creates that screen's icon, in FBIconFactory:

```js
    createPatternsScreenIcon: function() {

      var warhol = new Warhol();
      var inputCanvas = FBCanvasUtils.createCanvasWithImage( butterflyHiRes );
      var outputCanvas = warhol.apply( inputCanvas );
      var iconNode = new Image( outputCanvas.toDataURL() );

      return new ScreenIcon( iconNode, { fill: FBColors.PATTERNS_SCREEN_BACKGROUND } );
    },
```

If I change to this, the problem goes away:

```js
    createPatternsScreenIcon: function() {
      var iconNode = new Rectangle( 0, 0, 100, 100, { fill: 'red' });
      return new ScreenIcon( iconNode, { fill: FBColors.PATTERNS_SCREEN_BACKGROUND } );
    },
```

**Comment by pixelzoom** [comment]
Adding debug output to `createPatternsScreenIcon`:

```js
console.log( 'width=' + butterflyHiRes.width + ' height=' + butterflyHiRes.height );//XXX
var inputCanvas = FBCanvasUtils.createCanvasWithImage( butterflyHiRes );
```

... prints `width=499 height=344`, which is the correct size of butterfly-hires.png.

**Comment by pixelzoom** [comment]
More debug output:

```js
createPatternsScreenIcon: function() {

      var warhol = new Warhol();
      console.log( 'butterflyHiRes width=' + butterflyHiRes.width + ' height=' + butterflyHiRes.height );
      var inputCanvas = FBCanvasUtils.createCanvasWithImage( butterflyHiRes );
      console.log( 'inputCanvas width=' + inputCanvas.width + ' height=' + inputCanvas.height );
      var outputCanvas = warhol.apply( inputCanvas );
      console.log( 'outputCanvas width=' + outputCanvas.width + ' height=' + outputCanvas.height );
      var iconNode = new Image( outputCanvas.toDataURL() );
      console.log( 'iconNode width=' + butterflyHiRes.width + ' iconNode=' + butterflyHiRes.height );

      return new ScreenIcon( iconNode, { fill: FBColors.PATTERNS_SCREEN_BACKGROUND } );
    },
```

... prints:

```
[Log] butterflyHiRes width=499 height=344 (FBIconFactory.js, line 55)
[Log] inputCanvas width=499 height=344 (FBIconFactory.js, line 57)
[Log] outputCanvas width=499 height=344 (FBIconFactory.js, line 59)
[Log] iconNode width=499 iconNode=344 (FBIconFactory.js, line 61)
```

**Comment by pixelzoom** [comment]
Explicitly specifying `initialWidth` and `initialHeight` fixes the problem:

```js
      var iconNode = new Image( outputCanvas.toDataURL(), {
        initialWidth: outputCanvas.width,
        initialHeight: outputCanvas.height
      } );
```

I'll check this in, but I don't understand what's going on. @jonathanolson can you explain?

**Comment by pixelzoom** [comment]
Is it because of where this occurs in the startup sequence? `FBIconFactory.createPatternsScreenIcon` is called in `PatternsScreen` constructor, which is called from `function-builder-main.js`.

**Comment by jonathanolson** [comment]
Potential typo in console.logs. I see:
```js
      var iconNode = new Image( outputCanvas.toDataURL() );
      console.log( 'iconNode width=' + butterflyHiRes.width + ' iconNode=' + butterflyHiRes.height );
```
seems to be logging butterflyHiRes.width, whereas I would expect iconNode's bounds to be empty. Including initial dimensions should fix it.

**Comment by pixelzoom** [comment]
> Potential typo in console.logs.

Ah, indeed, sorry about that.

> I would expect iconNode's bounds to be empty

Why?

**Comment by pixelzoom** [comment]
Fix published in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.49/function-builder_en.html.

@phet-steele Can you please verify?

**Comment by pixelzoom** [comment]
@jonathanolson said:
> I would expect iconNode's bounds to be empty

I asked:
> Why? What is different about this situation?

More verbosely... In https://github.com/phetsims/function-builder/issues/15, we determined that we can rely on images having been loaded if the code that uses the images is in the callback to `SimLauncher.launch`.  And that is the case here - `PatternsScreen` constructor is called in the callback (see function-builder-main.js), then `FBIconFactory.createPatternsScreenIcon` is called in `PatternsScreen` constructor.  

So is the issue that the image is not available yet? Or that one of the canvas operations hasn't completed? Or that `canvas.toDataURL` is for some reason incorrect?.... I'd like to understand for future reference why I needed to specify initialWidth and initialHeight in this particular case.

**Comment by phet-steele** [comment]
@pixelzoom 1.0.0-dev.49 loads for me.

**Comment by pixelzoom** [comment]
Thank you @phet-steele.

This issue can be closed after @jonathanolson clarifies https://github.com/phetsims/function-builder/issues/66#issuecomment-225231906, after which I may update documentation in FBIconFactory.

**Comment by pixelzoom** [comment]
Following up on my documentation question in https://github.com/phetsims/function-builder/issues/68. 

Closing this issue.
