### ISSUE TITLE
Card images randomly relocate and resize

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/function-builder#67]
Test device: Lenovo Thinkpad w540, iPad Air 2

Operating System: Microsoft Windows 7 (Version 6.1.7601) and iOS 9.3.2

Browser: FF 46.0.2 & Safari 601.1

Problem description: Images on the cards in the output carousel sometimes become smaller and relocate to the bottom right corner of the card, like so:
![img_0044](https://cloud.githubusercontent.com/assets/7988696/15973480/e17804f8-2f00-11e6-9e46-ba8ef8c79377.jpg)

Steps to reproduce: This can happen with any number of cards in the output area - four, three, two, and one cards were tested. 
It has also been seen to happen when you open the sim, drag a card over, without using any functions.
It has been seen to happen when functions are dragged up. Seems to sometimes happen when you use a function you haven't used before. 

For phetsims/tasks#613

Troubleshooting information (do not edit):
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.48/function-builder_en.html
Version: 1.0.0-dev.48 2016-06-09 21:13:13 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Language: en-US
Window: 1280x590
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"b71cc337","branch":"master"},"babel":{"sha":"728956f3","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"4c679115","branch":"master"},"dot":{"sha":"9b554e82","branch":"master"},"function-builder":{"sha":"ebab2b1f","branch":"master"},"joist":{"sha":"ddf0d912","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"533a56b5","branch":"master"},"scenery-phet":{"sha":"cc33f674","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"f2631eea","branch":"master"},"tandem":{"sha":"b3c68afa","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by phet-steele** [comment]
@pixelzoom here's an image from my FF on OSX 10.11.5. As you can see, there's a lot going on here:

<img width="1599" alt="screen shot 2016-06-10 at 11 51 24 am" src="https://cloud.githubusercontent.com/assets/5863899/15973909/f7fb93dc-2f02-11e6-931f-97aeb3d1fed8.png">

**Comment by phet-steele** [comment]
@pixelzoom I can't manage to make this happen on Chrome.

**Comment by pixelzoom** [comment]
Is the problem always in the output carousel? Or do you see this with any cards as you're dragging them around?

**Comment by phet-steele** [comment]
Also while dragging, but only after leaving the machine as an output. All inputs look normal.

**Comment by pixelzoom** [comment]
Images are centered on the cards.  If an image isn't yet ready when the centering occurs, then its width and height will be zero, and the card's "center" will be (0,0), it's upper-left corner.  

Reproduced in latest (1.0.0-dev.49 and master) with FF 47.0 on Mac OS X 10.11.5:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.49/function-builder_en.html
You need to restart FF each time to reproduce.

I cannot reproduce this problem in this dev version, which was published before changes to scenery.Image in https://github.com/phetsims/scenery/issues/548:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.47/function-builder_en.html

Removing these 2 lines that were added to Image.setImage makes the problem go away:

```js
228   this._initialWidth = 0;
229   this._initialHeight = 0;
```

My guess is that this change to `Image.setImage` was either not tested with `canvas.toDataURL()` arg, or did something to break `Image.setImageWidthSize`. @jonathanolson I'm reopening https://github.com/phetsims/scenery/issues/548

**Comment by pixelzoom** [comment]
Happens immediately in this version on FF:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.49/function-builder_en.html

Fix in this version - the only thing different is that I rolled back phetsims/scenery#548:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.50/function-builder_en.html

@phet-steele please verify.  Close if it looks OK, thanks.

**Comment by phet-steele** [comment]
@pixelzoom issue is not present after the rollback.
