### ISSUE TITLE
revisit workaround for iOS rendering bug

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#69]
A workaround was added to `SceneNode` to address https://github.com/phetsims/function-builder/issues/35. After lots of trial and error, I discovered that using `renderer: 'canvas'` for the `controlsLayer` makes the problem disappear.  No idea why this works.  Consider revisiting in the future. 

The relevant code in `SceneNode` is:

```js
38 //TODO revisit this workaround, see https://github.com/phetsims/function-builder/issues/69
39 var WORKAROUND_35_OPTIONS = platform.mobileSafari ? { renderer: 'canvas' } : {};

78 var controlsLayer = new Node( WORKAROUND_35_OPTIONS );
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/function-builder/issues/147#issuecomment-1135117675, @jessegreenberg identified this workaround (the use of `renderer: 'canvas'` specifically) as causing a performance problem with pan/zoom on iPad Air 2.  So I'm going to attempt to remove the workaround, to see if it resolves https://github.com/phetsims/function-builder/issues/147.

**Comment by pixelzoom** [comment]
To potentially address #147, the workaround was removed in the above commit. 

@KatieWoe please test (1.2.0-dev.8)[https://phet-dev.colorado.edu/html/function-builder/1.2.0-dev.8/phet/function-builder_en_phet.html], to verify that the problem originally reported in #35 has not returned.  Unfortunately the movie that demonstrated #35 seems to be lost. But basically, dragging a card through the builder would sometimes leave a white path behind the card, around the edges of the builder.

**Comment by pixelzoom** [comment]
So now the sim is totally unresponsive on iPad Air 2?  I can't explain that.  The only changes between 1.2.0-dev.7 and 1.2.0-dev.8 were:

* https://github.com/phetsims/function-builder/commit/ee7f34bd49594bd12953acf46e68956058e398ef - removed workaround use of `renderer: 'canvas'` in SceneNode.js
* https://github.com/phetsims/function-builder/commit/652022afda8745e12b7ccb8d5fab7cf571607507 - added `preventFit: true` to FBScreenView.js

@jonathanolson thoughts?

**Comment by pixelzoom** [comment]
I got on Zoom with @KatieWoe.  The iPad Air 2 must have been in some weird state.  After restarting the browser (and iPad?) the sim loads an is responsive.  So @KatieWoe will continue with verifying this issue.

**Comment by KatieWoe** [comment]
Boxes did not seem to show up. In addition, while the screenshots were a bit slow, they seemed faster and I didn't see the crashing/freezing behavior. As long as https://github.com/phetsims/function-builder/issues/69#issuecomment-1137706620 was just a one off I'd say this fix looks better.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.  We'll proceed with this change for FB 1.2.

**Comment by pixelzoom** [comment]
To verify in 1.2.0-rc.1, test on iPad, and verify that you don't see the problem pictured in https://github.com/phetsims/function-builder/issues/69#issuecomment-1137645258, and described in #35.

**Comment by KatieWoe** [comment]
I am not seeing the issue from https://github.com/phetsims/function-builder/issues/35. However, unlike what I said in https://github.com/phetsims/function-builder/issues/69#issuecomment-1137794483, I did manage to get a crashing behavior with the screenshot. However, it took many more tries to replicate.

**Comment by KatieWoe** [comment]
Closing unless this comes up again.

**Comment by pixelzoom** [comment]
Just to clarify... This issue deals only with the graphics artifacts caused by dragging cards, and it sounds like that is no longer a problem.  The screenshot crash is being tracked in https://github.com/phetsims/function-builder/issues/148.  @jonathanolson is investigating. We may delay FB 1.2 until he addresses it.  Or we may publish FB 1.2 with that known problem, then address it in an MR.  That will be someone else’s call (probably @kathy-phet).
