### ISSUE TITLE
challenges for Mystery screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#71]
The challenges (function combinations) for the Mystery screen are specified in https://docs.google.com/document/d/1S6pkoJODPNZFtkLaSmk2MKzh2aAH6lk30pqCTxTX8z8/edit#heading=h.ie707iinqicg
 
In 6/16/16 design meeting, we decided that we would not use negative operands with plus and minus operators (e.g. `+ -2` or `- -1`). This rules out many of the challenges in the spreadsheet - which has not been updated. I went through and used 'red' font to indicate challenges that are no longer valid. This dev version contains all of the challenges that are still valid:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.61/function-builder_en.html

Here's a link that will show you the answer (`?showAnswer`) and cycle through the challenges in the order that they appear in the pool (`?playAll`):

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.61/function-builder_en.html?showAnswer&playAll

Reset All is a bit broken in this dev version, so please reload the sim if you need to start over.

I suspect that the challenges need refinement.  What I need, for each of the 3 pools, is:

1. Revised challenges
2. Indication of which challenge is displayed on startup and Reset All.

The format used in the spreadsheet was very difficult to transfer to Javascript. So I'll ask you to please provided challenges in a format that I use directly.  Here are the pools, as they currently appear in the code. Each challenge is a string of operators and operands, separated by spaces.   The first challenge in the pool is used on startup and Reset All.

```js
  // 1-function challenges
  POOL1: [
    '+ 3', // selected on startup and reset
    '+ 2',
    '+ 1',
    '+ 0',
    '- 3',
    '- 2',
    '- 1',
    '- 0',
    '* 3',
    '* 2',
    '* 1',
    '* 0',
    '* -1',
    '* -2',
    '* -3',
    '/ 3',
    '/ 2',
    '/ 1',
    '/ -1',
    '/ -2',
    '/ -3'
  ];

  // 2-function challenges
  POOL2: [
    '+ 1 + 3', // selected on startup and reset
    '+ 1 + 2',
    '* 2 * 0',
    '* 0 * 1',
    '* -1 * -2',
    '* 2 * 1',
    '* -3 * 2',
    '* 2 * -3',
    '* 3 + 3',
    '* 2 + 3',
    '* 2 - 2',
    '* 1 + 3',
    '* 1 + 2',
    '/ 1 - 1',
    '* 0 + 3',
    '* -3 + 0',
    '/ 3 - 3',
    '/ 3 + 2',
    '/ -1 - 3',
    '/ -2 + 2',
    '+ 3 * 3',
    '- 3 * 2',
    '+ 2 * 2',
    '+ 3 * 1',
    '+ 2 / 1',
    '- 1 * 1',
    '+ 3 * 0',
    '+ 0 * -3',
    '- 3 / 3',
    '- 2 / 3',
    '+ 3 / -1',
    '+ 2 / -1'
  ],

  // 3-function challenges
  POOL3: [
    '* -3 * -1 * 0', // selected on startup and reset
    '* 3 * -2 * -1',
    '* 2 * -2 * -2',
    '/ 3 / -1 / -1',
    '/ 2 / 3 / -2',
    '/ 1 / -1 / 2',
    '* 3 * -3 + 3',
    '/ 2 * 2 - 2' ,
    '+ 3 * 1 + 3',
    '+ 2 * 1 + 2',
    '- 1 / 1 - 1',
    '+ 3 * 0 + 3',
    '+ 2 * -2 + 3',
    '+ 0 * -3 + 0',
    '- 3 / 3 - 3',
    '- 2 / 3 + 2' ,
    '+ 3 / -1 - 3',
    '+ 2 / -2 + 2',
    '* -3 + 3 + 3',
    '/ 3 - 3 - 3',
    '* 0 + 2 + 2',
    '* 3 + 3 * 1',
    '/ 2 + 2 / 1',
    '/ 2 - 1 * 1',
    '* -2 + 3 * 0',
    '* 2 + 3 * -2',
    '* 1 + 0 * -3',
    '* 0 - 3 / 3',
    '* -1 - 2 / 3',
    '* 0 + 3 / -1',
    '* 1 + 2 / -1'
  ]
```  

Assigning to @amanda-phet to decide who will do this. Labeled as "top priority" since this seems important to complete before 6/29/16 interviews (see https://github.com/phetsims/tasks/issues/625.)

**Comment by pixelzoom** [comment]
I've edited the above comment to show all 3 pools, as they are currently implemented.

**Comment by pixelzoom** [comment]
@amanda-phet I see that you've added @bethstade to the list of assignees. Does that mean that she is responsible for this? What is the deadline?

**Comment by pixelzoom** [comment]
A thought... Perhaps instead of enumerating specific challenges, we should enumerate the order of operators that are desired. Then randomly generate operands from the range of valid values for each operator. 

For example, "+ N * M" may be a desired order of operations for the 2-function challenges, where N is [0,3] and M is [-3,3].

**Comment by pixelzoom** [comment]
+ : [0,3]
- : [0,3]
* : [-3,3]
/ : [-3,-1],[1,3]

**Comment by amanda-phet** [comment]
I assigned @bethstade so she could also weigh in. 

The benefit of creating a pool is that we could have more "*M +N" challenges than "+N *M", so my next comment will include modified pools of 2 and 3.

**Comment by amanda-phet** [comment]
// pool of 2-function challenges
  var POOL2 = [
    '+ 1 * 2', // this challenge is always selected on startup and reset
    '+ 1 + 3', 
    '+ 1 + 2',
    '* 2 * 0',
    '* 0 * 1',
    '* -1 * -2',
    '* -3 * 2',
    '* 3 + 3',
    '* 2 + 3',
    '* 2 - 2',
    '* 3 - 1',
    '* -3 + 0',
    '* -2 + 1’,
    '* 1 + 3',
    '* 1 - 2',
    '* 0 + 3',
    '* 0 - 2’,
    '/ 1 - 1',
    '/ 3 - 3’,
    '/ 3 + 2',
    '/ -1 - 3',
    '/ -2 + 2',
    '+ 3 * 3',
    '- 1 * 3’,
    '+ 2 * 2',
    '+ 3 * 1',
    '+ 2 / 1',
    '+ 3 * 0',
    '+ 0 * -3',
    '- 3 / 2’,
    '- 2 / 3',
    '+ 3 / -1'
];

**Comment by amanda-phet** [comment]
// pool of 3-function challenges
  var POOL3 = [
    '+ 2 * 1 + 2', // this challenge is always selected on startup and reset
    '* -3 * -1 * 0', 
    '* 3 * -2 * -1',
    '* 2 * -2 * -2',
    '/ 3 / -1 / -1',
    '/ 2 / 3 / -2',
    '/ 1 / -1 / 2',
    '* 3 * -3 + 3',
    '/ 2 * 2 - 2' ,
    '+ 3 * 1 + 3',
    '- 1 / 1 - 1',
    '+ 3 * 0 + 3',
    '+ 2 * -2 + 3',
    '+ 0 * -3 + 0',
    '+ 1 - 3 * 2',
    '- 3 / 3 - 3',
    '- 2 / 3 + 2' ,
    '+ 3 / -1 - 3',
    '+ 2 / -2 + 2',
    '* -3 + 3 + 3',
    '/ 3 - 3 - 3',
    '* 0 + 2 + 2',
    '* 3 + 3 * 1',
    '/ 2 + 2 / 1',
    '/ 2 - 1 * 1',
    '* -2 + 3 * 0',
    '* 1 + 0 * -3',
    '* 0 - 3 + 3',
    '* -1 - 2 / 3',
    '* 0 + 3 / -1',
  ];

**Comment by pixelzoom** [comment]
POOL1 is OK as is?

POOL2 and POOL3 revised in 1.0.0-dev.63:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.63/function-builder_en.html

Run with `?playAll&showAnswer` to play all challenges with answer visible:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.63/function-builder_en.html?playAll&showAnswer

**Comment by bethstade** [comment]
This is Amanda's call.
I got the list started, but I defer to her judgement.
I am out of town for 2 weeks, but will try to jump in when I can.
Thanks,
Beth

----- Original Message -----From: Amanda McGarry <notifications@github.com>To: phetsims/function-builder <function-builder@noreply.github.com>Cc: bethstade <stadee@colorado.edu>, Mention <mention@noreply.github.com>Sent: Wed, 22 Jun 2016 15:11:46 -0000 (UTC)Subject: Re: [phetsims/function-builder] challenges for Mystery screen (#71)

Assigned #71 to @bethstade.
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by amanda-phet** [comment]
>POOL1 is OK as is? 

Yes.

**Comment by pixelzoom** [comment]
6/23/16 design meeting: Everything good here, closing.
