### ISSUE TITLE
Mystery screen has a blank space in card carousels

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#72]
We decided that the cards in the Mystery screen would have range [-4,6], and there would be no 'x' card. This leaves a blank space in the carousel, as shown in the screenshot below.  This bugs me a little, and I wonder if it will be distracting/problematic.  I'm creating this issue so that we take a look at this, and make a conscious decision to leave it as is or do something about it.

Dev version that demonstrates this is:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.61/function-builder_en.html

![blank](https://cloud.githubusercontent.com/assets/3046552/16250012/436c3966-37d7-11e6-9764-9a106a89b952.png)

**Comment by amanda-phet** [comment]
I have this as an agenda item for 6/23's design meeting. I personally do not mind the blank space. It's clearly the space where x was on the previous screen, and should be obvious to the user (or prompt a discussion about) why they can't use it here!

**Comment by pixelzoom** [comment]
Not saying we should do this... But if we added a '7' card, the largest y value is `7 + 3 * 3 * 3 = 90`.
It's trivial to customize the range of the graph, so for the "Mystery" screen we could use ranges x=[-8,8] and y=[-100,100].  This is demonstrated in this dev version, and it doesn't look too bad:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.64/function-builder_en.html

It would also be possible to use non-symmetrical ranges (eg, x=[-6,8] and y=[-80,100]) if you'd prefer to have the same number of grid lines as in the Equations screen.

**Comment by pixelzoom** [comment]
I added some code to the graph to verify that each point is in range.  Based on the current set of 3-function challenges, the y range used in the Numbers screen (y=[-90,90]) works for the Mystery screen as well.  So if we added a '7' card, we'd only need to adjust the x axis range -- either by increasing to [-8,8] or shifting to [-6,8]. 

That said... The safest thing would be to also adjust the y range, in case challenges are modified in the future.

**Comment by pixelzoom** [comment]
6/23/16 design meeting decisions:  
- it makes sense to add the '7' card to the Mystery screen, since the Numbers screen also has a '7' card. 
- use the same graph ranges and tick labels in both the Equations and Mystery screens 
- change the graph ranges to x=[-8,8] and y=[-100,100]
- change the y-axis tick labels to -50 and 50

Done in above commit.

Note to self: Some cleanup of options propagation still required.

**Comment by pixelzoom** [comment]
Work completed, closing.
