### ISSUE TITLE
should the "See Inside" feature be available for 1-slot builders?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#73]
We currently provide the "See Inside" check box only for builders that have more than 1 function slot.  For example in the "Patterns" screen, one scene has no "See Inside" feature:

![screenshot_39](https://cloud.githubusercontent.com/assets/3046552/16250316/b013c2c6-37d9-11e6-8da5-e217ed1a3519.png)

While the other scene does:

![screenshot_40](https://cloud.githubusercontent.com/assets/3046552/16250324/b825dc2e-37d9-11e6-9777-ed87a1b2ed57.png)

The rightmost "See Inside" window (regardless of the number for function slots in the builder) is always equivalent to what is shown in the output carousel. But we decided to include the rightmost window so that a card could be "parked" in there, and changes to the rightmost function could be made in close proximity to the card.  Why doesn't this same argument apply to 1-slot builders?  Shouldn't we provide the "See Inside" feature in that case for the same reason?  

Also... Both the "Patterns" and "Mystery" screens both have a 1-slot builder, and it's the first one the student encounters.  It may be less confusing to just introduce the "See Inside" feature right away, than to add/remove it when they switch scenes.

**Comment by amanda-phet** [comment]
I have this as an agenda item for 6/23's design meeting. Given how the see inside window currently functions, it probably makes sense to include it on the single builder. However I want a chance to explain why it was not originally designed to be there...

**Comment by pixelzoom** [comment]
6/23/16 design meeting:  For consistency, we decided to include the 'See Inside' feature for 1-slot builders, for the reasons cited in https://github.com/phetsims/function-builder/issues/73#issue-161567218.  Done in above commit. Closed.
