### ISSUE TITLE
add QA credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#74]
This sim currently doesn't show any QA credits in the About dialog.

**Comment by pixelzoom** [comment]
@ariel-phet @phet-steele Who should be listed in the QA section of the credits? Please provide names exactly as you want them to appear. Thanks.

**Comment by ariel-phet** [comment]
@phet-steele I think you know this better than me at this point!

**Comment by phet-steele** [comment]
Steele Dalton, Amanda Davis, Andrea Lin, Ben Roberts
