### ISSUE TITLE
confirm credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#76]
The current credits in the sim are shown below. QA credits were provided by @phet-steele in #74.  

@amanda-phet If credits look correct, please close this issue. Otherwise indicate what I should change, and assign back to me. Thanks.

![screenshot_158](https://cloud.githubusercontent.com/assets/3046552/16348531/6049ee62-3a10-11e6-8870-c283eb6f2744.png)

**Comment by ariel-phet** [comment]
@pixelzoom -- @samreid should be added to the credits in the "team" section

**Comment by pixelzoom** [comment]
@ariel-phet Sam Reid is in team credits, first name on the 2nd line.

**Comment by ariel-phet** [comment]
Indeed he is...I swear the first time I read that I did not see him, my mistake!

**Comment by amanda-phet** [comment]
We should credit Amy Hanson for interviews.

**Comment by pixelzoom** [comment]
@amanda-phet PhET's credits policy is to put someone in 1 section of the credits. I put Amy Hanson in the "Team" section because, in addition to interviews, she also pitched in on some artwork revisions.  Would you prefer that I move her to "Interviews"?

**Comment by amanda-phet** [comment]
Either way is fine, I didn't realize she had contributed to artwork.

**Comment by pixelzoom** [comment]
@amanda-phet @amyh-phet You currently share credit on the following icons: start.png, rotate90.png, rotate180.png.  The attribution (in license.json) reads: ```created by Amanda McGarry and Amy Hanson```

**Comment by amyh-phet** [comment]
@pixelzoom  and @amanda-phet    Given that I only made minor tweaks to the artwork, I'm thinking that I don't need to be credited for the artwork.  Happy to just be listed as a team member.

**Comment by pixelzoom** [comment]
@amyh-phet OK, I've removed your credits on the artwork.  Do you want to be listed under "Team" or "Interviews"?

**Comment by amyh-phet** [comment]
@pixelzoom    Since I was only involved in interviews, it would make sense for that to be where I'm given credit.  I know the other team members had much more contribution to the sim that I have.

**Comment by pixelzoom** [comment]
After all that... HTML5 sims don't have an "Interviews" credits category. According to @jbphet, a decision was long ago to fold this category into "Team".  So @amyh-phet you shall continue to be credited in "Team".

**Comment by jbphet** [comment]
For reference, here is the issue where simplifying the credits was discussed: https://github.com/phetsims/joist/issues/157.  In comment https://github.com/phetsims/joist/issues/157#issuecomment-56721253 @pixelzoom talks about removing the "Interviews" section and moving those people onto the "Team" section.

**Comment by pixelzoom** [comment]
The decision to remove the "Interviews" category was made in https://github.com/phetsims/joist/issues/157#issuecomment-55424134, I merely implemented it.
