### ISSUE TITLE
Docs in RationalNumber

### ISSUE THREAD

**Issue by andrewadare** [phetsims/function-builder#78]
Functions like [plus](https://github.com/phetsims/function-builder/blob/58e10dfcb1fa1a5554ab231a1c0ef92823a592ef/js/common/model/RationalNumber.js#L68-L72) could use documentation.

I see that the file is marked with a TODO for relocation; apologies for jumping the gun if adding docs for this is already on your list.

**Comment by pixelzoom** [comment]
Related to #55 (code review).

**Comment by pixelzoom** [comment]
Documentation in this case seemed a little redundant, since all of the documented functions would have this general form:

```js
    /**
     * Perform someOperation and return a new RationalNumber containing the result.
     * @param integerValue - the value to someOperation
     * @returns {RationalNumber}
     */
    someOperation: function( integerValue ) {
      return toRationalNumber( this.bigRational.someOperation( integerValue ) );
    },
```

E.g. for "plus":

```js
    /**
     * Perform addition and return a new RationalNumber containing the result.
     * @param integerValue - the value to add
     * @returns {RationalNumber}
     */
    plus: function( integerValue ) {
      return toRationalNumber( this.bigRational. plus( integerValue ) );
    },
```

But if you think it's useful, let me know and I'll add the doc.

**Comment by ariel-phet** [comment]
unassigned @andrea-phet since seemed like a "fat finger"

**Comment by pixelzoom** [comment]
yep, thanks.

**Comment by pixelzoom** [comment]
Docs added to RationalNumber.  I also renamed a couple of things and fixed a bug in https://github.com/phetsims/function-builder/commit/9f4a9c5d0604ec84c3aece389ae906ec9eb23805.

@andrewadare have a look and see if this is better.

**Comment by andrewadare** [comment]
Looks perfect now, nothing left for me to complain about here. Closing.
