### ISSUE TITLE
create screenshot for web page

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#79]
We'll need to create the screenshot for this sim's page on the PhET site.

Assigning to @amanda-phet to specify what configuration of the sim she'd like to show in the screenshot.

**Comment by pixelzoom** [comment]
@amanda-phet You put the sim in the state you want, then take a screenshot and attach it to a comment in this issue.  I'll use that to create the final screenshot file.

**Comment by pixelzoom** [comment]
Expected to publish 1.0.0 sometime in the next few days, so raising priority to high.

**Comment by amanda-phet** [comment]
Curious if @phet-steele has any ideas for something fun here. I'd like to show the Equations screen, but not be too overwhelming. 

![screen shot 2016-07-11 at 12 12 30 pm 2](https://cloud.githubusercontent.com/assets/7852916/16741529/e2987926-4760-11e6-80fb-723601e894dd.png)

**Comment by pixelzoom** [comment]
Keep in mind that this screenshot is going to be displayed at 128x84 and 300x180.   Here's what your screenshot about will look like at these sizes:

![128](https://cloud.githubusercontent.com/assets/3046552/16742377/b17e8d5e-4764-11e6-8721-5f06327480ea.png)

![128](https://cloud.githubusercontent.com/assets/3046552/16742380/b41720a8-4764-11e6-9be8-522acac4a4bb.png)

At these sizes, equations and points on the graph, and even fractions in the output carousel, will effectively disappear.  So I see no point in showing those features. 

My recommendation would be to show the "Patterns" screen, where the user-interface elements are larger.

**Comment by pixelzoom** [comment]
Also note that the navigation bar needs to be included in the screenshot.  Which means the above example will become even less legible.

**Comment by phet-steele** [comment]
I moved away from the graph since it may be hard to see, and made the outputs whole numbers since fractions would also be harder to see.
![img_0103](https://cloud.githubusercontent.com/assets/5863899/16748043/14315b24-477f-11e6-96fc-e299f68e362b.jpeg)
![img_0103](https://cloud.githubusercontent.com/assets/5863899/16748059/31c9ebf6-477f-11e6-8ad9-db7f9dfaa057.jpeg)


Here's what patterns would look like. I tried to not use the Warhol, since it would just look bad at small sizes. The next best thing to add some color would be to use the rainbow function. I also kept the function carousel on the third page since I thought it was the most visually appealing.
![img_0049](https://cloud.githubusercontent.com/assets/5863899/16748326/a72b76ca-4780-11e6-8bfa-8ebdb2c5fa72.jpeg)
![img_0049](https://cloud.githubusercontent.com/assets/5863899/16748337/b6ac1a6e-4780-11e6-9deb-4ef0cba3cb80.jpeg)

**Comment by pixelzoom** [comment]
Feedback on configurations proposed by @phet-steele immediately above...

"Equations" screenshot:
(1) Looks OK at the larger size, not so good at smaller size.
(2) Patterns screenshot is more appealing to me.

"Patterns" screenshot:
(1) Having the black "invert RGB" function smack dab in the middle of the screenshot doesn't look great. I think it would look a lot better with a fun-colored function in the center.
(2) I wouldn't use one of the mystery functions in the builder, since the text isn't very legible.

**Comment by amanda-phet** [comment]
I agree, Patterns looks better. 

How about this? 

<img width="150" alt="screen shot 2016-07-12 at 3 00 31 pm" src="https://cloud.githubusercontent.com/assets/7852916/16783517/994a9b82-4841-11e6-8e0e-6aa1edb48062.png">

**Comment by pixelzoom** [comment]
Looks OK to me, if you don't mind that the cards in the output carousel are all gray.

**Comment by amanda-phet** [comment]
There's plenty of color elsewhere in the screenshot so I'm ok with the gray.

**Comment by pixelzoom** [comment]
OK. I'll proceed with the icon in https://github.com/phetsims/function-builder/issues/79#issuecomment-232180244. @amanda-phet Can you please attach a larger version of this screenshot. I'll need to give it to someone else to make the screenshot, and a larger screenshot will be easier to "read".

**Comment by amanda-phet** [comment]
<img width="956" alt="screen shot 2016-07-12 at 4 29 49 pm" src="https://cloud.githubusercontent.com/assets/7852916/16785920/0209644e-484e-11e6-87cf-3e1809376793.png">

**Comment by pixelzoom** [comment]
@samreid has volunteered to create the screenshot, since I'm not familiar with the process, and I don't have the necessary equipment (retina iPad).

**Comment by pixelzoom** [comment]
@samreid Please check the screenshot into master as assets/function-builder-screenshot.png. Assign the issue back to me, and I can take care of copying it to the 1.0 branch. Thanks!

**Comment by pixelzoom** [comment]
The final desired configuration for the screenshot is shown in https://github.com/phetsims/function-builder/issues/79#issuecomment-232202043.

**Comment by samreid** [comment]
Can I use rc.2 for the screenshot?

**Comment by pixelzoom** [comment]
Yes, please use 1.0.0-rc.2:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.2/function-builder_en.html

**Comment by samreid** [comment]
Screenshot added above, @pixelzoom please double-check the screenshot for the following:

* correct size
* correct content
* correct filename
* anything else?

**Comment by pixelzoom** [comment]
[7/13/16, 12:45:44 PM] Chris Malley: Sam, one detail missing from the screenshot.  Amanda shows a card (cherries) entering builder.
[7/13/16, 12:45:53 PM] Sam Reid: oh blah, I’m on it.
[7/13/16, 12:46:06 PM] Sam Reid: I see it now!
[7/13/16, 12:46:16 PM] Chris Malley: Should be a fun multi-finger exercise.

**Comment by samreid** [comment]
Added a cherry card above, please review.

**Comment by pixelzoom** [comment]
Looks great. Thanks for your help. Closing.

**Comment by amanda-phet** [comment]
I was wondering if you'd need two people to take that screenshot on an iPad! Nice work @samreid .

**Comment by ariel-phet** [comment]
Tis a beautiful screenshot!

**Comment by pixelzoom** [comment]
Reopening. I forgot to copy the screenshot to the 1.0 release branch.
