### ISSUE TITLE
Eslint failure

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#8]
During build:

Building function-builder
Running "eslint:allFiles" (eslint) task

/Users/samreid/github/function-builder/js/patterns/model/PatternsScene.js
  12:7  error  "CanvasUtils" is defined but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

Warning: Task "eslint:allFiles" failed. Use --force to continue.

Aborted due to warnings.

**Comment by pixelzoom** [comment]
I have master HEAD (sha ac1935c5dc96ce6df94723420b9fda49ebcccbb5) of function-builder in my working copy, and I see no such error with `grunt lint`.   @samreid is your working copy current?

**Comment by pixelzoom** [comment]
`CanvasUtils` was removed from PatternsScene.js on 1/15/2016 at 11:58am, about 18 hours before this issue was created. So I'm guessing that @samreid's working copy isn't current.

**Comment by samreid** [comment]
This update fixed the problem, closing.
