### ISSUE TITLE
review pointerAreas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#81]
I've adjusted pointerAreas (mostly touchAreas) throughout the sim. From the master checklist in https://github.com/phetsims/function-builder/issues/2, this task needs to be completed by the lead designer:

- [ ] Carefully review `?showPointerAreas`

**Comment by pixelzoom** [comment]
By the way...  You'll see pointerAreas for some user-interface components that are not visible on screen due to an issue in scenery (https://github.com/phetsims/scenery/issues/221).   In Function Builder, this occurs for carousels and drawers.  For example, see the screenshot below. The areas indicated with green arrows are buttons for scenery-phet.NumberPickers that are on the second page of the carousel. The areas indicated with orange arrows are two buttons that are inside a scenery-phet.Drawer that is currently closed.  You can rest assured that these user-interface components are not accessible in these situations.  Scenery is simply rendering the blue and red dashed outlines to indicate where their pointerAreas would be if there were accessible.

![pointerareas1](https://cloud.githubusercontent.com/assets/3046552/16535814/c40c83b4-3fa7-11e6-9ce1-9bba73022b36.png)

**Comment by pixelzoom** [comment]
By the way...  You'll see pointerAreas for some user-interface components that are not visible on screen due to an issue in scenery (https://github.com/phetsims/scenery/issues/221).   

In Function Builder, this occurs for carousels and drawers.  For example, see the screenshot below. The areas indicated with green arrows are buttons for NumberPickers that are on the second page of the function carousel. The areas indicated with orange arrows are the two scroll buttons that are inside the "table" drawer.  The red arrow is pointing to the "slope-intercept" check box inside the equation drawer.

You can rest assured that these user-interface components are not accessible in these situations.  Scenery is simply rendering the blue and red dashed outlines to indicate where their pointerAreas would be if there were accessible.

![pointerareas1](https://cloud.githubusercontent.com/assets/3046552/16535860/5233f65e-3fa8-11e6-9bd0-c80f68748c88.png)

**Comment by pixelzoom** [comment]
Raising priority to "top", since this is a prerequisite for meeting the "final change requests" deadline in https://github.com/phetsims/function-builder/issues/86.

**Comment by amanda-phet** [comment]
These look good to me.
