### ISSUE TITLE
Spurious pointer areas?

### ISSUE THREAD

**Issue by andrewadare** [phetsims/function-builder#85]
When running with `showPointerAreas`, I see a few surprising rectangles:

![image](https://cloud.githubusercontent.com/assets/154163/16596485/66df5600-42b1-11e6-9140-ab66e1aa92d5.png)

![image](https://cloud.githubusercontent.com/assets/154163/16596517/8b6031ca-42b1-11e6-91ae-ac8530babbc2.png)

These may not be a problem at all, just curious what they are. They are not clickable or draggable for me.

**Comment by pixelzoom** [comment]
This is a scenery issue.  Described in detail in https://github.com/phetsims/function-builder/issues/81#issuecomment-230060282.

Closing.

**Comment by pixelzoom** [comment]
Related to #55.
