### ISSUE TITLE
sim reviewed by team

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#86]
Function Builder is complete, and ready for review by the team.  Use this dev version:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.69/function-builder_en.html

**Final change requests are due by Monday, July 11, 9:00am**.  While that is technically the deadline, the schedule is tight.  If you can review sooner, then final dev testing can begin sooner, and that will increase the probability of an on-time publication.

If you have a change request, please create a GitHub issue.  When you have reviewed the simulation, (or if you don't have time to review and want to waive your review) please check off your name below.

- [x] @amanda-phet 
- [x] @amyh-phet  
- [x] @ariel-phet 
- [x] @bethstade 
- [x] @kathy-phet 
- [x] @samreid

**Comment by samreid** [comment]
Should we be reviewing this version? http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.69/function-builder_en.html

**Comment by pixelzoom** [comment]
Yes, thanks, you beat me to it :)

**Comment by ariel-phet** [comment]
Have looked at the sim many times, but give it another walk through. All looks great!

**Comment by samreid** [comment]
I took a brief test drive on mac firefox, everything looks very nice, no issues noted.

**Comment by amyh-phet** [comment]
Tested on PC using Chrome and looked great.  No issues to report.

**Comment by bethstade** [comment]
Looks consistent with what was discussed. Everything I tried seemed functional and correct.

**Comment by kathy-phet** [comment]
Looks great. Submitted one pedagogical question for consideration in case of "times 0" scenario.

**Comment by amanda-phet** [comment]
Based on interviews and my final look-through, the only open question for me is the "selfie" icon for the identity function. In my 3 interviews this week, students did not associate the selfie icon with the "does nothing" function. After talking with them, I still don't have a better idea. A mirror could work, but then we'd need a new icon for reflection... perhaps a reflection of a tree in a pond?? 

If anyone has an idea please email me (do not respond in this issue), otherwise this may remain a mystery to users.

**Comment by amanda-phet** [comment]
My husband said, "have you thought about a Congress icon?" 😜

**Comment by pixelzoom** [comment]
Moved the issue of the identity function icon to #91, assigned to @amanda-phet.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/function-builder/issues/86#issuecomment-231242747, @amanda-phet said:
> Based on interviews and my final look-through, the only open question for me is ...

@amanda-phet Are you ready to check your name off in https://github.com/phetsims/function-builder/issues/86#issue-163928049? If so, I can proceed with dev testing.

**Comment by amanda-phet** [comment]
Yes. Checked off.

**Comment by pixelzoom** [comment]
Team review completed. Change requests are all tracked in separate issues.

Closing.

**Comment by pixelzoom** [comment]
@amanda-phet I've checked off and dated "Lead designer sign off" in the master checklist (#2), since all of its sub-items are completed.
