### ISSUE TITLE
change behavior of "helpful" equation on "times 0" scenario

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/function-builder#87]
Function Builder is amazing. I am logging this issue to revisit the question of the equation behavior with times "0". As I played with the sim this time, I was struck by the significant change in the equation display when I passed through 0. So instead of keeping the "helpful" view, it simplified all the way down to -9 in my case, instead of reading y=3(0x-3). Since the slope intercept form reads y=-9 and the x card would read y=-9, and some students might get confused as to why x is entirely missing, I wanted to consider not having this simplification rule for 0 in our "helpful" form case ... and just leaving the full equation y=3(0x-3) to help support that understanding that it is -9 because  you have multiplied x times 0.

**Comment by pixelzoom** [comment]
This will take 2-4 hours to change and test.

To stay on schedule, I'll need a decision on this by 9am on Monday 7/11.

**Comment by pixelzoom** [comment]
Mentioning @ariel-phet and @bethstade, since they were involved in specifying the current behavior.  Please weigh in.

**Comment by ariel-phet** [comment]
I defer to @amanda-phet - this is a pedagogical question in my mind.

**Comment by amanda-phet** [comment]
I reviewed the equation formats [here] (https://github.com/phetsims/function-builder/blob/master/doc/equation-formats.md) and the suggestion that Kathy is making is more consistent with the non-zero formatting. I think we should go ahead with this change. 

Looking at the table of formats, the following rows will change: 

| Builder  | Helpful | Slope-Intercept |
| ------------- | ------------- | ------------- | 
| * 0 * 2  | y=0x  | y=0 |
| / 3 * 0 	| y = 0(x/3) 	| y = 0|
| * 0 / 3 |	y = [0x]/3 	| y = 0|
| * 0 * 2 + 1 	| y = 0x + 1 |	y = 1|
| * 0 + 1 * 2 	| y = 2(0x + 1) | 	y = 2|

**Comment by pixelzoom** [comment]
OK, I'll proceed with this change.

**Comment by pixelzoom** [comment]
Specification (equation-formats.md) has been updated, and the change is implemented in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.70/function-builder_en.html

@amanda-phet and @kathy-phet please verify that this is what you had in mind.

**Comment by kathy-phet** [comment]
Looks great on this fix! Thanks! 

However, I see the font size in the card used up space is much smaller now. I find that hard to read and I think it makes it harder to see the input-output association with the very small values there. And projection will be really hard. Not sure which issue this change was requested in.

**Comment by pixelzoom** [comment]
@kathy-phet said:
> However, I see the font size in the card used up space is much smaller now.

I made no changes to font sizes. So I'm not clear on what you're saying here, or what you're proposing to fix/change.  

But `y = [0x]/3` is of course going to be larger than `y = 0`, so it's necessarily going to be shrunk down to fit in the equation panel.  And this is no different than what we were doing for non-zero cases, e.g. `y = [2x]/3`.

**Comment by kathy-phet** [comment]
I opened a new issue to address the above observation. 

Regarding this issue, feel free to close --- all looks good to me.

**Comment by amanda-phet** [comment]
Looks great to me!

**Comment by pixelzoom** [comment]
Related to #86
