### ISSUE TITLE
Font in emply input card slot small

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/function-builder#89]
Working on windows, chrome. 

Here is what it looks like now: 
![image](https://cloud.githubusercontent.com/assets/5096804/16669773/8c120d24-4454-11e6-8430-09dd4230b00d.png)

It was fine in v69

**Comment by kathy-phet** [comment]
Here is my info: 
Troubleshooting information (do not edit):
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.70/function-builder_en.html
Version: 1.0.0-dev.70 2016-07-07 18:29:29 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Language: en-US
Window: 1920x973
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"83211f20","branch":"master"},"babel":{"sha":"452ce1dc","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"4ab176ca","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"function-builder":{"sha":"edccf415","branch":"master"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"77506dc3","branch":"master"},"sun":{"sha":"cccaf534","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by amanda-phet** [comment]
I am seeing that too.

**Comment by pixelzoom** [comment]
Related to #86

**Comment by pixelzoom** [comment]
Thanks, good catch. Bug was introduced in https://github.com/phetsims/function-builder/commit/79f56eb30fd927f04b3b33fef7be6a527b9fb467 for #88.  Fixed in above commit, demonstrated in this dev version:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.71/function-builder_en.html

@kathy-phet or @amanda-phet please verify.  Whoever does verify can close this issue if all looks OK.

**Comment by amanda-phet** [comment]
Seems to be working just fine now. Closing.
