### ISSUE TITLE
revise icon for identity function?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/function-builder#91]
In https://github.com/phetsims/function-builder/issues/86#issuecomment-231242747, @amanda-phet said:

Based on interviews and my final look-through, the only open question for me is the "selfie" icon for the identity function. In my 3 interviews this week, students did not associate the selfie icon with the "does nothing" function. After talking with them, I still don't have a better idea. A mirror could work, but then we'd need a new icon for reflection... perhaps a reflection of a tree in a pond??

If anyone has an idea please email me (do not respond in this issue), otherwise this may remain a mystery to users.

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/function-builder/issues/46 for previous discussion about the identity icon.

**Comment by pixelzoom** [comment]
>  perhaps a reflection of a tree in a pond??

This would be a reflection about the x axis, not the y axis, and would also require a change to the code that implements the image processing function.

**Comment by amanda-phet** [comment]
@ariel-phet has mentioned in the past a "blank" card, and reminded me of it again. I never wanted to do it, because the identity is a function and I wanted it to be represented in some way, but a blank card seems like it would be very clear to users that the function "does nothing" and there is no icon to figure out. 

So I'll make an executive decision to leave this card blank (no icon). I would much rather have a "boring but obvious" (@ariel-phet ) function than a confusing but important one. 

Assigning to @pixelzoom to implement.

**Comment by pixelzoom** [comment]
The icon has been removed on the identity function in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.72/function-builder_en.html

After removing the icon, I noticed that the identity and Warhol functions have background colors that are nearly identical.  Without the icon on the identify function, this seemed problematic - students might make an association with Warhol based on colors.  So I chose a unique color (RGB=255,255,128) for the identity function, as shown in this screenshot:

![screenshot_48](https://cloud.githubusercontent.com/assets/3046552/16735265/b19a3e74-4745-11e6-91eb-a30f60be86fb.png)

I also considered using 'white', so that there would be no association between the function and color. But that made the function look a bit list a "ghost" function (similar to the "ghost" cards), as demonstrated in this screenshot:

![screenshot_47](https://cloud.githubusercontent.com/assets/3046552/16735302/d34c3946-4745-11e6-9a54-0e7872f45218.png)

@amanda-phet If you like to use a different color for the identity function, please specify and assign this issue back to me. Otherwise please close this issue.

**Comment by amanda-phet** [comment]
I think yellow works, but I prefer a softer shade. Can you use #FFF692?

**Comment by pixelzoom** [comment]
#FFF692 is 'rgb( 255, 246, 146 )', changed in this dev version:
http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.73/function-builder_en.html

@amanda-phet please verify.

Screenshot:

![screenshot_49](https://cloud.githubusercontent.com/assets/3046552/16737569/3b030bb0-474f-11e6-939c-1125ef1933ab.png)

**Comment by amanda-phet** [comment]
Looks great. Thanks!
