### ISSUE TITLE
[iOS] Poor performance on iPad 2, iOS 8.4.1

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/function-builder#94]
For phetsims/tasks#638
Test Device: Lave
Operating System: iOS 8.4.1
Browser: Safari 

Problem Description: Very poor performance on the iPad 2, iOS 8.4.1 on **every** screen. Functions are very difficult to move after completely populating the output carousel. Treat this as similar to #36 with regards to the issue details, but this performance is much worse both because functions lag much more when dragged, the function combination does not matter, and only one instance of each card is needed to cause bad performance. 

Steps to Reproduce:
1. Place any three functions into the function machine slots
2. Drag one instance of each input through the function machine
3. Drag any of the functions to or from the function machine

Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.1/function-builder_en.html
Version: 1.0.0-rc.1 2016-07-11 16:15:00 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4
Language: en-us
Window: 1024x648
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-115.5)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"101ec12c","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"9059e93b","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"function-builder":{"sha":"7daf67e1","branch":"1.0"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"cccaf534","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by pixelzoom** [comment]
@amanda-phet Is this specific to any particular screen, or all screens?

**Comment by pixelzoom** [comment]
@alynne-phet  Is this specific to any particular screen, or all screens?

**Comment by phet-steele** [comment]
@pixelzoom 
> Very poor performance on the iPad 2, iOS 8.4.1 on every screen.

**Comment by pixelzoom** [comment]
@alynne-phet Is the performance similar on iOS 9 ?

**Comment by alynne-phet** [comment]
@pixelzoom, @phet-steele says iOS 9 performance is equivalent to what was deemed acceptable in #36.

**Comment by ariel-phet** [comment]
I think this may be the final straw on iOS 8 support for us, I will get @oliver-phet to pull some numbers.

**Comment by phet-steele** [comment]
@ariel-phet Iwas about to ask the same :1:

**Comment by pixelzoom** [comment]
I tested again on my iPad2 with iOS 9, and performance is still fine.

@ariel-phet wrote:
> I think this may be the final straw on iOS 8 support for us, I will get @oliver-phet to pull some numbers.

Can I infer from this that you'd like me to close this issues at "won't fix"?

**Comment by ariel-phet** [comment]
Yes, I think so. Looks like iOS 8 is a little less than 1 percent of our overall usage, so probably time to cut the cord. Will finalize at dev meeting, but going to close this issue.
