### ISSUE TITLE
Function machines have different length

### ISSUE THREAD

**Issue by phet-steele** [phetsims/function-builder#95]
@amanda-phet @pixelzoom the 3-slot function machine on the Patterns screen is slightly shorter than the 3-slot function machines on the Equations and Mystery screens, can it be made slightly larger? You can see the difference by switching between the Patterns and Equations screen (when viewing the 3-slot machine of course).

Seen on everything, for phetsims/tasks/issues/638.

Troubleshooting information:
Name: ‪Function Builder‬
URL: http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.1/function-builder_en.html
Version: 1.0.0-rc.1 2016-07-11 16:15:00 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
Language: en-US
Window: 1536x739
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9a0e2f3a","branch":"master"},"babel":{"sha":"101ec12c","branch":"master"},"brand":{"sha":"f0b1f7da","branch":"master"},"chipper":{"sha":"9059e93b","branch":"master"},"dot":{"sha":"3628c3ae","branch":"master"},"function-builder":{"sha":"7daf67e1","branch":"1.0"},"joist":{"sha":"94bc734c","branch":"master"},"kite":{"sha":"88f0c3a0","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"35ef94ad","branch":"master"},"scenery":{"sha":"942889ad","branch":"master"},"scenery-phet":{"sha":"0d6b589e","branch":"master"},"sherpa":{"sha":"03590a07","branch":"master"},"sun":{"sha":"cccaf534","branch":"master"},"tandem":{"sha":"a8ac284b","branch":"master"},"twixt":{"sha":"53b31872","branch":"master"}}

**Comment by amanda-phet** [comment]
Good catch! I agree that they should be the same.

**Comment by pixelzoom** [comment]
@amanda-phet wrote:
> Good catch! I agree that they should be the same.

The options are:

(1) Make the builder in the Patterns screen longer.

(2) Make the builder in the Equations & Mystery screens short, which will require making the table and graph narrower.

I'm assuming that you'll want option (1), but just checking.

**Comment by pixelzoom** [comment]
I went ahead and made the 3-slot builder in the Patterns screen longer, to match the Equations and Mystery screens. @amanda-phet please verify that that is acceptable.

**Comment by pixelzoom** [comment]
@amanda-phet You can also verify in this dev version:

http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-dev.74/function-builder_en.html

**Comment by amanda-phet** [comment]
Yup, option (1). Looks good. Closing.

**Comment by pixelzoom** [comment]
Reopening so that I remember to put this on the verification list for 1.0.0-rc.2.

**Comment by pixelzoom** [comment]
Please verify in http://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.0-rc.2/function-builder_en.html.

**Comment by phet-steele** [comment]
Verified on Win 7 & 10 Chrome, OSX 10.11.5 Chrome, and iPad2 iOS 9.3.3
