### ISSUE TITLE
Random number sequences should be reproducible

### ISSUE THREAD

**Issue by samreid** [phetsims/function-builder#99]
In order to support deterministic playback for phet-io for https://github.com/phetsims/phet-io/issues/548, the random number sequences must be reproducible.  In the case of Function Builder, this can be done by changing `new Random()` to `new Random( { staticSeed: true } )`.  The randomness can be tested using a link like:

http://localhost/phet-io/html/wrappers/mirror-input-events.html?sim=function-builder&phet-io.validateTandems=false

Control the top one and see if the bottom one matches.  I've tested with the `staticSeed` and all seems well, so I will commit.  Afterwards, I'd also like @pixelzoom to review the changes and make sure they are good, as well as commenting on whether there are any other sources of randomness in the sim.

**Comment by samreid** [comment]
Fixed above, reassigned to @pixelzoom for feedback as described in the issue description.

**Comment by samreid** [comment]
Grunt is passing, sim is launching.

**Comment by pixelzoom** [comment]
8/18/16 dev meeting:  It's worth replacing DOT.Random with phet.joist.random. I'll do this.

**Comment by pixelzoom** [comment]
I replaced DOT.Random with phet.joist.random in the above commit. @samreid could you please take a look, to make sure that I understood everything that needs to be done?  If it looks OK, feel free to close this issue.

**Comment by samreid** [comment]
Looks perfect, thanks! Closing.
